function UTCases = set_up_UT_cases_SNRUnitRecon;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    
    'VB17A_Gadgetron_testdata\7T',          'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648', 'VB',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SNR_Unit_Recon\BuildInNoiseScan', 'meas_MID00134_FID02871_GRE_reps=150__WIP724_sPAT=3_weak_asymmetric_echo', 'VB',   'GT_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data2', 'meas_MID00321_FID03058_GRE_reps=150_sPAT=2_phs_res_75_peFOV75_pf=7_8_weak_asym', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00146_FID03200_GRE_reps20_xRes256_dummy1', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00147_FID03201_GRE_reps=20_sPat2_xRes256_dummy1', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00148_FID03202_GRE_reps=20_sPat3_xRes256_dummy1', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00149_FID03203_GRE_reps=20_sPat4_xRes256_dummy1', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00150_FID03204_GRE_reps=20_xRes256_dummy1_FOV240', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00151_FID03205_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00153_FID03207_GRE_reps=20_sPAT4_xRes256_dummy1_FOV240', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00154_FID03208_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240_strong_asym', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00155_FID03209_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240_strong_asym_7_8pf', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3', 'meas_MID00152_FID03206_GRE_reps=20_sPAT3_xRes256_dummy1_FOV240', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SNR_Unit_Recon\Childrens',                      'meas_MID00087_FID34565_CV_Gadgetron_GFactor_R1', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00158_FID02895_GRE_reps=150_sPAT=2', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00159_FID02896_GRE_reps=150_sPAT=3', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00160_FID02897_GRE_reps=150_sPAT=4', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00169_FID02906_GRE_reps=150_TPAT=2', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00171_FID02908_GRE_reps=150_TPAT=3', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00172_FID02909_GRE_reps=150_TPAT=4', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00170_FID02907_GRE_reps=150_higher_BW', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00161_FID02898_GRE_reps=150_strong_asym_echo', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00162_FID02899_GRE_reps=150_strong_asym_echo_6_8_partial_fourier', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00163_FID02900_GRE_reps=150_sPAT=2_strong_asym_echo', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00164_FID02901_GRE_reps=150_sPAT=3_strong_asym_echo', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00165_FID02902_GRE_reps=150_sPAT=4_strong_asym_echo', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00166_FID02903_GRE_reps=150_sPAT=2_strong_asym_echo_6_8_partial_fourier', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00167_FID02904_GRE_reps=150_sPAT=3_strong_asym_echo_6_8_partial_fourier', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00168_FID02905_GRE_reps=150_sPAT=4_strong_asym_echo_6_8_partial_fourier', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00173_FID02910_GRE_reps=150_iPAT=2', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00174_FID02911_GRE_reps=150_iPAT=3', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00175_FID02912_GRE_reps=150_iPAT=4', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00179_FID02916_GRE_reps=150_prescan_normalize', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SNR_Unit_Recon\skyra',                          'meas_MID00140_FID37475_CV_Gadgetron_FL_TPAT2_60REP',       'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'SNR_Unit_Recon\skyra',                          'meas_MID00138_FID37473_CV_Gadgetron_FL_TPAT2_StrongAsymEcho_60REP', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\skyra',                          'meas_MID00137_FID37472_CV_Gadgetron_FL_TPAT3_StrongAsymEcho_60REP', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\skyra',                          'meas_MID00141_FID37476_CV_Gadgetron_FL_TPAT4_StrongAsymEcho_60REP', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'SNR_Unit_Recon\skyra',                          'meas_MID00142_FID37477_CV_Gadgetron_FL_TPAT3_StrongAsymEcho_30REP', 'VD',   'GT_2DT_Cartesian_GFactor_NoiseStd.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'SNR_Unit_Recon\BuildInNoiseScan',                          'meas_MID00143_FID02880_GRE_reps=150__WIP724_noPAT_strong_asym_echo_6_8_partial_fourier', 'VB',   'GT_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
