function UTCases = set_up_UT_cases_Cine;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'cine',                  'meas_MID00034_FID69052_Stress_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',                                  'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141106_17h08m37s_28065',                                     'VD',   'GTPrep_2DT_RealTimeCine.xml',                                  'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141106_17h08m37s_28065',                                     'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',                             'grappa_gfactor_res',      'grappa_gfactor_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'CV_Sparse',             'meas_MID00387_FID21047_4CH_CVsparse_rt_net12_0','VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                            'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             '20130123_14h51m33s_759','VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                                                    'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    
    'CV_Sparse',             'meas_MID00171_FID60124_RealTimeCineNonLinear','VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                                                    'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    
    'CV_Sparse',             'meas_MID00306_FID348232_Cine_SA_4CH_2CH_SPARSE','VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_DualLayer_Gateway.xml',   'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
   
     'binning',                  '20150702_10h47m29s_54199',                                     'VD',   'GTPrep_2DT_RealTimeCine.xml',                                  'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
     
     'binning',                  '20150702_10h47m29s_54199',                                     'VD',   'GTPrep_2DT_RealTimeCine.xml',                                  'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
     
     'binning',                  'meas_MID00322_FID06960_RealTimeCineBinning',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
