function UTCases = set_up_UT_cases_GT_UT;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'GT_UT/simple_gre',       'meas_MiniGadgetron_GRE',                    'VB',   'default.xml',      'res',           'ref',   'IsmrmrdParameterMap.xsl'   ; ...
    % 'GT_UT/simple_gre',       'meas_MiniGadgetron_GRE',                    'VB',   'distributed_default.xml',      'res',           'ref',   'IsmrmrdParameterMap.xsl'   ; ...
    'GT_UT/gre_3d',           'meas_MID248_gre_FID30644',                  'VB',   'default_optimized.xml', 'res',      'ref',   'IsmrmrdParameterMap.xsl'   ; ...
    
    'GT_UT/T2W',              'meas_MID00057_T2w',                         'VD',   'GT_2DT_T2W.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/LGE',              'meas_MID00083_9_slice',                     'VD',   'GT_2DT_LGE.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/3D_head',          'meas_MID00156_FID05944_GRE_128iso_p2x2',    'VD',   'GT_3DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/FatWater',         'meas_MID00342_3e2i_R4',                     'VD',   'GT_2DT_FatWater.xml', 'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/FetalHASTE',       'raw30488',                                  'VD',   'GT_2DT_HASTE.xml', 'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/localizer',        'meas_MID00026',                             'VD',   'GT_2DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/localizer',        'meas_MID00026',                             'VD',   'GT_2DT_Cartesian_Dicom.xml', 'res_dicom',       'ref_dicom',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/MOLLI',            '20100330_10h33m11s_5562',                   'VD11', 'GT_2DT_MOLLI.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/Perfusion',        'meas_MID00045_R3_AIF_ON',                   'VD',   'GT_2DT_Perfusion.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/RealTimeCine',     'meas_MID21_CINE_R4',                        'VD',   'GT_2DT_RealTimeCine.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/RealTimeCine',     'meas_MID21_CINE_R4',                        'VD',   'GT_2DT_Cartesian_GFactor.xml', 'gfactor_res',       'gfactor_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/RealTimeCine_9slices',     'meas_MID00832',                     'VD',   'GT_2DT_RealTimeCine.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/sasha',            '20140325_15h59m29s_7720',                   'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_builtin_noise',   'meas_MID00127_FID02864_GRE_reps=150__WIP724_sPAT=4',                   'VD11',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_ipat4',           'meas_MID00175_FID02912_GRE_reps=150_iPAT=4',                   'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/ProspectiveCine',                'meas_MID00209_FID07469_CV_gtPlus_2D_epat4',                   'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_spat2_asym_pf',   'meas_MID00156_FID03210_GRE_reps=50_sPAT2_xRes256_dummy1_FOV240_strong_asym_7_8pf',                   'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_spat3',           'meas_MID00152_FID03206_GRE_reps=20_sPAT3_xRes256_dummy1_FOV240',                   'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_tpat3',           'meas_MID00171_FID02908_GRE_reps=150_TPAT=3',                   'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    
    'GT_UT/CineBinning',                  'meas_MID836_PK_rt_test_1slice_FID22517',                       'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/CineBinning',                  'meas_MID838_PK_rt_test_2slice_FID22519',                       'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'GT_UT/Nonlinear',                    '20140703_11h09m11s_12297',                                     'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',             'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/7T',          'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648',               'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/RetroGating',           'meas_MID00385_FID00375_RetroCine_NL_15msT_Res192_NHLBI_Cloud',        'VD',   'GTPrep_2DT_RetroGated_Cine.xml',                                 'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    'GT_UT/LGE',                   'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/RealTimeFlow',          'meas_MID00089_FID19207_real_time_flow_R5_30s',                        'VD',   'GTPrep_2DT_RTFlow_KspaceBinning.xml',                          'binning_res',             'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/T2W',                   'meas_MID00057_FID25460_QQQ_4ch_CV_T2w_567C_MOCO',                     'VD',   'GTPrep_2DT_T2W_MOCO_AVE.xml',                                                  'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/t2star',                'meas_MID42_CV_me_584_T2Star_FID2535',                                 'VB',   'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/B1Mapping',               'meas_MID00089_FID22003_STACK_B1Map_ep2d_fid_snv_gt_a120_rep30_PAT2_VREF750_FOV320',  'VD',   'B1mapping.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'  ; ...
    'GT_UT/epi',               'meas_MID517_nih_ep2d_bold_fa60_FID82077',  'VD',   'epi.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'  ; ...
    
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
