function UTCases = set_up_UT_cases_ScannerUpdate;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'mapping\20150111\SASHA',                  '20140623_13h07m42s_22785',                       'VD',   'GTPrep_2DT_SASHA.xml',                           'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',                       'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20140703_11h09m11s_12297',                                     'VD',   'GTPrep_2DT_Cartesian_L1SPIRIT.xml',                                            'l1spirit_res',            'l1spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',                                     'VD',   'GTPrep_2DT_RealTimeCine.xml',                                                  'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',                                     'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',             'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',                                     'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_CoilMap.xml',             'slep_coil_map_res',                'slep_coil_map_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'GTPrep_2DT_RealTimeCine.xml',  'grappa_res', 'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID838_PK_rt_test_2slice_FID22519', 'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',  'binning_res', 'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00451_FID17024_CV_gtPlus_RealTimeCine_KSpaceBinning_NHLBI_cloud', 'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',               'binning_res',             'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00451_FID17024_CV_gtPlus_RealTimeCine_KSpaceBinning_NHLBI_cloud', 'VD',   'GTPrep_2DT_RTCine_KspaceBinning_FFT.xml',           'binning_fft_res',         'binning_fft_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'GTPrep_2DT_RealTimeCine.xml',  'grappa_res', 'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'CV_Sparse',             '20130123_14h51m33s_759',                                           'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res', 'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...
    'CV_Sparse',             '20130123_14h51m33s_759',                                           'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_CoilMap.xml',  'slep_coil_map_res', 'slep_coil_map_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...

    'CV_Sparse',             'meas_MID01300_FID40320_PK_CVsparse_rt_net12_0',                    'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res', 'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...    
    'CV_Sparse',             'meas_MID01300_FID40320_PK_CVsparse_rt_net12_0',                    'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_CoilMap.xml',  'slep_coil_map_res', 'slep_coil_map_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...
    
    'CV_Sparse',             'meas_MID01095_FID40115_PK_CVsparse_rt_net12_0',                    'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res', 'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...    
    'CV_Sparse',             'meas_MID01095_FID40115_PK_CVsparse_rt_net12_0',                    'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_CoilMap.xml',  'slep_coil_map_res', 'slep_coil_map_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...

    'CV_Sparse',             'meas_MID01402_FID40422_PK_CVsparse_rt_net12_0',                    'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res', 'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...    
    'CV_Sparse',             'meas_MID01402_FID40422_PK_CVsparse_rt_net12_0',                    'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_CoilMap.xml',  'slep_coil_map_res', 'slep_coil_map_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...

    'hxue_data\data_20140924', 'meas_MID00318_FID06956_RTCineNL_SingleSlice',                'VD',   'GTPrep_2DT_RealTimeCine.xml', 'grappa_res', 'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'hxue_data\data_20140924', 'meas_MID00302_FID06940_RTCineNL_NHLBI',                'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml', 'slep_res', 'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    %'hxue_data\data_20140924',               'meas_MID00322_FID06960_RealTimeCineBinning',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'VB17A_Gadgetron_testdata\7T',          'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648', 'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'VB17A_Gadgetron_testdata',  'psir_moco2', 'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',           'moco_ave_res',         'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'perfusion',             '20140408_13h17m13s_10066',                                     'VD',   'GTPrep_2DT_Perfusion_AIF.xml',                                 'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'perfusion',             '20141212_16h18m30s_53904',                                     'VD',   'GTPrep_2DT_Perfusion_AIF.xml',                                 'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
   
    'RetroGating',           'meas_MID00029_FID24055_tf2d9_retro_iPAT5',                     'VD',   'GTPrep_2DT_RetroGated_Cine.xml',                                               'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    'RetroGating',           'meas_MID00039_FID24273_RetroCine_sPAT5_Res256_3sBH',           'VD',   'GTPrep_2DT_RetroGated_Cine_L1SPIRIT_SLEP.xml',                                 'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    'RetroGating',           'meas_MID00385_FID00375_RetroCine_NL_15msT_Res192_NHLBI_Cloud',              'VD',   'GTPrep_2DT_RetroGated_Cine.xml',                                 'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    
    'LGE',                   'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',  'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',                   'meas_MID00082_FID36121_21MIN_gt_PSIR_SSFP_9sl_8ave_MOCO',      'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\SCC_Test',          '20150309_12h35m43s_67676',      'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',                   '20150407_13h40m49s_39106',      'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'RealTimeFlow',          'meas_MID00089_FID19207_real_time_flow_R5_30s',                 'VD',   'GTPrep_2DT_RTFlow_KspaceBinning.xml',                          'binning_res',             'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'binning',               '20140808_10h47m38s_16690',                                     'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                          'binning_res',             'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'binning',               'meas_MID00391_FID21051_4CH_CV_binning',                        'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                          'binning_res',             'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2w',                   'meas_MID00057_FID25460_QQQ_4ch_CV_T2w_567C_MOCO',              'VD',   'GTPrep_2DT_T2W_MOCO_AVE.xml',                                                  'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2w',                   'meas_MID00123_FID43785_gt_CV_T2w_segmented',                   'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',                                                  'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2w',                   'meas_MID00124_FID43786_gt_T2w_1sl_8ave_MOCO',                  'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',                                                  'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star',                '20140530_15h08m15s_18550',              'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star\VB17',                'meas_MID42_CV_me_584_T2Star_FID2535',              'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',                'meas_MID45_CV_me_584K_DB_FB_160_FID123521',        'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',                'meas_MID198_CV_me_584Z_DB_BH_256_FID140066',        'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star\VB17',                'meas_MID285_CV_me_584Z_DB_BH_256_FS_FID140153',        'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',                'meas_MID286_CV_me_584Z_DB_BH_128_FS_FID140154',        'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',                'meas_MID287_CV_me_584Z_DB_FB_160_FS_FID140155',        'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',                'meas_MID288_CV_me_584Z_DB_FB_128_FS_FID140156',        'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star',                '20140609_10h40m42s_20069',                          'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                'meas_MID02074_FID72649_Gadgetron_T2Star_BH_DB_8e',  'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                '20140530_15h06m05s_18546',  'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                'meas_MID00594_FID41000_Gadgetron_T2Star_MOCO_DB_8e',  'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                '20140530_15h08m15s_18550',  'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
   
    %'CDTI_EPI_Data',         'meas_MID00125_FID22039_STEAM_TD300_2x2x8_b500_AVE2_TE30_RR680_VREF750',              'VD',   'DTI.xml',                                                                 'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI_DTI.xsl'  ; ...
    'B1Mapping',               'meas_MID00089_FID22003_STACK_B1Map_ep2d_fid_snv_gt_a120_rep30_PAT2_VREF750_FOV320',  'VD',   'B1mapping.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'  ; ...
    'B1Mapping',               'meas_MID00067_FID57353_B1MAP_BH_a90_rep30_PAT2',  'VD',   'B1mapping.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'  ; ...
    
    % IRT
    'IRT',               'meas_MID00051_FID32838_MiniIRT_3slc',  'VD',   'grappa_device.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    'IRT',               'meas_MID00379_FID33156_MiniIRT_3slc',  'VD',   'grappa_device.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    
    % 'cine',                  'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',          'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',  'slep_res', 'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SNR_Unit_Recon\Childrens',          'meas_MID00087_FID34565_CV_Gadgetron_GFactor_R1', 'VD',   'GT_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\AdjNoiseScan\20140404',          'meas_MID00158_FID02895_GRE_reps=150_sPAT=2', 'VD',   'GT_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'SNR_Unit_Recon\SNR_unit_data3',          'meas_MID00154_FID03208_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240_strong_asym', 'VD',   'GT_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
