function UTCases = set_up_UT_cases_Cloud;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = { 'cine',                  'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',          'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...          
            'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',                'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_SingleSlice_Gateway.xml', 'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % 160 * 120, R5
            'cine',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
            % 192*144, R5, 9 slice cine
            'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_CoilMap_DualLayer_Gateway.xml',  'slep_coil_map_cloud_res', 'slep_coil_map_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  '20141205_15h37m58s_31798',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141027_15h31m18s_26452',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141023_08h43m35s_26080',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141020_16h11m10s_25740',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141017_10h09m21s_25173',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141013_15h07m14s_24419',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141008_13h20m39s_23934',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141007_12h31m16s_23730',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141007_08h03m17s_23619',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
           
            % 256*120, R6, 9 slice cine
            'cine',                  '20141007_10h39m51s_23674',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141219_13h53m08s_33457',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141017_10h09m21s_25173',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'CV_Sparse',             '20130123_14h51m33s_759',                                           'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...
            'CV_Sparse',             '20130123_14h51m33s_759',                                           'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_CoilMap_DualLayer_Gateway.xml',  'slep_coil_map_cloud_res', 'slep_coil_map_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...
            'CV_Sparse',             'meas_MID00381_FID34951_CVsparse_10sl_rt_30msTempoalRes',           'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling_CoilMap_DualLayer_Gateway.xml',  'slep_coil_map_cloud_res', 'slep_coil_map_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_SPARSE.xsl'   ; ...
            
            % binning, 192*144, 16s data
            'binning',               'meas_MID01145_FID12389_RealTimeCine_KSpaceBinning_Amazon_cloud',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'binning',               'meas_MID01145_FID12389_RealTimeCine_KSpaceBinning_Amazon_cloud',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway_Amazon_Cloud.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % binning, 256*192, 20s data
            'binning',               'meas_MID01147_FID12391_RealTimeCine_KSpaceBinning_Res256_Amazon_cloud',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % binning, CNMC
            'binning',               '20150515_12h47m26s_48845',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'binning',               '20150702_10h47m29s_54199',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % 'hxue_data\data_20140924',                  'meas_MID00316_FID06954_RTCineNL_Res240', 'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % cine, single slice, 192*144, R5
            'hxue_data\data_20140924',                  'meas_MID00318_FID06956_RTCineNL_SingleSlice',                'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_SingleSlice_Gateway.xml', 'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % binning, 192*144, 16s data
            'hxue_data\data_20140924',               'meas_MID00322_FID06960_RealTimeCineBinning',   'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'FISP_Perfusion_TPAT3',               'meas_MID00315_FID26114_PerfusionStress_inject',   'VD',   'GTPrep_2DT_Perfusion_NonLinear_Gateway.xml',             'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...         
            
            'perfusion',             'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',   'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',                                  'grappa_flow_res',              'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
