function UTCases = set_up_UT_cases_LGE;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'LGE\SCC_Test',         '20150302_10h50m25s_66537',         'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\SCC_Test',         '20150302_10h50m25s_66537',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'LGE\SCC_Test',         '20150306_16h05m28s_40842',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
     
    'LGE\SCC_Test',         '20150309_12h35m43s_67676',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
     
    'LGE',         'meas_MID03010_FID17085_L46_6_CV_gtPlus_PSIR_1sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID02838_FID26818_L54_0_postCV_gtPlus_PSIR_1sl_32ave_MOCO_highRes',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE',         'meas_MID02931_FID17006_postCV_gtPlus_PSIR_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID02838_FID26818_L54_0_postCV_gtPlus_PSIR_1sl_32ave_MOCO_highRes',         'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID02838_FID26818_L54_0_postCV_gtPlus_PSIR_1sl_32ave_MOCO_highRes',         'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE',         '20150306_16h06m18s_40844',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         '20150306_16h06m18s_40844',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_NonLinear.xml',                               'moco_ave_nl_res',         'moco_ave_nl_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE',         'meas_MID00434_FID42820_4CH_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID00435_FID42821_4CH_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID00436_FID42822_4CH_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID00437_FID42823_4CH_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID00438_FID42824_4CH_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID00439_FID42825_4CH_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE',         'meas_MID00076_FID60410_gt_PSIR_FLASH_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\BLOOD_INHOMOGENEITY',         '20150521_12h54m02s_50720',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\BLOOD_INHOMOGENEITY',         '20150521_12h45m19s_50706',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\VB17A_artifact_moco_case',         'Pat1_PSIR',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17A_artifact_moco_case',         'Pat2_PSIR',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\20150624_case',         '20150624_13h02m25s_61108',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\20150624_case',         '20150624_13h02m43s_61109',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\20150624_case',         '20150624_13h03m11s_61110',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\20150624_case',         '20150624_13h03m39s_61111',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\20150624_case',         '20150624_13h04m06s_61112',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\VD13A_AERA_LGE_MOCO_BLACK_SPOT_CASE',         'meas_MID00059_FID94643_3minCV_gtPlus_PSIR_9sl_4ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
