function UTCases = set_up_UT_cases_3D;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {      
    '3D',         'meas_MID00156_FID05944_GRE_128iso_p2x2',         'VD',   'GT_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00173_FID08775_head_gre_ipat3x2',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00176_FID08778_head_gre_ipat3x3',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00351_FID27847_QQQ_Angio3D_Sag_pre',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00370_FID29656_head_gre_ipat2x2_96',         'VD',   'GTPrep_3DT_Cartesian_GFactor.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00496_FID36032_t1_fl2d_sag_spat2',         'VD',   'GTPrep_2DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00497_FID36033_t1_fl2d_sag_ipat2',         'VD',   'GTPrep_2DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00499_FID36035_t2_spc_sag_p2_iso_128_ipat2p2',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00500_FID36036_GRE_128iso_p2x2',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00501_FID36037_GRE_128iso_spat2x2',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00502_FID36038_GRE_128iso_elip_spat2x2',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00503_FID36039_GRE_256iso_elip_spat2x2',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00504_FID36040_GRE_256iso_elip_spat2x2_176slc',         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00828_FID39146_T1_3D_SAG___R2Y',         'VD',   'GTPrep_3DT_Cartesian_GFactor.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00302_FID60251_GT_tfl_R3_20reps',         'VB',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00024_FID77709_GT_tfl_R1_20Rep',         'VD',   'GTPrep_3DT_Cartesian_GFactor.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
