function UTCases = set_up_UT_cases_Binning;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'CMR_2DT_RTCine_KspaceBinning_MultiSeries.xml',                                  'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID00322_FID06960_RealTimeCineBinning',          'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'binning',                  '20160307_11h13m09s_4537',                             'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
          
    'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h39m35s_62241',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',              'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
   
    'binning\20150923_StudyLoid_12.0.123557963_CNMC2359-C0832',   '20150923_11h51m34s_62440',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    'binning\CNMC_20160715',   'meas_MID00062_FID23728_SAX_R3_RT_Binning_256_CLOUD_9sl',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                                  'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'binning\CNMC_20160715',   'meas_MID00062_FID23728_SAX_R3_RT_Binning_256_CLOUD_9sl',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                                  'binning_res2',            'binning_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    'binning\TenNV',   'meas_MID00163_FID12147_PK792_binning_256_144_LVOT',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                                  'binning_res2',            'binning_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'binning\TenNV',   'meas_MID00164_FID12148_PK792_binning_256_144_RV2CH',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                                  'binning_res2',            'binning_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'binning\TenNV',   'meas_MID00286_FID10557_PK792_binning_192_128_RV2CH',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                                  'binning_res2',            'binning_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'binning\TenNV',   'meas_MID00332_FID10603_PK792_binning_256_144_LVOT20s',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                                  'binning_res2',            'binning_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
