function UTCases = set_up_UT_cases_GtPrep_UT;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'gtprep_data\gtprep\7T',              'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648',        'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',         'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data\gtprep\CineBinning',     'meas_MID836_PK_rt_test_1slice_FID22517',                                 'VD',   'GTPrep_2DT_RTCine_Binning.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\CineBinning',     'meas_MID838_PK_rt_test_2slice_FID22519',                                 'VD',   'GTPrep_2DT_RTCine_Binning.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    % 'gtprep_data\gtprep\CineBinning',     '20150923_11h51m34s_62440',                                               'VD',   'GTPrep_2DT_RTCine_Binning.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data\gtprep\LGE',             'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',            'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\LGE',             'meas_MID120_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343803',                   'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',              'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\LGE',             'meas_MID00355_FID81568_3CH_gt_PSIR_FLASH_9sl_8ave_MOCO',                 'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\LGE',             'meas_MID00569_FID178560_FB_DB_PSIR_10sl_16_ave_MOCO',                    'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data\gtprep\Nonlinear',       '20140703_11h09m11s_12297',                                               'VD',   'GTPrep_2DT_RTCine_SLEP_PInterp.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
        
    'gtprep_data\gtprep\RetroGating',     'meas_MID00385_FID00375_RetroCine_NL_15msT_Res192_NHLBI_Cloud',           'VD',   'GTPrep_2DT_RetroGated_Cine.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\RetroGating',     'meas_MID00208_FID115039_SAX_fisp_retro_iPAT_256',                        'VD',   'GTPrep_2DT_RetroGated_Cine.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\RetroGating',     'meas_MID00031_FID107666_4CH_fisp_retro_iPAT_256',                        'VD',   'GTPrep_2DT_RetroGated_Cine.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data\gtprep\Perfusion',       'Perfusion_AIF_TwoEchoes_Interleaved_R2_41672_54147266_54147276_1037_20160602-122009',  'VD',   'GTPrep_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'gtprep_data\gtprep\Perfusion',       'Perfusion_AIF_TwoEchoes_Interleaved_R2_41672_54147266_54147276_1046_20160602-123712',  'VD',   'GTPrep_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'gtprep_data\gtprep\Perfusion',       'meas_MID00545_FID144266_SSFP_Perf__MBF_MBV_stress',  'VD',   'GTPrep_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'gtprep_data\gtprep\Perfusion',       'meas_MID00552_FID144273_SSFP_Perf__MBF_MBV_rest',  'VD',   'GTPrep_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    % 'gtprep_data\gtprep\RealTimeFlow',    'meas_MID00089_FID19207_real_time_flow_R5_30s',                           'VD',   'GTPrep_2DT_RTFlow_Binning.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data\gtprep\t2star',          'meas_MID00372_FID108007_SAX_gt_T2Star_MOCO_DB_8e',                       'VD',   'GTPrep_2DT_T2Star_Mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data\gtprep\B1Mapping',       'meas_MID00272_FID112569_B1MAP_BH_a90_rep30_PAT2',                        'VD',   'B1mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'   ; ...
    
    'gtprep_data\gtprep\T2W',             'meas_MID00123_FID43785_gt_CV_T2w_segmented',                             'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',              'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data\gtprep\T2W',             'meas_MID00371_FID108006_SAX_gt_T2w_9sl_8ave_MOCO',                       'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',     'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
