function UTCases = set_up_UT_cases_Perfusion;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'DualBolus\Flash_rest\20150429\rest',  'meas_MID00186_FID43636_BIG__075_PK_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2.xml',          'grappa_res',          'grappa_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\Flash_rest\20150429\rest',  'meas_MID00186_FID43636_BIG__075_PK_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\Flash_rest\20150429\rest',  'meas_MID00186_FID43636_BIG__075_PK_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'slep_flow_res',          'slep_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\Flash_rest\20150429\rest',  'meas_MID00186_FID43636_BIG__075_PK_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_flow_res_cloud',          'slep_flow_ref_cloud',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\Flash_rest\20150429\rest',  'meas_MID00186_FID43636_BIG__075_PK_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\Flash\20150506\stress',  'meas_MID00300_FID45790_BIG_STRESS__075_PK_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Offline.xml',          'grappa_flow_res_cx',          'grappa_flow_ref_cx',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...   
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...    
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'PerfusionUT',  'meas_MID00023_FID62532_R4_2SLC_96Res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Offline.xml',          'grappa_flow_res_cx',          'grappa_flow_ref_cx',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'PerfusionUT',  'meas_MID00023_FID62532_R4_2SLC_96Res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...    
    'PerfusionUT',  'meas_MID00023_FID62532_R4_2SLC_96Res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'PerfusionUT',  'meas_MID00026_FID62535_R4_2SLC_96Res_60REP_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Offline.xml',          'grappa_flow_res_cx',          'grappa_flow_ref_cx',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'PerfusionUT',  'meas_MID00026_FID62535_R4_2SLC_96Res_60REP_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...    
    'PerfusionUT',  'meas_MID00026_FID62535_R4_2SLC_96Res_60REP_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'slep_flow_res',          'slep_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_cloud_flow_res',          'slep_cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_cloud_flow_res2',          'slep_cloud_flow_ref2',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\CardiacPhases',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\CardiacPhases',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'slep_flow_res',          'slep_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\CardiacPhases',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_cloud_flow_res',          'slep_cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...

    'SUB_Perf',  'meas_MID00329_FID59479_PK_256by144_high_spatial_res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'FLASH_Perfusion_HighRes',  'meas_MID00116_FID36155_FULL_STRESS_FLASH_Perf_TPAT3_AIF_PF3_4',      'VD',   'GTPrep_2DT_Perfusion_AIF.xml',          'grappa_res',          'grappa_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'FLASH_Perfusion_HighRes',  'meas_MID00116_FID36155_FULL_STRESS_FLASH_Perf_TPAT3_AIF_PF3_4',      'VD',   'GTPrep_2DT_Perfusion_AIF_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'FLASH_Perfusion_HighRes',  'meas_MID00155_FID37490_1sl_128RO_12rep_FLASH_PERFUSION_GADGETRON',      'VD',   'GTPrep_2DT_Perfusion_AIF_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'MOCO_EVALUATION\SUB\SUB_SSFP',  '20150519_10h41m05s_81722',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\TwoConc',  'meas_MID00027_FID65792_40ms_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2.xml',          'grappa_res',          'grappa_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\TwoConc',  'meas_MID00027_FID65792_40ms_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\TwoConc',  'meas_MID00031_FID65796_40ms_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00021_FID68459_40ms_8_sl_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00022_FID68460_40ms_4_sl_1conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00255_FID68693_1_conc_40ms_Trigger4_1_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00252_FID68690_1_conc_40ms_1_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00251_FID68689_1_conc_40ms_3_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00250_FID68688_2_conc_40ms_6_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00033_FID68886_CV_epi_DS_AIF_810_snv_pk',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
};

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
