function [wx, wy, wz ] = Image2WorldMrFtk(header, x, y, z)
% image coordinates to world for MrFtk

wx = header.orientationPatient(1,1) * (x*header.spacingX) ...
    + header.orientationPatient(2,1) * (y*header.spacingY) ...
    + header.orientationPatient(3,1) * (z*header.spacingZ) ... 
    + header.positionPatient(1);

wy =  header.orientationPatient(1,2) * (x*header.spacingX) ...
    + header.orientationPatient(2,2) * (y*header.spacingY) ... 
    + header.orientationPatient(3,2) * (z*header.spacingZ) ...
    + header.positionPatient(2);

wz = header.orientationPatient(1,3) * (x*header.spacingX) ...
    + header.orientationPatient(2,3) * (y*header.spacingY) ... 
    + header.orientationPatient(3,3) * (z*header.spacingZ) ... 
    + header.positionPatient(3);
