function [x, y, z ] = World2ImageMrFtk(header, wx, wy, wz)
% image coordinates to world for MrFtk

x = ( (header.orientationPatient(1,1) * ( wx - header.positionPatient(1) )) ... 
        + (header.orientationPatient(1,2) * ( wy - header.positionPatient(2) )) ...
        + (header.orientationPatient(1,3) * ( wz - header.positionPatient(3) )) ) / header.spacingX;

y = ( (header.orientationPatient(2,1) * ( wx - header.positionPatient(1) )) ...
        + (header.orientationPatient(2,2) * ( wy - header.positionPatient(2) )) ...
        + (header.orientationPatient(2,3) * ( wz - header.positionPatient(3) )) ) / header.spacingY;

z = ( (header.orientationPatient(3,1) * ( wx - header.positionPatient(1) )) ...
        + (header.orientationPatient(3,2) * ( wy - header.positionPatient(2) )) ...
        + (header.orientationPatient(3,3) * ( wz - header.positionPatient(3) )) ) / header.spacingZ;

