    function UTCases = set_up_UT_cases_Cine;
% run the gt recon

% set_UT_Dir('D');

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'cine/ai_analysis', 'meas_MID3000014_FID58121_2ch_retrogated_cine_RR',              'VD',   'GTPrep_2DT_RetroCine_GLS_Seg_AI_istore.xml',           'res2',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/20210901_BARCELONA_RetroCineAI', 'meas_MID00056_FID93225_BH_retrogated_cine',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/QLDXRAY',                  'meas_MID00117_FID233415_4Ch_BH_retrogated_cine_K',              'NX20',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis_istore.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...
    
    'cine/gls_3slices',                  'meas_MID00336_FID457398_pk_cine_lax',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/gls_3slices',                  'Retro_Lin_Cine_2DT_LAX_GLS_66016_3873315_3873320_3000006_20210519-190543',              'VD',   'GTPrep_2DT_RetroCine_GLS_ECG_istore.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/gls_3slices',                  'Retro_Lin_Cine_2DT_LAX_GLS_66016_3873315_3873320_3000006_20210519-190543',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/gls_sax',                  'Retro_Lin_Cine_2DT_LAX_GLS_41837_45093191_45093200_1537_20210602-125915',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/multi_slice',                  'RT_Cine_LIN_66016_369793089_369793098_82_20190325-092425',              'VD',   'Generic_RTCine_UnetFil.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'Retro_Lin_Cine_2DT_42110_74419962_74419971_1536_20180815-113621',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',           'res_GLS',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'Retro_Lin_Cine_2DT_42110_74419962_74419971_1536_20180815-113621',              'VD',   'Generic_2DT_RetroGated_Cine.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'Retro_Lin_Cine_2DT_42110_74419962_74419971_1536_20180815-113621',              'VD',   'GTPrep_2DT_RetroCine_GLS_ECG_istore.xml',           'res_ecg',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/single_slice',                  'RT_Cine_LIN_66016_1346884862_1346884871_473_20201006-101515',              'VD',   'GTPrep_2DT_RTCine.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_66016_1346884862_1346884871_473_20201006-101515',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',           'res_n3',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_66016_1346884862_1346884871_473_20201006-101515',              'VD',   'Generic_RTCine_UnetFil.xml',           'res_unet',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_66016_1346884862_1346884871_473_20201006-101515',              'VD',   'GTPrep_2DT_RetroCine_GLS_ECG_istore.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_66016_1346884862_1346884871_473_20201006-101515',              'VD',   'Generic_2DT_RetroGated_Cine_ECG.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_66016_1346884862_1346884871_473_20201006-101515',              'VD',   'CMR_RTCine_LAX_AI.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/single_slice',                  'RT_Cine_LIN_41837_02134007_02134016_1005_20190313-160711',              'VD',   'GTPrep_2DT_RTCine.xml',           'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_41837_02134007_02134016_1005_20190313-160711',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',           'res_n3',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_41837_02134007_02134016_1005_20190313-160711',              'VD',   'Generic_RTCine_UnetFil.xml',           'res_unet',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'RT_Cine_LIN_41837_08802975_08802984_1343_20180815-114942',              'VD',   'GTPrep_2DT_RTCine.xml',             'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_41837_08802975_08802984_1343_20180815-114942',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',             'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/multi_LAX',                  'meas_MID00094_FID136007_RT_cine_2_slice_grp_2ch_4ch',              'VD',   'GTPrep_2DT_RTCine.xml',     'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/multi_LAX',                  'meas_MID00094_FID136007_RT_cine_2_slice_grp_2ch_4ch',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',     'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'RT_Cine_LIN_42363_08467446_08467451_599_20181022-130358',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'RT_Cine_LIN_42363_08467446_08467451_599_20181022-130358',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_N3.xml',             'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    'cine',                  'RT_Cine_LIN_42363_08467446_08467451_599_20181022-130358',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_NN.xml',             'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...            
    
    % phantom
    %'cine',                  'RT_Cine_LIN_42363_08467352_08467357_376_20181021-142515',              'VD',   'GTPrep_2DT_RTCine.xml',             'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    %'cine',                  'RT_Cine_LIN_42363_08467352_08467357_376_20181021-142515',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',             'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    
    'cine',                  'RT_Cine_LIN_42110_57527846_57527855_60_20180225-100045',              'VD',   'GTPrep_2DT_RTCine.xml',     'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_42110_57527846_57527855_60_20180225-100045',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',     'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
 
    'cine',                  'RT_Cine_LIN_42363_0457338_0457343_212_20180921-132238',              'VD',   'GTPrep_2DT_RTCine.xml',     'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_42363_0457338_0457343_212_20180921-132238',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',     'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'GTPrep_2DT_RTCine.xml',             'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',               'VD',   'Generic_Cartesian_Grappa_RealTimeCine_NN.xml',             'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...            
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',               'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',             'res_n3_gls',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...            
    
    %'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG.xml',             'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
   
    
    'cine',                  'RT_Cine_LIN_42363_08467446_08467451_599_20181022-130358',              'VD',   'Generic_RTCine_PInterp_ECG.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'RT_Cine_LIN_42363_08467352_08467357_376_20181021-142515',              'VD',   'Generic_RTCine_PInterp_ECG.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_42363_0457338_0457343_212_20180921-132238',              'VD',   'Generic_RTCine_PInterp_ECG.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_42363_0457338_0457343_212_20180921-132238',              'VD',   'Generic_RTCine_PInterp.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_41837_08802975_08802984_1343_20180815-114942',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_Python.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'GTPrep_2DT_RTCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'GTPrep_2DT_RTCine_Fil.xml',      'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'Generic_RTCine_PInterp_ECG.xml',      'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',      'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00079_FID02462_tpat3_RT_Cine_Bart_Res160_Lighthouse_FOV450_1200',              'VD',   'Generic_RTCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
     'cine',                  'meas_MID00079_FID02462_tpat3_RT_Cine_Bart_Res160_Lighthouse_FOV450_1200',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
   
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_Python.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_RTCine_ECG.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_RTCine_PInterp.xml',             'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_RTCine_PInterp_ECG.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_RTCine_PInterp_Fil.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
   
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_RTCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_RTCine_PInterp.xml',     'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_RTCine_PInterp_Fil.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_42363_2676010_2676015_1031_20180227-141738',              'VD',   'Generic_RTCine_PInterp.xml',     'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_42363_2676010_2676015_1031_20180227-141738',              'VD',   'Generic_RTCine_PInterp_Fil.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_41837_248889037_248889046_408_20180222-154214',              'VD',   'Generic_RTCine_PInterp.xml',     'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_41837_248889037_248889046_408_20180222-154214',              'VD',   'Generic_RTCine_PInterp_Fil.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
       
    'cine',                  'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'Generic_RTCine_PInterp.xml',     'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'Generic_RTCine_PInterp_Fil.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PInterp.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_Cloud.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20160113_13h44m33s_77171',              'VD',   'GTPrep_2DT_RTCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'GTPrep_2DT_RTCine_Fil.xml',             'grappa_fil_res',              'grappa_fil_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_ismrmrd_storage.xml',              'nl_res',              'nl_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'GTPrep_ismrmrd_storage.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00165_FID39820_R3_RT_Cine_Linear_Res160_35ms',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PInterp.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',              'nl_spirit_res',              'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                 'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',              'VB',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',     'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',              'VB',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',              'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',      'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',     'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',     'grappa_compression_res',  'grappa_compression_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',      'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00300_FID06938_RTCineNL_NHLBI',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',                    'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00300_FID06938_RTCineNL_NHLBI',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                        'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00300_FID06938_RTCineNL_NHLBI',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',        'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',            'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
      
    'cine',                  '20140703_11h09m11s_12297',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141007_08h03m17s_23619',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_08h03m17s_23619',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_08h03m17s_23619',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141007_10h39m51s_23674',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_10h39m51s_23674',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_10h39m51s_23674',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % R=5
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'Generic_RTCine_UnetFil.xml',           'unet_fil',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'binning',               'meas_MID00099_FID10377_SAXPK792_binning_192_128_PAT5',              'VD',   'Generic_RTCine_UnetFil.xml',           'unet_fil',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20141008_13h20m39s_23934',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141008_13h20m39s_23934',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141008_13h20m39s_23934',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20141013_15h07m14s_24419',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141013_15h07m14s_24419',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'cine',                  '20141013_15h07m14s_24419',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141017_10h09m21s_25173',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141017_10h09m21s_25173',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'cine',                  '20141017_10h09m21s_25173',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141020_16h11m10s_25740',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141020_16h11m10s_25740',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'cine',                  '20141020_16h11m10s_25740',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141023_08h43m35s_26080',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141023_08h43m35s_26080',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141023_08h43m35s_26080',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20141027_15h31m18s_26452',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141027_15h31m18s_26452',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141027_15h31m18s_26452',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141106_17h08m37s_28065',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141106_17h08m37s_28065',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141106_17h08m37s_28065',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141205_15h37m58s_31798',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141205_15h37m58s_31798',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141205_15h37m58s_31798',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141219_13h53m08s_33457',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141219_13h53m08s_33457',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141219_13h53m08s_33457',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % good show case
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20151119_15h29m30s_70292',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20151119_15h29m30s_70292',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20151119_15h29m30s_70292',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00138_FID106371_gtRealTimeCineNonLinear_9slc',              'VB',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res2',              'slep_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00138_FID106371_gtRealTimeCineNonLinear_9slc',              'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00042_FID96308_cine_SAX_realtime_gt_TPAT4',            'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00042_FID96308_cine_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00042_FID96308_cine_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_Contouring.xml',           'contouring_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
       
    'cine',                  'meas_MID00039_FID110008_2ch_realtime_gt_TPAT4_RT',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00039_FID110008_2ch_realtime_gt_TPAT4_RT',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
      
    'cine',                  'meas_MID00041_FID110010_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00041_FID110010_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00047_FID110016_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00047_FID110016_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00047_FID110016_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00035_FID110004_3ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00035_FID110004_3ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00037_FID110006_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00037_FID110006_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00061_FID110030_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00061_FID110030_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00039_FID110008_2ch_realtime_gt_TPAT4_RT',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00053_FID110022_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID378_sax_realtime_724Free-breathing_FID8217',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'cine/RTCine',           'meas_MID00394_FID114123_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00394_FID114123_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_Compression.xml',         'grappa_compression_res',              'grappa_compression_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'binning',           'meas_MID00391_FID21051_4CH_CV_binning',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/RTCine',           'meas_MID00380_FID114109_4CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00382_FID114111_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00384_FID114113_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/RTCine',           'meas_MID00406_FID114135_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00288_FID115664_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00275_FID115651_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00277_FID115653_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00273_FID115649_4CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/ReconChallenge',           'meas_MID378_sax_realtime_724Free-breathing_FID8217',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',           'meas_MID00165_FID39820_R3_RT_Cine_Linear_Res160_35ms',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',           'Cmr_Cine_NL_Cloud_53531_77803904_77803911_170_20170731-105855',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',           'Cmr_Cine_NL_Cloud_53531_85471775_85471782_424_20170804-171232',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00165_FID39820_R3_RT_Cine_Linear_Res160_35ms',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_Contouring.xml',           'contouring_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/single_slice',                  'RT_Cine_LIN_41837_02134007_02134016_1005_20190313-160711',              'VD',   'Generic_RTCine_PInterp_Fil_ECG_CMR_View_AI_dstore.xml',           'contouring_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_42363_160617594_160617599_252_20190607-153431',              'VD',   'Generic_RTCine_PInterp_Fil_ECG_CMR_View_AI_dstore.xml',           'contouring_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/single_slice',                  'RT_Cine_LIN_42363_160617594_160617599_252_20190607-153431',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_dstore.xml',           'res_n3',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',           'Cmr_Cine_NL_Cloud_53531_77803904_77803911_170_20170731-105855',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'D:\data\GadgetronSummerSchool\MultiSlice_Cine',           'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/lund',           'RT_Cine_LIN_182758_0000020050615543207100000003_0000020050615543207100000003_28_20200506-165202',              'VD',   'Generic_RTCine_PInterp_Fil_ECG.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/ch2',           'RT_Cine_LIN_41837_3258310_3258319_866_20200915-103856',              'VD',   'Generic_RTCine_PInterp_Fil_ECG_LAX_AI_istore.xml',         'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/ch2',           'RT_Cine_LIN_41837_3258310_3258319_866_20200915-103856',              'VD',   'Generic_RTCine_PInterp_Fil_ECG_LAX_AI_istore.xml',         'res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'cine/gls_3slices',           'meas_MID00336_FID457398_pk_cine_lax',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/lund',           'Retro_Lin_Cine_2DT_LAX_GLS_42034_57029509_57029517_365_20201008-142342',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',         'res_ai',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/lund',           'Retro_Lin_Cine_2DT_LAX_GLS_42034_57029509_57029517_385_20201008-144405',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',         'res_ai',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/lund',           'Retro_Lin_Cine_2DT_LAX_GLS_42034_57029509_57029517_365_20201008-142342',              'VD',   'GTPrep_2DT_RetroCine.xml',         'res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/lund',           'Retro_Lin_Cine_2DT_LAX_GLS_42034_57029509_57029517_365_20201008-142342',              'VD',   'GTPrep_2DT_RetroCine_GLS_AI_analysis.xml',         'res_ai2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    %'cine/lund',           'meas_MID01976_FID24843_BH_retrogated_cine',              'VD',   'GTPrep_2DT_RetroCine_GLS_AI_analysis.xml',         'res_ai2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/lund',           'meas_MID01976_FID24843_BH_retrogated_cine',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis_istore.xml',         'res_ai2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine/gls_debug',      'Retro_Lin_Cine_2DT_LAX_GLS_42363_47109290_47109295_380_20201008-150956',              'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',         'res_ai',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'RT_Cine_LIN_42110_67178329_67178338_699_20180228-135655',              'VD',   'Generic_RTCine_PInterp_Fil.xml',     'grappa_res3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_42110_67178329_67178338_699_20180228-135655',              'VD',   'Generic_RTCine_PInterp_Fil_ECG_CMR_View_AI_dstore.xml',     'grappa_res_AI',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_42110_67178329_67178338_699_20180228-135655',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_dstore.xml',     'grappa_res_n3',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'RT_Cine_LIN_42110_67178329_67178338_699_20180228-135655',              'VD',   'Generic_RTCine_LacandiFil.xml',     'grappa_res_lacandi',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'RT_Cine_LIN_141303_40611749_40611756_489_20180723-143603',              'VD',   'Generic_RTCine_LacandiFil.xml',     'grappa_res_lacandi',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    '/mnt/Lab-Kellman/Share/cases/20210121_pig',                  '20210121_145302_meas_MID00050_FID20583_4CH_RTCine_R3_160res',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',     'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
