function UTCases = set_up_UT_cases_CVSparse;
% run the gt recon

set_UT_Dir('D')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'CV_Sparse',             'meas_MID01095_FID40115_PK_CVsparse_rt_net12_0',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...  
    'CV_Sparse',             'meas_MID01402_FID40422_PK_CVsparse_rt_net12_0',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             '20130910_11h24m35s_28070',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             'meas_MID00306_FID348232_Cine_SA_4CH_2CH_SPARSE',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             'meas_MID00381_FID34951_CVsparse_10sl_rt_30msTempoalRes',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             '20130123_14h51m33s_759',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
    'CV_Sparse',             '20130903_16h56m54s_26500',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
    'CV_Sparse',             'meas_MID01300_FID40320_PK_CVsparse_rt_net12_0',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
    'CV_Sparse',             'meas_MID00387_FID21047_4CH_CVsparse_rt_net12_0',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'slep_res',            'slep_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   

    'CV_Sparse',             'meas_MID01095_FID40115_PK_CVsparse_rt_net12_0',   'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...    
    'CV_Sparse',             'meas_MID01402_FID40422_PK_CVsparse_rt_net12_0',   'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             '20130910_11h24m35s_28070',                        'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             'meas_MID00306_FID348232_Cine_SA_4CH_2CH_SPARSE',  'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             'meas_MID00381_FID34951_CVsparse_10sl_rt_30msTempoalRes',  'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',    'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             '20130123_14h51m33s_759',                          'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
    'CV_Sparse',             '20130903_16h56m54s_26500',                        'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
    'CV_Sparse',             'meas_MID01300_FID40320_PK_CVsparse_rt_net12_0',   'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...      
    'CV_Sparse',             'meas_MID00387_FID21047_4CH_CVsparse_rt_net12_0',   'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res',            'n_spirit_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...      
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
