function UTCases = set_up_UT_cases_RetroCine;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'RetroCine',                  'Retro_Lin_Cine_2DT_Contouring_41837_006458083_006458092_3000010_20171212-222256',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    
    'RetroCine',                  'meas_MID00454_FID07520_R3_Retro_NLin_Cine_8ms_4Ch',            'VD',  'Generic_2DT_RetroGated_Cine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroCine',                  'meas_MID00454_FID07520_R3_Retro_NLin_Cine_8ms_4Ch',            'VD',  'Generic_2DT_RetroGated_Cine_ECG.xml',         'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'RetroCine',                  'Retro_Lin_Cine_2DT_41837_62410798_62410807_92_20180828-083450',            'VD',  'Generic_2DT_RetroGated_Cine_ECG.xml',         'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroCine',                  'meas_MID3000002_FID156603_sa_cine_RR_RR',            'VD',  'Generic_2DT_RetroGated_Cine_ECG.xml',         'grappa_res2',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'hxue\retrocine',                  'meas_MID00142_FID04407_cine_tf2d13_retro_iPAT',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    'hxue\retrocine',                  'meas_MID00143_FID04408_cine_tf2d13_retro_iPAT',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    'hxue\retrocine',                  'meas_MID00158_FID04423_cine_tf2d13_retro_iPAT',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    'hxue\retrocine',                  'meas_MID00165_FID04430_cine_tf2d15_retro',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    'hxue\retrocine',                  'meas_MID00166_FID04431_cine_tf2d15_retro',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    'hxue\retrocine',                  'meas_MID00172_FID04437_cine_tf2d15_retro',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    'hxue\retrocine',                  'meas_MID00173_FID04438_cine_tf2d15_retro',            'VD',  'GTPrep_2DT_RetroCine_AI.xml',    'gc_res3',              'g_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
