function UTCases = set_up_UT_cases_T2Mapping;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'T2',                'T2map_3pt_TRUFI_41837_54891096_54891101_347_20171207-213304',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'T2',                '20130411_15h48m21s_9751',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'T2map_afib',                'meas_MID00056_FID09492_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_istore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00057_FID09493_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00058_FID09494_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00059_FID09495_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00060_FID09496_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00061_FID09497_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00062_FID09498_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00063_FID09499_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    'T2map_afib',                'meas_MID00064_FID09500_T2Map_TrueFISP',                                'VD',               'GTPrep_2DT_MOCO_AVE_T2_Mapping_dstore.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];

end
