    function UTCases = set_up_UT_cases_LowField;
% run the gt recon

% set_UT_Dir('D');

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'grad_waveform',              'meas_MID00198_FID30458_MiniFLASH_GradSend',              'VD',   'Generic_Cartesian_Grappa.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'LowField',              'meas_MID00882_FID02072_BinningCine_R3_192res_cloud',              'VD',   'CMR_2DT_Binning.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField',              'meas_MID00880_FID02070_BinningCine_R4_256res',              'VD',   'CMR_2DT_Binning_Fil.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField',                  'meas_MID00861_FID02051_RetroCine_R3_192res',              'VD',   'GTPrep_2DT_RetroCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'meas_MID00861_FID02051_RetroCine_R3_192res',              'VD',   'GTPrep_2DT_RetroCine_Fil.xml',             'grappa_fil_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'meas_MID00866_FID02056_RetroCine_NLin_R3_192res',              'VD',   'GTPrep_2DT_RetroCine_NL.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField',                  'meas_MID00864_FID02054_RetroCine_R3_256res_BW500',              'VD',   'GTPrep_2DT_RetroCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'meas_MID00864_FID02054_RetroCine_R3_256res_BW500',              'VD',   'GTPrep_2DT_RetroCine_Fil.xml',             'grappa_fil_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'meas_MID00864_FID02054_RetroCine_R3_256res_BW500',              'VD',   'GTPrep_2DT_RetroCine_NL.xml',             'nl_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % R=3
    'LowField',                  'Retro_NLin_Cine_2DT_41624_575234_575239_868_20171221-130530',              'VD',   'GTPrep_2DT_RetroCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'Retro_NLin_Cine_2DT_41624_575234_575239_868_20171221-130530',              'VD',   'GTPrep_2DT_RetroCine_NL.xml',             'nl_res',              'nl_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % R=3, 4CH
    'LowField',                  'Retro_NLin_Cine_2DT_41624_575234_575239_869_20171221-130947',              'VD',   'GTPrep_2DT_RetroCine_Fil.xml',             'fil_res',              'fil_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'Retro_NLin_Cine_2DT_41624_575234_575239_869_20171221-130947',              'VD',   'GTPrep_2DT_RetroCine_NL.xml',             'nl_res',              'nl_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % R2
    'LowField',                  'Retro_Lin_Cine_2DT_41624_575234_575239_858_20171221-124153',              'VD',   'GTPrep_2DT_RetroCine.xml',             'nl_res',              'nl_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField',                  'meas_MID00876_FID02066_RTCine_R3_192res',              'VD',   'GTPrep_2DT_RTCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'meas_MID00876_FID02066_RTCine_R3_192res',              'VD',   'GTPrep_2DT_RTCine_Fil.xml',             'grappa_fil_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField',                  'meas_MID00874_FID02064_RTCine_R4_192res',              'VD',   'GTPrep_2DT_RTCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField',                  'meas_MID00874_FID02064_RTCine_R4_192res',              'VD',   'GTPrep_2DT_RTCine_SLEP_PInterp.xml',             'nl_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % snr
    'LowField\20171222',                  'meas_MID00134_FID02324_SNR_GFactor_R1_Res160_BW500',              'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField\20171222',                  'meas_MID00132_FID02322_SNR_GFactor_R1',              'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField\20171222',                  'meas_MID00131_FID02321_SNR_GFactor_R2',              'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField\20171222',                  'meas_MID00133_FID02323_SNR_GFactor_R3',              'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % binning flow
    'LowField',                  'meas_MID00312_FID02787_BinningFlow_Res192_R2_40s',              'VD',   'GTPrep_2DT_BinningFlow_Fil.xml',             'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField\20180105',                  'meas_MID00429_FID02904_Sax_BinningCine_R3_192res',              'VD',   'CMR_2DT_Binning_Fil.xml',             'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField\20180105',                  'meas_MID00430_FID02905_Sax_BinningCine_R3_256res',              'VD',   'CMR_2DT_Binning_Fil.xml',             'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LowField\20180112',                  'meas_MID01013_FID04300_BinningFlow_Res192_R2_50s',              'VD',   'GTPrep_2DT_BinningFlow.xml',             'binning_res',              'binning_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    
    % retro flow
    'LowField\20180112',                  'meas_MID01012_FID04299_RetroFlow_Res192_R2',              'VD',   'GTPrep_2DT_RetroFlow.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    'LowField\20180112',                  'meas_MID01012_FID04299_RetroFlow_Res192_R2',              'VD',   'GTPrep_2DT_RetroFlow_Fil.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    'LowField\20180112',                  'meas_MID01012_FID04299_RetroFlow_Res192_R2',              'VD',   'GTPrep_2DT_RetroFlow_NL_Fil.xml',             'res_nl_fil',              'ref_nl_fil',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    
    'LowField\20180122',                  'meas_MID00316_FID05539_RTFlow_Res192_R3',              'VD',   'GTPrep_2DT_RTFlow.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    'LowField\20180122',                  'meas_MID00316_FID05539_RTFlow_Res192_R3',              'VD',   'GTPrep_2DT_RTFlow_Fil.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    
    'LowField\20180125',                  'meas_MID00145_FID06309_BinningFlow_Res192_R2_40s',              'VD',   'GTPrep_2DT_BinningFlow.xml',             'res_fil3',              'ref_fil',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    'LowField\20180125',                  'meas_MID00145_FID06309_BinningFlow_Res192_R2_40s',              'VD',   'GTPrep_2DT_BinningFlow_Fil.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    
    'LungTSE_rawData',                  '20181218_124140_meas_MID00542_FID03365_t2_tse_tra_p2_320_trig',              'VD',   'GTPrep_2DT_Cartesian_Lung_TSE.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui\abdomenH5\imagedata',               '20181206_212807_meas_MID00187_FID00682_t1_vibe_dixon_cor_p4_bh_wip963',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\abdomenH5\imagedata',                  '20181207_154011_meas_MID00065_FID00948_t2_tse_sfs_tra_trig_SkewedSpair',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\abdomenH5\imagedata',               '20190225_224306_meas_MID00094_FID00919_t1_vibe_dixon_tra_p4_bh',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui\brainH5\imagedata',               '20181207_170024_meas_MID00086_FID00969_t1_tse_dark-fluid_sag',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\brainH5\imagedata',               '20181207_170457_meas_MID00088_FID00971_t2_tse_dark-fluid_tra',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\brainH5\imagedata',               '20190225_210928_meas_MID00025_FID00850_t1_mprage_sag_iso_manual_denoising',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\brainH5\imagedata',               '20190225_211519_meas_MID00026_FID00851_t2_dark_fluid_sag_manual_denoising',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui\kneeH5\imagedata',               '20190104_200259_meas_MID00033_FID06439_pd_tse_sag_384',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\kneeH5\imagedata',               '20190104_200942_meas_MID00034_FID06440_t2_tse_tra',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui\spineH5\imagedata',               '20181205_214951_meas_MID00155_FID00270_t2_tse_stir_sag_384_t-spine',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui\spineH5\imagedata',               '20181207_181828_meas_MID00150_FID01036_t2_tse_sag_p2',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui\cardiacH5\imagedata',               '20190124_140027_meas_MID00846_FID10145_SAX_BinningCine_R3_192res_cloud',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_dstore.xml',             'res_fil',              'ref_fil',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
