function UTCases = set_up_UT_cases_CineCloud;
% run the gt recon

set_UT_Dir('D')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = { 
    
            'hxue',                  'meas_MID00181_FID04446_R3_RT_Cine_NL_Res192_Lighthouse',            'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'cloud_spirit_res', 'cloud_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'hxue',                  'meas_MID00181_FID04446_R3_RT_Cine_NL_Res192_Lighthouse',            'VD',   'Generic_Cartesian_Grappa_RealTimeCine_Cloud.xml',  'cloud_grappa_res', 'cloud_grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
            'cine',                  'meas_MID3000002_FID95847_RT_nonlinear_physio_Cloud_RR',            'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res', 'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID3000002_FID95847_RT_nonlinear_physio_Cloud_RR',            'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'cloud_spirit_res', 'cloud_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID3000002_FID95847_RT_nonlinear_physio_Cloud_RR',            'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling.xml',  'grappa_res', 'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

            'cine',                  'meas_MID01210_FID94548_RT_nonlinear_physio_Cloud',                 'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res', 'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID01096_FID94434_RT_nonlinear_physio_Cloud',                 'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_res', 'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cloud',                 'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',          'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                     
            'cloud',                 'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  'meas_MID00084_FID107719_gtRealTimeCineNonLinear',                  'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            % 'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',          'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  'meas_MID00042_FID96308_cine_SAX_realtime_gt_TPAT4',                'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',                  'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID00138_FID106371_gtRealTimeCineNonLinear_9slc',             'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            % phantom, 'cine',                  'measper_MID02847_FID20227_CV_gtPlus_RealTimeCine_NonLinear',          'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            % 'cine',                  'meas_MID00035_FID110004_3ch_realtime_gt_TPAT4',                    'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
         
            % Pig FFR data, 20160222_A04259_2ml, good quality 
            'cine',                  'meas_MID00157_FID109194_RTCine_NL_Amazon_Cloud_4SLC_Groups',       'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...           
            
            'cine',                  'meas_MID00537_FID00832_sax_Cine_FLASH_TPAT6_CV_724',               'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...           
            'cine',                  'meas_MID130_STRESS_CINE_R5_FID68512',                              'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...           
            'cine',                  'meas_MID00832_FID12089_RealTimeCine_NonLinear',                    'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...           
            
            % 'cine',                  '20140703_11h05m56s_12282',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20140703_11h09m11s_12297',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            % 'cine',                  '20140711_12h08m04s_13332',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            % 'cine',                  '20140728_11h03m38s_15309',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141007_08h03m17s_23619',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141007_10h39m51s_23674',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141007_12h31m16s_23730',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  '20141008_13h20m39s_23934',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141008_13h20m39s_23934',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'gtprep', 'gtprep',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  '20141013_15h07m14s_24419',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141017_10h09m21s_25173',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141020_16h11m10s_25740',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141023_08h43m35s_26080',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141027_15h31m18s_26452',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141106_13h25m17s_27988',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141106_17h08m37s_28065',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141205_15h37m58s_31798',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141219_13h53m08s_33457',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20151119_15h29m30s_70292',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20151230_16h17m26s_75567',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p0015', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                       

            'cine',                  '20151230_11h55m49s_75437',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20151230_12h29m15s_75471',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20151230_16h04m51s_75561',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20151230_17h21m16s_75607',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20151230_17h33m56s_75613',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20151230_17h40m01s_75618',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20160113_13h45m22s_77172',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20160113_13h55m40s_77177',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  '20160113_14h02m52s_77182',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'cine',                  'meas_MID00115_FID26611_R3_RT_Cine_NL_Res160_Lighthouse',           'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine',                  'meas_MID00117_FID26613_R3_RT_Cine_NL_Res192_Lighthouse',           'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res_db1_noise_floor_0p0015',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
            'binning\CNMC_20160817', 'meas_MID00165_FID28336_SAX_R3_RT_Cine_NL_Res192_Lighthouse',       'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',           'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'binning\CNMC_20160817', 'meas_MID00111_FID28282_SAX_R3_RT_Cine_NL_Res192_Lighthouse',       'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',           'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'binning\CNMC_20160822', 'meas_MID00041_FID28765_R2_RT_Cine_Binning_Res192_LocalCloud',       'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',          'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'binning\CNMC_20161018_NV', 'meas_MID00269_FID36195_R3_RT_Cine_Binning_Res192_Lighthouse',    'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',                             'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'binning\CNMC_20161018_NV', 'meas_MID00273_FID36199_R3_RT_Cine_NL_Res192_Lighthouse',        'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',           'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'binning\CNMC_20161018_NV', 'meas_MID00270_FID36196_R3_RT_Cine_Linear_Res192_43ms',         'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',           'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'binning\CNMC_20161018_NV', 'meas_MID00272_FID36198_R3_RT_Cine_Linear_Res160_35ms',         'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',           'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine\CNMC_NV_20161108',    'meas_MID00168_FID39823_R3_RT_Cine_res160_46ms_NL_BART_Proto1', 'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',         'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine\CNMC_NV_20161108',    'meas_MID00169_FID39824_R3_RT_Cine_NL_Res192_Lighthouse',       'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',         'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'cine\CNMC_NV_20161108',    'meas_MID00168_FID39823_R3_RT_Cine_res160_46ms_NL_BART_Proto1', 'VD',   'BART_Recon.xml',         'bart_res',              'bart_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine\CNMC_NV_20161108',    'meas_MID00164_FID39819_R4_RT_Cine_res192_42ms_NL_BART_Proto1', 'VD',   'BART_Recon.xml',         'bart_res',              'bart_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'cine\CNMC_NV_20161108',    'meas_MID00163_FID39818_R4_RT_Cine_res192_42ms_NL_gt_cloud',    'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine\CNMC_NV_20161108',    'meas_MID00163_FID39818_R4_RT_Cine_res192_42ms_NL_gt_cloud',    'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',           'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'cine\CNMC_NV_20161108',    'meas_MID00162_FID39817_R3_RT_Cine_Linear_Res192_50ms',    'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'cine\CNMC_NV_20161108',    'meas_MID00166_FID39821_R4_RT_Cine_res160_34ms_NL_gt_cloud',    'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            % 'binning\CNMC_20160831', 'meas_MID00255_FID30588_SAX_R3_RT_Cine_NL_Res192_Lighthouse',       'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res',              'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'binning\CNMC_20160831', 'meas_MID00255_FID30588_SAX_R3_RT_Cine_NL_Res192_Lighthouse',       'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling.xml',  'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'CV_Sparse',             'meas_MID01095_FID40115_PK_CVsparse_rt_net12_0',                    'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...    
            'CV_Sparse',             'meas_MID01402_FID40422_PK_CVsparse_rt_net12_0',                    'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
            'CV_Sparse',             '20130910_11h24m35s_28070',                                         'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
            'CV_Sparse',             'meas_MID00306_FID348232_Cine_SA_4CH_2CH_SPARSE',                   'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
            'CV_Sparse',             'meas_MID00381_FID34951_CVsparse_10sl_rt_30msTempoalRes',           'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
            'CV_Sparse',             '20130123_14h51m33s_759',                                           'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
            'CV_Sparse',             '20130903_16h56m54s_26500',                                         'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...   
            'CV_Sparse',             'meas_MID01300_FID40320_PK_CVsparse_rt_net12_0',                    'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...      
            'CV_Sparse',             'meas_MID00387_FID21047_4CH_CVsparse_rt_net12_0',                   'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...      
            
            'CV_Sparse',             'meas_MID00927_FID168219_2D_BEATsparse_rt_adaptive_acc10_5',        'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine.xml',  'nl_spirit_cloud_res_db1_noise_floor_0p001',            'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...    

    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
