function UTCases = set_up_UT_cases_T1Mapping;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'sasha\SASHA_PHANTOM', 'meas_MID00613_FID40909_pre_SASHA_10pt_TS600_256', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    'sasha\SASHA_PHANTOM', 'meas_MID00614_FID40910_pre_SASHA_10pt_variable_256', 'VD', 'CMR_2DT_T1Mapping_SASHA.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    
    'sasha', 'meas_MID01026_FID67745_pre_SASHA_2_1_0_8_1041C_V30_mrtime', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    
    'SASHA_HC', 'meas_MID00259_FID105959_SASHA_HC_1041C_7reps_of_7', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    'SASHA_HC', 'meas_MID00259_FID105959_SASHA_HC_1041C_7reps_of_7', 'VD', 'SASHA-HC_grappa.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    'SASHA_HC', 'meas_MID00259_FID105959_SASHA_HC_1041C_7reps_of_7', 'VD', 'SASHA-HC_grappa_moco.xml', 'grappa_moco_res', 'grappa_moco_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    
    'SASHA_HC', 'meas_MID00416_FID106116_SASHA_HC_1041C_7reps_of_7', 'VD', 'SASHA-HC.xml', 'spirit_res', 'spirit_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    'SASHA_HC', 'meas_MID00416_FID106116_SASHA_HC_1041C_7reps_of_7', 'VD', 'SASHA-HC_grappa.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    'SASHA_HC', 'meas_MID00416_FID106116_SASHA_HC_1041C_7reps_of_7', 'VD', 'SASHA-HC_grappa_moco.xml', 'grappa_moco_res', 'grappa_moco_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    
    'SASHA_HC', 'T1SR_Mapping_SASHA_HC_42363_38983621_38983626_155_20170623-093039', 'VD', 'SASHA-HC_grappa_moco.xml', 'grappa_moco_res', 'grappa_moco_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   

    'sasha', 'meas_MID00172_FID71628_SASHA_HC_1041C_BH_550ms', 'VD', 'SASHA-HC_grappa_moco.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    'sasha', 'meas_MID00172_FID71628_SASHA_HC_1041C_BH_550ms', 'VD', 'SASHA-HC_grappa.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    
    'sasha', 'zts_data_enc_pf_fix', 'VD', 'SASHA-HC_grappa.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    'sasha', 'zts_data_enc_pf_fix', 'VD', 'SASHA-HC_grappa_moco.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    
    'sasha', 'meas_MID00081_FID01646_SASHA', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    'sasha', 'meas_MID00082_FID01647_SASHA', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    
    'sasha\20170731', 'meas_MID00062_FID05131_BH_SASHA_Pre', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO_BH.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    'sasha\20170731', 'meas_MID00063_FID05132_FB_SASHA_Pre', 'VD', 'CMR_2DT_T1Mapping_SASHA_MOCO.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...   
    'sasha\20170731', 'meas_MID00064_FID05133_FB_SASHA_HC_Pre', 'VD', 'SASHA-HC_grappa_moco.xml', 'grappa_res', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_SASHA_HC.xsl'   ; ...   
    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];

end
