function UTCases = set_up_UT_cases_3D;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {      
    '/data/raw_data/neuro',         'meas_MID00471_FID28959_t1_mprage_tra_p2_iso',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                               'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '/data/raw_data/neuro',         'meas_MID00472_FID28960_t1_mprage_tra_p4iso',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                               'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   

    '/data/raw_data/neuro',         'VIDA_176578_2023-08-05-093539_FID008639_TSp_Sag_T1_2_2X_Anonymous',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                               'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '/data/raw_data/neuro',         'VIDA_176578_2023-08-05-093539_FID008639_TSp_Sag_T1_2_Anonymous',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                               'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   

    '3D',         'meas_MID00370_FID29656_head_gre_ipat2x2_96',                         'VD',   'GTPrep_3DT_Cartesian_GFactor.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00370_FID29656_head_gre_ipat2x2_96',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                               'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   

    '3D',         'meas_MID00156_FID05944_GRE_128iso_p2x2',                             'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    % good n3 show case
    '3D',         'meas_MID00173_FID08775_head_gre_ipat3x2',                            'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00173_FID08775_head_gre_ipat3x2',                            'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                        'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
        
    'neuro',      'meas_MID00069_FID19832_t2_qtse_tra_PAT3',                            'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                        'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',      'meas_MID00083_FID14721_t1_mprage_1mm_p4_pos50_ACPC_check',           'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                        'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',      'meas_MID00094_FID14732_t2_spc_sag_1mm_p2X2',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                        'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',      'meas_MID00095_FID14733_t2_spc_sag_1mm_p4X2',                         'VD',   'GTPrep_3DT_Cartesian_AI_FIL.xml',                        'grappa_res_n3',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    '3D',         'meas_MID00176_FID08778_head_gre_ipat3x3',                            'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00351_FID27847_QQQ_Angio3D_Sag_pre',                         'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    '3D',         'meas_MID00499_FID36035_t2_spc_sag_p2_iso_128_ipat2p2',               'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00500_FID36036_GRE_128iso_p2x2',                             'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00501_FID36037_GRE_128iso_spat2x2',                          'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00502_FID36038_GRE_128iso_elip_spat2x2',                     'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00503_FID36039_GRE_256iso_elip_spat2x2',                     'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',         'meas_MID00504_FID36040_GRE_256iso_elip_spat2x2_176slc',              'VD',   'GTPrep_3DT_Cartesian.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00828_FID39146_T1_3D_SAG___R2Y',                             'VD',   'GTPrep_3DT_Cartesian_GFactor.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    '3D',         'meas_MID00146_FID110904_QQQ_Angio3D_Sag_post',                       'VD',   'GTPrep_3DT_Cartesian_GFactor.xml',                               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00146_FID110904_QQQ_Angio3D_Sag_post',                       'VD',   'Generic_Cartesian_Grappa.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    'SNR_Unit_Recon\3D',         'meas_MID00113_FID115875_GT_tfl_R2_Res96_Rep20',       'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00173_FID08775_head_gre_ipat3x2',                            'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00176_FID08778_head_gre_ipat3x3',                            'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00351_FID27847_QQQ_Angio3D_Sag_pre',                         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00370_FID29656_head_gre_ipat2x2_96',                         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00828_FID39146_T1_3D_SAG___R2Y',                             'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    '3D',         'meas_MID00784_FID14130_GT_tfl_R3_Res320',                            'VD',   'Generic_Cartesian_Grappa.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00504_FID36040_GRE_256iso_elip_spat2x2_176slc',              'VD',   'Generic_Cartesian_Grappa.xml',                               'grappa_res2',         'grappa_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    '3D',         'meas_MID00156_FID05944_GRE_128iso_p2x2',                             'VD',   'Generic_Cartesian_Spirit.xml',                    'spirit_res',         'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00156_FID05944_GRE_128iso_p2x2',                             'VD',   'GTPrep_3DT_Cartesian_L1SPIRIT_SLEP.xml',          'spirit_res',         'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    '3D',         'meas_MID00370_FID29656_head_gre_ipat2x2_96',                         'VD',   'Generic_Cartesian_Spirit.xml',                    'spirit_res',         'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00501_FID36037_GRE_128iso_spat2x2',                          'VD',   'Generic_Cartesian_Spirit.xml',                    'spirit_res',         'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    '3D',         'meas_MID00102_FID163601_cine3D_prospective',                          'VD',   'GTPrep_3DT_Cine.xml',                    'spirit_res',         'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00102_FID163601_cine3D_prospective',                          'VD',   'GTPrep_3DT_Cartesian.xml',               'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00103_FID163602_cine3D_retro',                                'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    % cine 3D
    '3D\Cine3D',         'meas_MID00440_FID25103_cine3D_retro_nopats',                   'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D',         'meas_MID00440_FID25103_cine3D_retro_nopats',                   'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    
    '3D\Cine3D',         'meas_MID00447_FID25110_cine3D_NoRetro_nopats',                 'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D',         'meas_MID00448_FID25111_cine3D_NoRetro_nopats_e2_pf',           'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    
    
    '3D\Cine3D',         'meas_MID00441_FID25104_cine3D_retro_nopats_e1_pf',             'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D',         'meas_MID00441_FID25104_cine3D_retro_nopats_e1_pf',             'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    
    '3D\Cine3D',         'meas_MID00442_FID25105_cine3D_retro_nopats_e2_pf',             'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D',         'meas_MID00443_FID25106_cine3D_retro_nopats_e1_pf_e2_pf',       'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D',         'meas_MID00444_FID25107_cine3D_retro_spat_e1_2',                'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D',         'meas_MID00444_FID25107_cine3D_retro_spat_e2_2',                'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    
    '3D\Cine3D\2CV',         'meas_MID00658_FID25321_cine_3D_nopat',                         'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D\2CV',         'meas_MID00659_FID25322_cine_3D_nopat_e1_pf',                   'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D\2CV',         'meas_MID00660_FID25323_cine_3D_nopat_e2_pf',                   'VD',   'GTPrep_3DT_RetroGated_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    
    '3D\Cine3D\2CV',         'meas_MID00661_FID25324_cine_3D_no_retro_nopat',                'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D\2CV',         'meas_MID00662_FID25325_cine_3D_no_retro_nopat_e1_pf',          'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    '3D\Cine3D\2CV',         'meas_MID00663_FID25326_cine_3D_no_retro_nopat_e2_pf',          'VD',   'GTPrep_3DT_Cine.xml',         'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens_Cine3D.xsl'   ; ...   
    
    'external\Oxford',       'meas_MID243_fl3d_FID19268',                             'VB',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00501_FID36037_GRE_128iso_spat2x2',                          'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D\hxue',         'meas_MID00305_FID10518_mp2rage_wip900B_3T_p3',                          'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    '3D',         'meas_MID00151_FID15826_t1_mprage_tra_p2_iso_1_0',                          'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    '/export/Lab-Xue/data/mri_raw_data/neuro',         'meas_MID00073_FID33725_t1_mprage_sag_p3_p7mm',                          'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'generic_res',         'generic_ref',   'GadgetronParameterMap_Siemens.xsl'   ; ...

    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
