function UTCases = set_up_UT_cases_Test;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {  

    'head',        'meas_MID00246_FID04261_ax_R3_se_RR_v3_s32_bw250',        'VD',   'Generic_Spiral.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'ram_debug',        'Perfusion_AIF_TwoEchoes_Interleaved_R2_141303_43029071_43029076_563_20180515-175337',        'VD',   'Generic_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask_istore.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',             'meas_MID838_PK_rt_test_2slice_FID22519',        'VD',   'Generic_RTCine.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    % R=4
    'ram_debug',             'RT_Cine_LIN_141303_43029071_43029076_567_20180515-180704',        'VD',   'GTPrep_2DT_RTCine.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'ram_debug',             'RT_Cine_LIN_141303_43029071_43029076_567_20180515-180704',        'VD',   'Generic_RTCine.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % R=1
    'ram_debug',             'RT_Cine_LIN_141303_43029071_43029076_569_20180515-181143',        'VD',   'Generic_RTCine.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'SNR_Unit_Recon\NoiseDebug',             'meas_MID01106_FID23120_BEAT_interactive_1123_GT',        'VD',   'grappa_cpu.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'localizer',             'meas_MID00286_FID23857_tfl_loc_4_chamber_iPAT',        'VD',   'Generic_Cartesian_Grappa.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'QA',                    'meas_MID00329_FID117686_Coil_QA',                      'VD',   'Generic_Cartesian_Grappa_SNR.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'QA',                    'meas_MID00237_FID119468_RealTimeCine',                 'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',              'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'QA',                    'meas_MID00240_FID119471_GT_tfl_R2_Res128',             'VD',   'Generic_Cartesian_Grappa.xml',              'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'SpiralRaj',             'meas_MID00098_FID15665_Raj_pSpiral_Flow_2shot_PA2',             'VD',   'spiral_flow_gpusense_cg.xml',              'res',              'ref',   'IsmrmrdParameterMap_Siemens_Spiral.xsl'   ; ...
    
    'CoilSen',                    'meas_MID00298_FID25725_AdjCoilSens',                      'VB',   'default_measurement_dependencies_Noise_CoilSen_SCC.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'CoilSen',                    'meas_MID00310_FID25737_NoiseQA_Lighthouse',               'VD',   'Generic_Cartesian_Grappa_SNR.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'PhaseImaging',          'meas_MID00061_Thermo_epi_FID05626',                 'VD',   'Generic_Cartesian_Grappa_EPI.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens_EPI_PF_PreZeros.xsl'   ; ...
    'PhaseImaging',          'meas_MID00046_ep2d_fid_15coupes_150_DYN_FID101989', 'VD',   'Generic_Cartesian_Grappa_EPI.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens_EPI_PF_PreZeros.xsl'   ; ...
    
    'ut\20170420_phantom_perfusion\T2',                    'meas_MID00078_FID44965_T2map_3pt_TRUFI_192i',               'VD',   'Generic_Cartesian_Grappa_SNR.xml',                                  'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
