function UTCases = set_up_UT_cases_NX;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'XA20A',         'meas_MID00338_FID28519_qPerf_SSFP_3sl_stress',         'NX20',   'GTPrep_Perf_AIF_2E_Mapping_AI_4px_OFFLINE.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    'XA20A',         'meas_MID00341_FID28522_qPerf_SSFP_3sl_rest',         'NX20',   'GTPrep_Perf_AIF_2E_Mapping_AI_4px_OFFLINE.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    
    'NXVA11A/QLDXRAY',         'meas_MID00268_FID249972_Stress_SSFP_qPerf_3sl',         'NX20',   'GTPrep_Perf_AIF_2E_Mapping_AI_4px_istore.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    'NXVA11A/QLDXRAY',         'meas_MID00269_FID249973_Rest_SSFP_qPerf_3sl',         'NX20',   'GTPrep_Perf_AIF_2E_Mapping_AI_4px_istore.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    
    'VIDA_TEST_DATA',         'meas_MID00174_FID04926_de_tfl_high_res_psir_LG',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_Denoise_OnTheFly.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    
    'NXVA11A',         'meas_MID00021_FID29399_BEAT_epi_DS_AIF',         'NX',   'GTPrep_2DT_Perf_AIFR3_2E_Lin_Mapping_MBF_MBV_Mask_CMR_View_OFFLINE.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    'NXVA11A',         'meas_MID00025_FID29299_BEAT_epi_DS_AIF',         'NX',   'GTPrep_2DT_Perf_AIFR3_2E_Lin_Mapping_MBF_MBV_Mask_CMR_View_OFFLINE.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    
    'NXVA11A',         'meas_MID00031_FID30684_PSIR_MOCO_8_avg_9_slice_GT',         'NX',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...

    'NormalOrien/BARTS_Perfusion_20191011',         'meas_MID00314_FID259832_SSFP_Test_Perf_MBF_AI',         'NX',   'GTPrep_2DT_Perf_AIFR3_2E_Lin_Mapping_MBF_MBV_Mask_CMR_View_OFFLINE.xml',                          'moco_ave_res_fil',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    
    'NXVA11A',         'Perfusion_AIFR3_2E_Interleaved_175749_00002607024.2607061_00002607024.2607061_322_20191022-125558',         'NX',   'GTPrep_2DT_Perf_AIFR3_2E_Lin_Mapping_MBF_MBV_Mask_CMR_View_OFFLINE.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX.xsl'   ; ...
    
    'D:\data\test\XA20',         'meas_MID00032_FID00510_SSFP_BEAT_epi_DS_AIF',         'NX',   'GTPrep_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask_AI_CMR_View_OFFLINE.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX20A.xsl'   ; ...
    
    'perfusion/VIDA_datfiles',         'meas_MID00111_FID25648_FLASH_BEAT_epi_DS_AIF_prueba',         'NX20',   'GTPrep_2DT_Perf_AIF_2E_Lin_Mapping_MBF_MBV_Mask_AI_CMR_View_OFFLINE.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens_Perfusion_NX20A.xsl'   ; ...
    
    'perfusion',         'meas_MID00239_FID59772_qPerf_GRE',         'NX20',   'GTPrep_Perf_AIF_2E_Mapping_AI_4px_OFFLINE.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens_Perfusion_1437.xsl'   ; ...
    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end