function UTCases = set_up_UT_cases_GT_UT;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    
    'GT_UT/CoilQA',                         'meas_MID00202_FID109023_Coil_QA',                          'VD',   'GTPrep_2DT_Cartesian_GFactor_NoiseStd.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/CoilQA',                         'meas_MID00202_FID109023_Coil_QA',                          'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml', 'res2',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 

    'GT_UT/simple_gre',                     'meas_MiniGadgetron_GRE',                                   'VB',   'default.xml',      'res',           'ref',   'IsmrmrdParameterMap.xsl'   ; ...
    
    'GT_UT/simple_gre',                     'meas_MiniGadgetron_GRE',                                   'VB',   'matlab.xml',      'res',           'ref',   'IsmrmrdParameterMap.xsl'   ; ...
    
    'GT_UT/simple_gre',                     'meas_MiniGadgetron_GRE',                                   'VB',   'Generic_Cartesian_Grappa.xml',      'res_generic',           'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/gre_3d',                         'meas_MID248_gre_FID30644',                                 'VB',   'default_optimized.xml', 'res',      'ref',   'IsmrmrdParameterMap.xsl'   ; ...
    
    'GT_UT/T2W',                            'meas_MID00057_T2w',                                        'VD',   'GT_2DT_T2W.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/T2W',                            'meas_MID00057_T2w',                                        'VD',   'Generic_Cartesian_Grappa_T2W.xml',   'res_generic', 'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/T2W',                            'meas_MID00123_FID43785_gt_CV_T2w_segmented',               'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/T2W',                            'meas_MID00057_FID25460_QQQ_4ch_CV_T2w_567C_MOCO',          'VD',   'GTPrep_2DT_T2W_MOCO_AVE.xml',                                                  'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/LGE',                            'meas_MID00083_9_slice',                                    'VD',   'GT_2DT_LGE.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/3D_head',                        'meas_MID00156_FID05944_GRE_128iso_p2x2',                   'VD',   'GT_3DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/3D_head',                        'meas_MID00156_FID05944_GRE_128iso_p2x2',                   'VD',   'Generic_Cartesian_Grappa.xml', 'res_generic',       'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/3D_head',                        'meas_MID00173_FID08775_head_gre_ipat3x2',                  'VD',   'GT_3DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/3D_head',                        'meas_MID00176_FID08778_head_gre_ipat3x3',                  'VD',   'GT_3DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/3D_head',                        'meas_MID00370_FID29656_head_gre_ipat2x2_96',               'VD',   'Generic_Cartesian_Grappa.xml', 'res_generic',       'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/FatWater',                       'meas_MID00342_3e2i_R4',                                    'VD',   'GT_2DT_FatWater.xml', 'res',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/FetalHASTE',                     'raw30488',                                                 'VD',   'GT_2DT_HASTE.xml', 'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/localizer',                      'meas_MID00026',                                            'VD',   'GT_2DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'GT_UT/localizer',                      'meas_MID00026',                                            'VD',   'GTPrep_2DT_Cartesian_Dicom.xml', 'res_dicom',       'ref_dicom',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'GT_UT/MOLLI',                          '20100330_10h33m11s_5562',                                  'VD11', 'GT_2DT_MOLLI.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/Perfusion',                      'meas_MID00045_R3_AIF_ON',                                  'VD',   'GT_2DT_Perfusion.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'GT_UT/TSE',                            'meas_MID00450_FID76726_SAX_TE62_DIR_TSE',                  'VD',   'GT_2DT_Cartesian.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/TSE',                            'meas_MID00450_FID76726_SAX_TE62_DIR_TSE',                  'VD',   'Generic_Cartesian_Grappa.xml', 'res_generic',       'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    
    'GT_UT/RealTimeCine',                   'meas_MID21_CINE_R4',                                       'VD',   'GT_2DT_RealTimeCine.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/RealTimeCine',                   'meas_MID21_CINE_R4',                                       'VD',   'GT_2DT_Cartesian_GFactor.xml', 'gfactor_res',       'gfactor_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/RealTimeCine',                   'meas_MID21_CINE_R4',                                       'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml', 'res_generic',       'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
      
    'GT_UT/RealTimeCine',                   'meas_MID00034_FID69052_Stress_realtime_gt_TPAT4',          'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling.xml', 'gfactor_res',       'gfactor_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/RealTimeCine',                   'meas_MID00330_FID73046_Stress_realtime_gt_TPAT4',          'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml', 'gfactor_res',       'gfactor_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'GT_UT/RealTimeCine_9slices',           'meas_MID00832',                                            'VD',   'GT_2DT_RealTimeCine.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'GT_UT/sasha',                          '20140325_15h59m29s_7720',                                  'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'GT_UT/snr_unit_recon_builtin_noise',   'meas_MID00127_FID02864_GRE_reps=150__WIP724_sPAT=4',                                   'VD11',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_ipat4',           'meas_MID00175_FID02912_GRE_reps=150_iPAT=4',                                           'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/ProspectiveCine',                'meas_MID00209_FID07469_CV_gtPlus_2D_epat4',                                            'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_spat2_asym_pf',   'meas_MID00156_FID03210_GRE_reps=50_sPAT2_xRes256_dummy1_FOV240_strong_asym_7_8pf',     'VD',   'GTPrep_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_spat3',           'meas_MID00152_FID03206_GRE_reps=20_sPAT3_xRes256_dummy1_FOV240',                       'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/snr_unit_recon_tpat3',           'meas_MID00171_FID02908_GRE_reps=150_TPAT=3',                                           'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    
    'GT_UT/snr_unit_recon_no_pat',          'meas_MID00032_FID22409_oil_gre_128_150reps_pause_alpha_10',                            'VD',   'GT_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    'GT_UT/snr_unit_recon_no_pat',          'meas_MID00032_FID22409_oil_gre_128_150reps_pause_alpha_10',                            'VD',   'Generic_Cartesian_Grappa_SNR.xml', 'res_generic',       'ref_generic',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
      
    'SNR_Unit_Recon/SNR_unit_data2',        'meas_MID00322_FID03059_GRE_reps=150_Res256_sPAT2_phs_res_75_peFOV75_pf7_8_weak_asym',  'VD',   'GTPrep_2DT_Cartesian_GFactor.xml', 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    
    'GT_UT/CineBinning',                    'meas_MID836_PK_rt_test_1slice_FID22517',                               'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/CineBinning',                    'meas_MID838_PK_rt_test_2slice_FID22519',                               'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'GT_UT/CineBinning',                    'meas_MID00391_FID21051_4CH_CV_binning',                                'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    'GT_UT/CineBinning',                    'meas_MID00247_FID39104_PK_realtime_gt_TPAT4_6_8',                      'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                           'binning_res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    'GT_UT/Nonlinear',                      '20140703_11h09m11s_12297',                                             'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',             'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'GT_UT/7T',                             'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648',      'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',           'grappa_res',         'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/RetroGating',                    'meas_MID00385_FID00375_RetroCine_NL_15msT_Res192_NHLBI_Cloud',         'VD',   'GTPrep_2DT_RetroGated_Cine.xml',                                 'slep_res',                'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...
    
    'GT_UT/LGE',                            'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',          'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/LGE',                            '20150820_09h51m56s_98420',                                             'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/epi',                            'meas_MID01349_FID12150_amri_ep2d_bold_96x72x5_R2_16avg_gadgetron',     'VD',   'Generic_Cartesian_Grappa_EPI_AVE.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI_FLASHREF.xsl'  ; ...   
    
    'GT_UT/perfusion',                      'meas_MID00332_FID73048_BIG__075_STRESS_FLASH_PERF_TPAT3_PF3_4_192x111','VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml', 'grappa_flow_res',            'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'GT_UT/perfusion',                      '20150812_09h12m51s_96225',  'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml', 'grappa_flow_res',            'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'GT_UT/RealTimeFlow',                   'meas_MID00089_FID19207_real_time_flow_R5_30s',                         'VD',   'GTPrep_2DT_RTFlow_KspaceBinning.xml',                          'binning_res',             'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/t2star',                         'meas_MID287_CV_me_584Z_DB_FB_160_FS_FID140155',                        'VB',   'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/t2star',                         '20150302_10h20m21s_66499',                                             'VD',   'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'GT_UT/t2star',                         '20150317_10h14m14s_69403',                                             'VD',   'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'GT_UT/B1Mapping',                      'meas_MID00089_FID22003_STACK_B1Map_ep2d_fid_snv_gt_a120_rep30_PAT2_VREF750_FOV320',  'VD',   'B1mapping.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'  ; ...
    'GT_UT/epi',                            'meas_MID517_nih_ep2d_bold_fa60_FID82077',                              'VD',   'epi.xml',                                                           'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'  ; ...   
    
    'GT_UT/generic',                        'meas_MID00062_FID114726_SAX_SASHA',                                    'VB',   'Generic_Cartesian_Spirit_SASHA.xml',                                        'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'GT_UT/data/generic/meas_MID01095_FID40115',                        'meas_MID01095_FID40115',                                               'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',                 'nl_spirit_res',           'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'GT_UT/generic',                        'meas_MID836_1slice_FID22517',                                          'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',                 'nl_spirit_res',           'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'GT_UT/bart',                        'meas_MID00168_FID39823_R3_RT_Cine_res160_46ms_NL_BART_Proto1',            'VD',   'BART_Recon.xml',                 'bart_res',           'bart_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end


