function UTCases = set_up_UT_cases_GtPrep_4px_UT;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    
%     'gtprep_data/gtprep/LGE',             'LGE_MOCO_AVE_OnTheFly_66016_542414246_542414255_1622_20180523-144633',            'VD',   'Siemens_Gadgetron_LGE_MOCO_AVE.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
%     'gtprep_data/gtprep/LGE',             'LGE_MOCO_AVE_OnTheFly_42110_59370386_59370395_310_20180523-141913',            'VD',   'Siemens_Gadgetron_LGE_MOCO_AVE.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...


    %'gtprep_data/gtprep/FatWater',         'FatWater_42363_64992122_64992127_173_20181115-123957',        'VB',   'Generic_Cartesian_Grappa_CoilQA_ECG.xml',         'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/FatWater',         'meas_MID00078_FID114909_AX_DB_FW_3e2i_CxMOCO_724',        'VD',   'GTPrep_2DT_FatWater_Diego.xml',                              'ref',          'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/FatWater',         'FB_DB_FW_3e_MOCO_724_2ch_166032_40907579_40907586_154_20180626-130827',        'VB',   'GTPrep_2DT_FatWater_Diego.xml',         'ref',          'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/FatWater',         'FatWater_42363_64992122_64992127_173_20181115-123957',        'VB',   'GTPrep_2DT_FW_CINE_Diego.xml',                           'ref',          'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/FatWater',         'BH_PSIR_FW_segm_724_4e_42363_345380291_345380374_1872_20180817-161559',  'VD',   'GTPrep_2DT_FW_PSIR_Diego.xml',                        'ref',          'ref2',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'gtprep_data/gtprep/FatWater',         'FB_PSIR_FW_MOCO_724_3e_42363_345380291_345380374_1882_20180817-162814',  'VD',   'GTPrep_2DT_FW_MOCO_AVE_PSIR_Diego.xml',               'ref',          'ref2',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    
    'gtprep_data/gtprep/7T',              'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648',        'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',         'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/CineBinning',     'meas_MID836_PK_rt_test_1slice_FID22517',                                 'VD',   'CMR_2DT_Binning_Cloud.xml',      'ref',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/CineBinning',     'meas_MID838_PK_rt_test_2slice_FID22519',                                 'VD',   'CMR_2DT_Binning_Cloud.xml',      'ref',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/CineBinning',     'Cmr_Binning_Cloud_42537_19272744_19272754_38_20210706-070055',           'VD',   'CMR_2DT_Binning_Fil_LAX_GLS_AI_Cloud.xml',      'ref',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    % 'gtprep_data/gtprep/CineBinning',     '20150923_11h51m34s_62440',                                               'VD',   'GTPrep_2DT_RTCine_Binning.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/LGE',             'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',            'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/LGE',             'meas_MID120_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343803',                   'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',              'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/LGE',             'meas_MID00355_FID81568_3CH_gt_PSIR_FLASH_9sl_8ave_MOCO',                 'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/LGE',             'meas_MID00569_FID178560_FB_DB_PSIR_10sl_16_ave_MOCO',                    'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',     'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/Nonlinear',       '20140703_11h09m11s_12297',                                               'VD',   'GTPrep_2DT_RTCine_SLEP_PInterp.xml',   'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
        
    'gtprep_data/gtprep/RetroGating',     'meas_MID00385_FID00375_RetroCine_NL_15msT_Res192_NHLBI_Cloud',           'VD',   'GTPrep_2DT_RetroGated_Cine.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/RetroGating',     'meas_MID00208_FID115039_SAX_fisp_retro_iPAT_256',                        'VD',   'GTPrep_2DT_RetroGated_Cine.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/RetroGating',     'meas_MID00031_FID107666_4CH_fisp_retro_iPAT_256',                        'VD',   'GTPrep_2DT_RetroGated_Cine.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/RetroGating',     'meas_MID00310_FID08882_R3_Retro_Lin_Cine_30ms_SAX',                      'VD', 'GTPrep_2DT_RetroGated_Cine_MS_Contouring.xml',           'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'gtprep_data/gtprep/RetroGating',     'meas_MID00173_FID04438_cine_tf2d15_retro',                               'VD',  'GTPrep_2DT_RetroCine_AI.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'gtprep_data/gtprep/RetroGating',     'Retro_Lin_Cine_2DT_41837_1130353702_1130353711_34_20200408-140548',      'VD',  'GTPrep_2DT_RetroCine.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    'gtprep_data/gtprep/RetroGating',   'ch2',            'VD',  'GTPrep_2DT_RetroCine_CMR_View_AI_analysis.xml',    'ref',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'gtprep_data/gtprep/RetroGating',   'ch4',            'VD',  'GTPrep_2DT_RetroCine_CMR_View_AI_analysis.xml',    'ref',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'gtprep_data/gtprep/RetroGating',   'sax',            'VD',  'GTPrep_2DT_RetroCine_CMR_View_AI_analysis.xml',    'ref',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    
    'gtprep_data/gtprep/RetroGating',   'ch4',            'VD',  'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',    'ref_GLS',              'ref_GLS',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    
    'gtprep_data/gtprep/RetroGating',   'threeslices',    'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',         'ref',              'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'gtprep_data/gtprep/RetroGating',   'external_triggering',    'VD',   'GTPrep_2DT_RetroCine_CMR_View_GLS_AI_analysis.xml',         'ref',              'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/Perfusion',       'Perfusion_AIF_TwoEchoes_Interleaved_R2_41672_54147266_54147276_1046_20160602-123712',  'VD',   'GTPrep_Perf_AIF_2E_Mapping_AI_4px.xml',        'ref_AI',        'ref_AI2',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...   
    'gtprep_data/gtprep/Perfusion',       'Perfusion_AIFR3_2E_Interleaved_66097_27775548_27775556_224_20190529-094429',           'VD',   'GTPrep_Perf_AIFR3_2E_Mapping_AI_4px.xml',        'ref_AI',        'ref_AI2',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...

    'gtprep_data/gtprep/Perfusion',       'Perfusion_AIFR3_2E_Interleaved_141550_96588428_96588436_378_20191230-141357',          'VD',   'GTPrep_Perf_AIFR3_2E_Mapping_AI_4px.xml',        'ref',        'ref_AI',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'gtprep_data/gtprep/Perfusion',       'sola',                                                                                 'NX20A','GTPrep_Perf_AIF_2E_Mapping_AI_4px.xml',        'ref',        'ref_AI',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    %'gtprep_data/gtprep/Perfusion',       'Perfusion_AIFR3_2E_Lin_Cloud_42363_9649032_9649037_1273_20180927-175606',  'VD',   'GTPrep_Perf_AIFR3_2E_Mapping_AI_4px.xml',        'ref',        'ref_AI',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
   
    
    'gtprep_data/gtprep/RealTimeFlow',    'meas_MID00089_FID19207_real_time_flow_R5_30s',                           'VD',   'GTPrep_2DT_BinningFlow.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    'gtprep_data/gtprep/BinningFlow',    'meas_MID01013_FID04300_BinningFlow_Res192_R2_50s',                           'VD',   'GTPrep_2DT_BinningFlow_Fil.xml',      'res',           'ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...
    
    'gtprep_data/gtprep/t2star',          'meas_MID00372_FID108007_SAX_gt_T2Star_MOCO_DB_8e',                       'VD',   'GTPrep_2DT_T2Star_Mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/B1Mapping',       'meas_MID00272_FID112569_B1MAP_BH_a90_rep30_PAT2',                        'VD',   'B1mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'   ; ...
    
    'gtprep_data/gtprep/T2W',             'meas_MID00123_FID43785_gt_CV_T2w_segmented',                             'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',              'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/T2W',             'meas_MID00371_FID108006_SAX_gt_T2w_9sl_8ave_MOCO',                       'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',     'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/snr',                  'meas_MID00134_FID02324_SNR_GFactor_R1_Res160_BW500',                'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/snr',                  'meas_MID00132_FID02322_SNR_GFactor_R1',                             'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/snr',                  'meas_MID00131_FID02321_SNR_GFactor_R2',                             'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/snr',                  'meas_MID00133_FID02323_SNR_GFactor_R3',                             'VD',   'Generic_Cartesian_Grappa_SNR_CoilQA.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/t2mapping',            'meas_MID00058_FID09494_T2Map_TrueFISP',                             'VD',   'GTPrep_2DT_MOCO_AVE_T2_Mapping_istore.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_T2Mapping.xsl'   ; ...
    
    'gtprep_data/gtprep/RTCine',               'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_RTCine_PInterp_ECG.xml',     'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'gtprep_data/gtprep/RTCine',               'RT_Cine_LIN_42363_08229514_08229519_283_20181205-140724',              'VD',   'Generic_RTCine_PInterp_Fil_ECG.xml',     'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'gtprep_data/gtprep/RetroGating',     'meas_MID00454_FID07520_R3_Retro_NLin_Cine_8ms_4Ch',                      'VD',  'Generic_2DT_RetroGated_Cine_ECG.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        

    'gtprep_data/gtprep/ecg',               '2ch_Pilot_41837_62411242_62411251_867_20180829-114900',              'VD',   'Generic_Cartesian_Grappa_CoilQA_ECG.xml',     'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'gtprep_data/gtprep/ecg',               'CMR_Localizer_ECG_Training_41837_739006564_739006569_181_20200417-181211',              'VD',   'Generic_Cartesian_Grappa_CoilQA_ECG.xml',     'ref',              'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'gtprep_data/gtprep/ecg',               'CMR_Localizer_ECG_Training_41837_8357815_8357824_1081_20210414-115624',              'VD',   'Generic_Cartesian_Grappa_CoilQA_ECG.xml',     'ref',              'ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'gtprep_data/gtprep/RTCine',                  'rtcine_1slice',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_LAX_AI.xml',           'ref',        'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'gtprep_data/gtprep/t1t2', 'T1SR_Mapping_SASHA_HC_T1T2_42363_670701690_670701695_237_20200612-163645', 'VD', 'SASHA-HC_grappa_moco_AVE_AI_CMR_View.xml', 'ref', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...       
    'gtprep_data/gtprep/t1t2', 'T1SR_Mapping_SASHA_HC_T1T2_141613_33813360_33813368_325_20200719-140652', 'VD', 'SASHA-HC_grappa_moco_AVE_AI_CMR_View.xml', 'ref', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...       
    
    'gtprep_data/gtprep/MultSlice_T2_Localizer', 'CMR_MultSlice_T2_Localizer_AI_41837_673916_673925_1177_20210210-135113', 'VD', 'Generic_MultiSlice_Localizer_AI.xml', 'ref', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...       
    % 'gtprep_data/gtprep/MultSlice_T2_Localizer', 'CMR_Localizer_ECG_Training_141316_118477969_118477976_448_20210209-132653', 'VD', 'Generic_MultiSlice_Localizer_AI.xml', 'ref', 'grappa_ref', 'IsmrmrdParameterMap_Siemens_T1Mapping_SASHA.xsl'   ; ...       
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

disp('set_up_UT_cases_GtPrep_4px_UT')

if(nargout<=0)
    UTCases = [];
end
