function UTCases = set_up_UT_cases_FreeMax_AI_Denoising;
% run the gt recon

% set_UT_Dir('D');

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'FreeMax/SCMR/2022-08-19-HV-cardiac-DL',         'meas_MID00442_FID06019_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-19-HV-cardiac-DL',         'meas_MID00443_FID06020_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-19-HV-cardiac-DL',         'meas_MID00444_FID06021_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-19-HV-cardiac-DL',         'meas_MID00456_FID06033_Sax_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-19-HV-cardiac-DL',         'meas_MID00457_FID06034_Sax_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-19-HV-cardiac-DL',         'meas_MID00459_FID06036_Sax_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    

    'FreeMax/SCMR/2022-08-23-HV-cardiac-SNR-DL',         'meas_MID00038_FID06109_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-23-HV-cardiac-SNR-DL',         'meas_MID00039_FID06110_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-23-HV-cardiac-SNR-DL',         'meas_MID00040_FID06111_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-23-HV-cardiac-SNR-DL',         'meas_MID00051_FID06122_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-23-HV-cardiac-SNR-DL',         'meas_MID00053_FID06124_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-23-HV-cardiac-SNR-DL',         'meas_MID00055_FID06126_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    

    'FreeMax/SCMR/2022-08-24-Cardiac-SNR-DL',         'meas_MID00134_FID06218_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-24-Cardiac-SNR-DL',         'meas_MID00135_FID06219_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-24-Cardiac-SNR-DL',         'meas_MID00136_FID06220_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-24-Cardiac-SNR-DL',         'meas_MID00145_FID06229_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-24-Cardiac-SNR-DL',         'meas_MID00147_FID06231_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-24-Cardiac-SNR-DL',         'meas_MID00149_FID06233_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    
    'FreeMax/SCMR/2022-08-30_HV_cardiac_SNR_DL_pulseOx',         'meas_MID00312_FID06396_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-30_HV_cardiac_SNR_DL_pulseOx',         'meas_MID00313_FID06397_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-30_HV_cardiac_SNR_DL_pulseOx',         'meas_MID00314_FID06398_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-30_HV_cardiac_SNR_DL_pulseOx',         'meas_MID00322_FID06406_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-30_HV_cardiac_SNR_DL_pulseOx',         'meas_MID00323_FID06407_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-30_HV_cardiac_SNR_DL_pulseOx',         'meas_MID00324_FID06408_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    
    'FreeMax/SCMR/2022-08-31-HV_cardiac_DL_SNR',         'meas_MID00422_FID06505_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-31-HV_cardiac_DL_SNR',         'meas_MID00423_FID06506_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-31-HV_cardiac_DL_SNR',         'meas_MID00424_FID06507_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-31-HV_cardiac_DL_SNR',         'meas_MID00431_FID06514_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-31-HV_cardiac_DL_SNR',         'meas_MID00432_FID06515_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-08-31-HV_cardiac_DL_SNR',         'meas_MID00433_FID06516_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    
    'FreeMax/SCMR/2022-09-08-HV_cardiac_DL_SNR',         'meas_MID00586_FID06668_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-08-HV_cardiac_DL_SNR',         'meas_MID00587_FID06669_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...        
    'FreeMax/SCMR/2022-09-08-HV_cardiac_DL_SNR',         'meas_MID00588_FID06670_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...        
    'FreeMax/SCMR/2022-09-08-HV_cardiac_DL_SNR',         'meas_MID00603_FID06685_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-08-HV_cardiac_DL_SNR',         'meas_MID00604_FID06686_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-08-HV_cardiac_DL_SNR',         'meas_MID00605_FID06687_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...        
    
    'FreeMax/SCMR/2022-09-12_HV_cardiac_SNR_DL',         'meas_MID00074_FID06815_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-12_HV_cardiac_SNR_DL',         'meas_MID00075_FID06816_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-12_HV_cardiac_SNR_DL',         'meas_MID00076_FID06817_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-12_HV_cardiac_SNR_DL',         'meas_MID00091_FID06832_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-12_HV_cardiac_SNR_DL',         'meas_MID00092_FID06833_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-12_HV_cardiac_SNR_DL',         'meas_MID00093_FID06834_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    
    'FreeMax/SCMR/2022-09-15_HV_cardiac_SNR_DL',         'meas_MID00219_FID06956_repeat_Ch4_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-15_HV_cardiac_SNR_DL',         'meas_MID00223_FID06960_Ch4_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-15_HV_cardiac_SNR_DL',         'meas_MID00225_FID06962_Ch4_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-15_HV_cardiac_SNR_DL',         'meas_MID00234_FID06971_MID_SAX_CINE_IPAT2_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-15_HV_cardiac_SNR_DL',         'meas_MID00240_FID06977_MID_SAX_CINE_IPAT3_256Res_24ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    
    'FreeMax/SCMR/2022-09-15_HV_cardiac_SNR_DL',         'meas_MID00243_FID06980_MID_SAX_CINE_IPAT4_256Res_36ref',              'NX',   'GTPrep_2DT_RetroCine_CNNT_offline.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens_NX.xsl'   ; ...    


    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
