function UTCases = set_up_UT_cases_BinningCine;
% run the gt recon

set_UT_Dir('D')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {  
    'binning\20150923_StudyLoid_12.0.123557963_CNMC2359-C0832',                  '20150923_11h51m34s_62440',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning\20150923_StudyLoid_12.0.123557963_CNMC2359-C0832',                  '20150923_11h51m34s_62440',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',            'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h09m53s_62222',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h09m53s_62222',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',            'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h39m35s_62241',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h39m35s_62241',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',            'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    'binning',                  '20160201_10h27m06s_78653',                             'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20160201_10h27m06s_78653',                             'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',             'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID00127_FID13470_SAX_ReBinning_256_CLOUD',       'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID00127_FID13470_SAX_ReBinning_256_CLOUD',       'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID00169_FID13512_Ax_ReBinning_256_Cloud',        'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID00169_FID13512_Ax_ReBinning_256_Cloud',        'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID00322_FID06960_RealTimeCineBinning',           'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID00322_FID06960_RealTimeCineBinning',           'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  '20160307_11h13m09s_4537',                              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20160307_11h13m09s_4537',                              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',               'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID00391_FID21051_4CH_CV_binning',               'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID00391_FID21051_4CH_CV_binning',               'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  'meas_MID00247_FID39104_PK_realtime_gt_TPAT4_6_8',     'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  'meas_MID00247_FID39104_PK_realtime_gt_TPAT4_6_8',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  '20140725_09h39m20s_15118',     'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20140725_09h39m20s_15118',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  '20140808_10h43m11s_16687',     'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20140808_10h43m11s_16687',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  '20140808_10h46m55s_16688',     'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20140808_10h46m55s_16688',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20140808_10h46m55s_16688',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res3',              'generic_ref3',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'binning',                  '20140811_08h51m42s_16829',     'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20140811_08h51m42s_16829',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'binning',                  '20140811_08h51m42s_16829',     'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'generic_res2',              'generic_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...        
    
    'binning\STALCUP',    'meas_MID00200_FID26809_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
