function UTCases = set_up_UT_cases_LGE;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'LGE\upmc',         'meas_MID137_4ch_PSIR_FLASH_FID264063',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_12bit.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\upmc',         'meas_MID128_4ch_MOCO_PSIR_LGE_GT_FID264054',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage_SavedISMRMRD_localhost.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\upmc',         'meas_MID129_3ch_MOCO_PSIR_LGE_GT_FID264055',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage_SavedISMRMRD_localhost.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\upmc',         'meas_MID130_2ch_MOCO_PSIR_LGE_GT_FID264056',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage_SavedISMRMRD_localhost.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    

    'LGE\OSU',         'meas_MID00213_FID158480_FB_gt_PSIR_9sl_8ave_MOCO_VLA_state_clf',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\SCC_Test',         '20150302_10h50m25s_66537',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
                
    'LGE',         'meas_MID00076_FID60410_gt_PSIR_FLASH_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE',         'meas_MID00358_FID115734_gt_PSIR_FLASH_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\BLOOD_INHOMOGENEITY',         '20150521_12h54m02s_50720',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\VB17A_artifact_moco_case',         'Pat1_PSIR',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17A_artifact_moco_case',         'Pat2_PSIR',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
       
    'LGE\AERA_FLASH_segmented_BH_normalization\E07505',         '20150820_09h49m09s_98415',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\AERA_FLASH_segmented_BH_normalization\E07505',         '20150820_09h51m56s_98420',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_ismrmrd_storage.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\RINGING_CASE\E07514',         '20150824_14h54m18s_99532',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\VE11A_PSIR_MOCO',         'meas_MID00275_FID64940_FB_gt_PSIR_1sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_12bit.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
       
    'LGE\SUB_Crash',         'meas_MID00129_FID103755_Sax_gt_PSIR_Segm_FLASH',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_12bit.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\GoodCase_Cyst_A04050',         'meas_MID00354_FID81567_SAX_gt_PSIR_FLASH_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_12bit.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\GoodCase_Cyst_A04050',         'meas_MID00355_FID81568_3CH_gt_PSIR_FLASH_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_12bit.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\GoodCase_Cyst_A04050',         'meas_MID00356_FID81569_COR_gt_PSIR_FLASH_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly_12bit.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\gtPSIR-2015-09-30',         'meas_MID00268_FID61977_PSIR_4ch_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\gtPSIR-2015-09-30',         'meas_MID00269_FID61978_PSIR_3_ch_MOCO',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\VD13A_MOCO_Artifact_case',         '20151022_11h11m57s_110496',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\SUB_Crash',         'meas_MID01214_FID02499_Sax_BH_seqm_FLASH_gt_PSIR',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\VB17_20160226',         'meas_MID110_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343793',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID111_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343794',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID112_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343795',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID113_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343796',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID114_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343797',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID115_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343798',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID116_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343799',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID117_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343800',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID118_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343801',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID119_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343802',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID120_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343803',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID121_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343804',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID122_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343805',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID123_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343806',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID124_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343807',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'LGE\VB17_20160226',         'meas_MID125_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343808',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'LGE\VB17_20160226',         'meas_MID126_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343809',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'LGE\VB17_20160226',         'meas_MID127_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343810',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'LGE\VB17_20160226',         'meas_MID128_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343811',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'LGE\OSU',                  'scc_artifact_case_meas_MID00119_FID139746_DME_psir_bh_HLA',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\OSU',                  'meas_MID00229_FID138541_psir_bh_VLA',         'VB',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'moco_ave_res',            'moco_ave_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
