

function UTCases = set_up_UT_cases_FatWater;
% run the gt recon

set_UT_Dir('D')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'fatwater', 'meas_MID00068_FID05053_QQQ_SAX_DB_CV_me_724_4e2i',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00084_FID06417_QQQ_SAX_DB_CV_me_724_4e2i',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    % 'fatwater', 'meas_MID00087_FID06420_QQQ_2CH_DB_CV_me_724_4e2i',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00342_FID22655_PSIR_FW_3e2i_CxMOCO_724_tpat4',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00599_FID00892_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00600_FID00893_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00601_FID00894_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00602_FID00895_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'fatwater', 'meas_MID00603_FID00896_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00604_FID00897_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00605_FID00898_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00606_FID00899_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00607_FID00900_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00608_FID00901_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00609_FID00902_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...       
    'fatwater', 'meas_MID00610_FID00903_QQQ_Ax_DB_FW_3e2i_CxMOCO_724',  'VD',   'GTPrep_2DT_FatWater.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ... 
    
    'fatwater', 'meas_MID00087_FID06420_QQQ_2CH_DB_CV_me_724_4e2i',  'VD',   'Generic_Cartesian_Grappa_FatWater_Proto.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
