function UTCases = set_up_UT_cases_FOVTest;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'FOVTest', 'meas_MID00144_FID112830_AdjCoilSens',                       'Adj',   'default_measurement_dependencies.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'FOVTest', 'meas_MID00177_FID112863_AdjCoilSens',                       'Adj',   'default_measurement_dependencies.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   

    'FOVTest', 'meas_MID00153_FID112839_CV_R1_PEFOV100_PERes100_PFNo_AsymEchoNo',                       'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'FOVTest', 'meas_MID00155_FID112841_CV_spatR2_PEFOV100_PERes100_PFNo_AsymEchoNo',                   'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    
    'FOVTest', 'meas_MID00157_FID112843_CV_spatR3_PEFOV100_PERes100_PFNo_AsymEchoNo',                   'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00159_FID112845_CV_spatR3_PEFOV100_PERes100_PFNo_AsymEchoNo_InterpON',          'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
           
    'FOVTest', 'meas_MID00169_FID112855_CV_spatR3_PEFOV75_PERes100_PFNo_AsymEchoNo_InterpOFF',          'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00167_FID112853_CV_spatR3_PEFOV75_PERes75_PFNo_AsymEchoNo_InterpOFF',           'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00165_FID112851_CV_spatR3_PEFOV75_PERes75_PF6_8_AsymEchoNo_InterpOFF',          'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    
    'FOVTest', 'meas_MID00187_FID112873_CV_spatR2_PEFOV75_PERes75_PF5_8_AsymEchoNo_InterpOFF',          'VD',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    
    'FOVTest', 'meas_MID00171_FID112857_CV_spatR3_PEFOV100_PERes100_PFNo_AsymEchoNo_InterpOFF',         'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    
    'FOVTest', 'meas_MID00173_FID112859_CV_spatR3_PEFOV75_PERes60_PF6_8_AsymEcho_Strong_InterpOFF',     'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00175_FID112861_CV_spatR3_PEFOV75_PERes60_PF6_8_AsymEcho_Strong_InterpON',      'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00183_FID112869_CV_spatR3_PEFOV75_PERes60_PEOvers21_PF6_8_AsyStrong_InterpON',  'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    
    % generic chain
    'FOVTest', 'meas_MID00175_FID112861_CV_spatR3_PEFOV75_PERes60_PF6_8_AsymEcho_Strong_InterpON',      'VB',   'Generic_Cartesian_Grappa.xml',  'generic_res',  'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    
    % 3D
    'FOVTest', 'meas_MID00178_FID112864_GT_3D_R1_PEFOV100_PARFOV100_InterpOff',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00179_FID112865_GT_3D_R1_PEFOV100_PARFOV100_InterpON',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00180_FID112866_GT_3D_R1_PEFOV75_PARFOV100_InterpOff',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00181_FID112867_GT_3D_R1_PEFOV75_PAROversampling20_InterpOff',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00191_FID112877_GT_3D_R2_PEFOV75_PARRes75_InterpOff',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00193_FID112879_GT_3D_R2_PERes75_PARRes75_PARPF6_8_InterpOff',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'FOVTest', 'meas_MID00194_FID112880_GT_3D_R2_PERes75_PEPF75_PARRes75_PARPF6_8_InterpOff',  'VD',   'GTPrep_3DT_Cartesian.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
