function UTCases = set_up_UT_cases_BinningCloud;
% run the gt recon

set_UT_Dir('D')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = { 'cloud',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
            % 192*144, R5, 9 slice cine
            'cloud',                 '20141211_14h40m45s_32438',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res_0p0001', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
                       
            % binning, 192*144, 16s data
            'cloud',                 'meas_MID01145_FID12389_RealTimeCine_KSpaceBinning_Amazon_cloud',      'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...            

            % binning,
            'binning',                  '20140725_09h39m20s_15118',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140725_09h39m20s_15118',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud_ismrmrd_storage.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  '20140808_10h43m11s_16687',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140808_10h46m55s_16688',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140808_10h47m17s_16689',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140808_10h47m38s_16690',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  '20140811_08h51m42s_16829',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140811_08h55m30s_16830',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  '20150528_09h15m14s_49725',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20150702_10h47m29s_54199',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...               
            
            'binning',                  '20160201_10h27m06s_78653',     'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20160201_10h27m06s_78653',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'generic_cloud_res',              'generic_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  '20160307_11h13m09s_4537',      'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20160608_14h42m27s_18305',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...               
            
            'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h09m53s_62222',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h39m35s_62241',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning\20150923_StudyLoid_12.0.123557963_CNMC2359-C0832',                  '20150923_11h51m34s_62440',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  'meas_MID00324_FID06962_RTCineBinning_Res256',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  'meas_MID00094_FID20352_SAX_RT_Binning_8sec_Lighthouse_(Baseline)',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  'meas_MID00169_FID13512_Ax_ReBinning_256_Cloud',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  'meas_MID00186_FID12170_PK792_binning_192_128_SAX',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  'meas_MID00322_FID06960_RealTimeCineBinning',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  'meas_MID00324_FID06962_RTCineBinning_Res256',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  'meas_MID00391_FID21051_4CH_CV_binning',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  '20160202_09h36m47s_78711',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
                        
            'binning\Segmented_binning','20140801_13h20m17s_16046',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140804_10h49m30s_16197',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140805_09h41m08s_16314',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140806_15h11m46s_16546',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140811_08h51m42s_16829',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140813_08h44m36s_17059',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140815_09h08m39s_17649',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140815_11h43m47s_17744',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140819_09h59m51s_18072',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140820_11h27m29s_18236',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140822_10h39m46s_18655',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140822_11h57m58s_18706',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140828_09h31m25s_19205',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140828_11h16m18s_19268',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning\CNMC_20160802',    'meas_MID00067_FID25968_R2_RT_Cine_Binning_Res192_LocalCloud',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                
            'binning\CNMC_20160802',    'meas_MID00109_FID26010_SAX_R2_RT_Cine_Binning_Res256_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                

            'binning\CNMC_20160802',    'meas_MID00067_FID25968_R2_RT_Cine_Binning_Res192_LocalCloud',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',         'binning_gtprep_res',              'binning_gtprep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                
            'binning\CNMC_20160802',    'meas_MID00109_FID26010_SAX_R2_RT_Cine_Binning_Res256_LocalCloud',          'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',         'binning_gtprep_res',              'binning_gtprep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                
            
            
            'binning\FAULK',    'meas_MID00033_FID26529_SAX_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                
            'binning\HUTTO',    'meas_MID00082_FID26578_SAX_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\STALCUP',    'meas_MID00200_FID26809_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\CNMC2359-V1095',    'meas_MID00042_FID27079_SAX_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\hohel',            'meas_MID00223_FID27306_SAX_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\fialko',           'meas_MID00344_FID27422_SAX_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            

            'binning\CathLab_20160810',    'meas_MID00047_FID24640_2CH_RT_Binning_8sec_(Baseline)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CathLab_20160810',    'meas_MID00052_FID24645_3CH_RT_Binning_8sec_(Baseline)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CathLab_20160810',    'meas_MID00053_FID24646_4CH_RT_Binning_8sec_(Baseline)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CathLab_20160810',    'meas_MID00056_FID24649_SAX_RT_Binning_8sec_Lighthouse_(Baseline)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\HENDERSON',    'meas_MID00188_FID27605_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\CNMC_20160816',    'meas_MID00030_FID27942_SAX_R3_RT_Binning_256_CLOUD_9sl',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160816',    'meas_MID00061_FID27973_SAX_R3_RT_Binning_256_CLOUD_9sl',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160816',    'meas_MID00099_FID28011_SAXC1_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160816',    'meas_MID00135_FID28047_SAX_TEST_TRIGERR3_RT_Binning_256_CLOUD_9sl',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160816',    'meas_MID00138_FID28050_SAX_TEST_BADTRIGGER_R3_RT_Binning_256_CLOUD_9sl',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\CNMC_20160817',    'meas_MID00164_FID28335_SAX_R3_RT_Cine_Binning_Res192_Lighthouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\CNMC_20160822',    'meas_MID00034_FID28758_R3_RT_Binning_256_CLOUD_9sl',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160822',    'meas_MID00042_FID28766_SAX_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160822',    'meas_MID00118_FID28842_SAX_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160822',    'meas_MID00156_FID28880_AX_R2_RT_Cine_Binning_Res160_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_20160822',    'meas_MID00055_FID29083_AX_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning',                  'meas_MID00191_FID31548_SAX_R2_RT_Cine_Binning_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\CNMC_small_baby',    'meas_MID00101_FID33085_SAX_R2_RT_Cine_Binning_Res160_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_small_baby',    'meas_MID00099_FID33083_pSAX_FB_segm_cine_retro',          'VD',   'GTPrep_2DT_RetroGated_Cine.xml',         'retro_res',              'retro_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\CathLab_Pig_20160928',    'meas_MID00032_FID29755_2CH_RT_Binning_8sec_(Baseline)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CathLab_Pig_20160928',    'meas_MID00033_FID29756_4CH_RT_Binning_8sec_(Baseline)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CathLab_Pig_20160928',    'meas_MID00054_FID29777_SAX_RT_Binning_8sec_(Cond_2)(Lighthouse)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CathLab_Pig_20160928',    'meas_MID00104_FID29827_SAX_RT_Binning_8sec_(Cond_2)(Lighthouse)',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            

            'binning\CNMC_4mmSliceThickness',    'meas_MID00029_FID34531_AX_R2_RT_Cine_Binning_4mm_Res160_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_4mmSliceThickness',    'meas_MID00042_FID34345_AX_R2_RT_Cine_Binning_4mm_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            'binning\CNMC_4mmSliceThickness',    'meas_MID00046_FID34548_SAX_R2_RT_Cine_Binning_4mm_Res192_LocalCloud',          'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            
            
            'binning\2016-11-22-RHC_dat',    'meas_MID00065_FID42367_SAX_R2_RT_Cine_Binning_Res256_LightHouse',          'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            

            'binning\CNMC_20161017',    'meas_MID00092_FID35817_SAX_R2_RT_Cine_Binning_Res256_LocalCloud_state_clf',          'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                            

            % test
            'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                
            
            'binning',                  '20150923_11h51m34s_62440',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
