function UTCases = set_up_UT_cases
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {'cine',                  'meas_MID21_CINE__R4_ICEPAT_6_0_secs_6_0mm_REST_FID66101',                      'VB',   'GadgetronProgram_gtPlus_2DT_RealTimeCine.xml',         'grappa_res',       'grappa_ref' ; ...
           'cine',                  'meas_MID21_CINE__R4_ICEPAT_6_0_secs_6_0mm_REST_FID66101',                      'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian_L1SPIRIT.xml',   'l1spirit_res',     'l1spirit_ref' ; ... 
           'cine',                  'meas_MID21_CINE__R4_ICEPAT_6_0_secs_6_0mm_REST_FID66101',                      'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian_SPIRIT.xml',     'spirit_res',       'spirit_ref' ; ...
           
           'cine',                  'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',                      'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           'cine',                  'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',                      'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_L1SPIRIT.xml',   'l1spirit_res',     'l1spirit_ref' ; ...
           'cine',                  'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',                      'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_SPIRIT.xml',     'spirit_res',       'spirit_ref' ; ...
           
           'cine',                  'meas_MID130_STRESS_CINE_R5_FID68512',                                          'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           'cine',                  'meas_MID130_STRESS_CINE_R5_FID68512',                                          'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian_L1SPIRIT.xml',   'l1spirit_res',     'l1spirit_ref' ; ...
           'cine',                  'meas_MID130_STRESS_CINE_R5_FID68512',                                          'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian_SPIRIT.xml',     'spirit_res',       'spirit_ref' ; ...
           
           'molli',                 '20100330_10h33m11s_5562',                                                      'VB',   'GadgetronProgram_gtPlus_2DT_MOLLI.xml',                'grappa_res',       'grappa_ref' ; ...
           
           'sasha',                 '20140325_15h59m29s_7720',                                                      'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           
           'LGE',                   'meas_MID00083_FID26624_QQQ_SAX_PSIR_9___slice_MOCO_CV_826',                    'VD',   'GadgetronProgram_gtPlus_2DT_LGE.xml',                  'grappa_res',       'grappa_ref' ; ...
           
           'LGE\PSIR_REP\meas_MID00059_FID03264_QQQ_1MIN_PSIR_9_slice_MOCO_CV_826_highres',                   'meas_MID00059_FID03264_QQQ_1MIN_PSIR_9_slice_MOCO_CV_826_highres',                    'VD',   'GadgetronProgram_gtPlus_2DT_LGE_MOCO_AVE_OnTheFly.xml',                  'grappa_res',       'grappa_ref' ; ...
           
           'fatwater',              'meas_MID00342_FID22655_PSIR_FW_3e2i_CxMOCO_724_tpat4',                         'VD',   'GadgetronProgram_gtPlus_2DT_FatWater.xml',             'grappa_res',       'grappa_ref' ; ...
           
           'perfusion',             'meas_MID00045_FID22177_QQQ_stress_swap__half_Perfusion_SSFP_TPAT3_810_AIF_ON', 'VD',   'GadgetronProgram_gtPlus_2DT_Perfusion.xml',            'grappa_res',       'grappa_ref' ; ...
           'perfusion',             '20140408_13h17m13s_10066',                                                     'VD',   'GadgetronProgram_gtPlus_2DT_Perfusion.xml',            'grappa_res',       'grappa_ref' ; ...
           
           'localizer',             'meas_MID00026_FID25429_QQQ_tfl_loc_multi_iPAT_c',                              'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           'localizer',             'meas_MID00286_FID23857_tfl_loc_4_chamber_iPAT',                                'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           
           't2w',                   'meas_MID00057_FID25460_QQQ_4ch_CV_T2w_567C_MOCO',                              'VD',   'GadgetronProgram_gtPlus_2DT_T2W.xml',                  'grappa_res',       'grappa_ref' ; ...
           
           '3D',                    'meas_MID00370_FID29656_head_gre_ipat2x2_96',                                   'VD',   'GadgetronProgram_gtPlus_3DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           '3D',                    'meas_MID00370_FID29656_head_gre_ipat2x2_96',                                   'VD',   'GadgetronProgram_gtPlus_3DT_Cartesian_L1SPIRIT.xml',   'l1spirit_res',     'l1spirit_ref' ; ...
           
           '3D',                    'meas_MID00156_FID05944_GRE_128iso_p2x2',                                       'VD',   'GadgetronProgram_gtPlus_3DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           '3D',                    'meas_MID00156_FID05944_GRE_128iso_p2x2',                                       'VD',   'GadgetronProgram_gtPlus_3DT_Cartesian_L1SPIRIT.xml',   'l1spirit_res',     'l1spirit_ref' ; ...
           
           '3D',                    'meas_MID00351_FID27847_QQQ_Angio3D_Sag_pre',                                   'VD',   'GadgetronProgram_gtPlus_3DT_Cartesian.xml',            'grappa_res',       'grappa_ref' ; ...
           '3D',                    'meas_MID00351_FID27847_QQQ_Angio3D_Sag_pre',                                   'VD',   'GadgetronProgram_gtPlus_3DT_Cartesian_L1SPIRIT.xml',   'l1spirit_res',     'l1spirit_ref' ; ...
           
           'REP_MEASUREMENT',       'meas_MID00032_FID22409_oil_gre_128_150reps_pause_alpha_10',                    'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...

           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00145_FID03199_GRE_reps=50_xRes256_dummy1',               'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00146_FID03200_GRE_reps20_xRes256_dummy1',                'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00147_FID03201_GRE_reps=20_sPat2_xRes256_dummy1',         'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00148_FID03202_GRE_reps=20_sPat3_xRes256_dummy1',         'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00149_FID03203_GRE_reps=20_sPat4_xRes256_dummy1',         'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00150_FID03204_GRE_reps=20_xRes256_dummy1_FOV240',        'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00151_FID03205_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240',  'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00152_FID03206_GRE_reps=20_sPAT3_xRes256_dummy1_FOV240',  'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00153_FID03207_GRE_reps=20_sPAT4_xRes256_dummy1_FOV240',  'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00154_FID03208_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240_strong_asym',          'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00155_FID03209_GRE_reps=20_sPAT2_xRes256_dummy1_FOV240_strong_asym_7_8pf',    'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\SNR_unit_data3',              'meas_MID00156_FID03210_GRE_reps=50_sPAT2_xRes256_dummy1_FOV240_strong_asym_7_8pf',    'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
          
           'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00157_FID02894_GRE_reps=150',                                    'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00158_FID02895_GRE_reps=150_sPAT=2',                             'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00159_FID02896_GRE_reps=150_sPAT=3',                             'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00160_FID02897_GRE_reps=150_sPAT=4',                             'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00169_FID02906_GRE_reps=150_TPAT=2',                             'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00171_FID02908_GRE_reps=150_TPAT=3',                             'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00172_FID02909_GRE_reps=150_TPAT=4',                             'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00170_FID02907_GRE_reps=150_higher_BW',                          'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00161_FID02898_GRE_reps=150_strong_asym_echo',                   'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00162_FID02899_GRE_reps=150_strong_asym_echo_6_8_partial_fourier','VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00163_FID02900_GRE_reps=150_sPAT=2_strong_asym_echo',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00164_FID02901_GRE_reps=150_sPAT=3_strong_asym_echo',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00165_FID02902_GRE_reps=150_sPAT=4_strong_asym_echo',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00166_FID02903_GRE_reps=150_sPAT=2_strong_asym_echo_6_8_partial_fourier',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00167_FID02904_GRE_reps=150_sPAT=3_strong_asym_echo_6_8_partial_fourier',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00168_FID02905_GRE_reps=150_sPAT=4_strong_asym_echo_6_8_partial_fourier',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00173_FID02910_GRE_reps=150_iPAT=2',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00174_FID02911_GRE_reps=150_iPAT=3',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           %'SNR_Unit_Recon\AdjNoiseScan\20140404',       'meas_MID00175_FID02912_GRE_reps=150_iPAT=4',            'VD',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           
           'SNR_Unit_Recon\NoNoiseScan',                 'meas_MID00144_FID02881_GRE_reps=150',                   'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...
           
           'SNR_Unit_Recon\BuildInNoiseScan',            'meas_MID00127_FID02864_GRE_reps=150__WIP724_sPAT=4',    'VB',   'GadgetronProgram_gtPlus_2DT_Cartesian_GFactor.xml',    'grappa_res',       'grappa_ref' ; ...           
          };
      
UTCases
