function UTCases = set_up_UT_cases_Cine;
% run the gt recon

set_UT_Dir('D');

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_ismrmrd_storage.xml',              'nl_res',              'nl_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20160113_13h44m33s_77171',              'VD',   'GTPrep_ismrmrd_storage.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00165_FID39820_R3_RT_Cine_Linear_Res160_35ms',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',             'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',              'nl_spirit_res',              'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                 'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',              'VB',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',     'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',              'VB',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00136_FID106369_gtRealTimeCineNonLinear',              'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',      'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',     'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',     'grappa_compression_res',  'grappa_compression_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00051_FID110020_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',      'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00300_FID06938_RTCineNL_NHLBI',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',                    'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00300_FID06938_RTCineNL_NHLBI',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',                        'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00300_FID06938_RTCineNL_NHLBI',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',        'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',            'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00545_FID00840_sax_realtime_tfi_tpat6_724',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
      
    'cine',                  '20140703_11h09m11s_12297',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20140703_11h09m11s_12297',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141007_08h03m17s_23619',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_08h03m17s_23619',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_08h03m17s_23619',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141007_10h39m51s_23674',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_10h39m51s_23674',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_10h39m51s_23674',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141007_12h31m16s_23730',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20141008_13h20m39s_23934',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141008_13h20m39s_23934',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141008_13h20m39s_23934',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20141013_15h07m14s_24419',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141013_15h07m14s_24419',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'cine',                  '20141013_15h07m14s_24419',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141017_10h09m21s_25173',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141017_10h09m21s_25173',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'cine',                  '20141017_10h09m21s_25173',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141020_16h11m10s_25740',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141020_16h11m10s_25740',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'cine',                  '20141020_16h11m10s_25740',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141023_08h43m35s_26080',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141023_08h43m35s_26080',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141023_08h43m35s_26080',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  '20141027_15h31m18s_26452',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141027_15h31m18s_26452',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141027_15h31m18s_26452',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141106_17h08m37s_28065',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141106_17h08m37s_28065',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141106_17h08m37s_28065',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141205_15h37m58s_31798',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141205_15h37m58s_31798',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141205_15h37m58s_31798',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20141219_13h53m08s_33457',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141219_13h53m08s_33457',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141219_13h53m08s_33457',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % good show case
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141211_14h40m45s_32438',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  '20151119_15h29m30s_70292',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20151119_15h29m30s_70292',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20151119_15h29m30s_70292',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00138_FID106371_gtRealTimeCineNonLinear_9slc',              'VB',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res2',              'slep_ref2',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00138_FID106371_gtRealTimeCineNonLinear_9slc',              'VB',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00042_FID96308_cine_SAX_realtime_gt_TPAT4',            'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00042_FID96308_cine_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',           'nl_spirit_res',        'nl_spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
       
    'cine',                  'meas_MID00039_FID110008_2ch_realtime_gt_TPAT4_RT',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00039_FID110008_2ch_realtime_gt_TPAT4_RT',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
      
    'cine',                  'meas_MID00041_FID110010_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00041_FID110010_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00047_FID110016_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00047_FID110016_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00047_FID110016_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'generic_res',              'generic_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00035_FID110004_3ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00035_FID110004_3ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'cine',                  'meas_MID00037_FID110006_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00037_FID110006_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00061_FID110030_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00061_FID110030_2ch_realtime_gt_TPAT4_LT',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',                  'meas_MID00039_FID110008_2ch_realtime_gt_TPAT4_RT',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID00053_FID110022_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID378_sax_realtime_724Free-breathing_FID8217',              'VD',   'Generic_Cartesian_Spirit_RealTimeCine.xml',         'spirit_res',              'spirit_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'cine/RTCine',           'meas_MID00394_FID114123_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00394_FID114123_SAX_realtime_gt_TPAT4',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine_Compression.xml',         'grappa_compression_res',              'grappa_compression_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'binning',           'meas_MID00391_FID21051_4CH_CV_binning',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/RTCine',           'meas_MID00380_FID114109_4CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00382_FID114111_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00384_FID114113_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/RTCine',           'meas_MID00406_FID114135_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00288_FID115664_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00275_FID115651_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00277_FID115653_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine/RTCine',           'meas_MID00273_FID115649_4CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine/ReconChallenge',           'meas_MID378_sax_realtime_724Free-breathing_FID8217',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'cine',           'meas_MID00165_FID39820_R3_RT_Cine_Linear_Res160_35ms',              'VD',   'Generic_Cartesian_Grappa_RealTimeCine.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
