function UTCases = set_up_UT_cases_FreeMax_AI_Denoising_SCMR_2024;
% run the gt recon

% set_UT_Dir('D');

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

'/export/Lab-Xue/data/mri_raw_data/freemax/test',         'meas_MID00722_FID20445_G25_SAX_RTCINE_256_R3_tpat',              'NX',   'Freemax_RTCine_Binning_STCNNT_AI.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    % prior MI
    '/export/Lab-Xue/data/mri_raw_data/freemax/20231102_MI_PT',         'meas_MID00655_FID20374_G25_Perfusion_trufi_sr_tpat_3_192res_TI135',              'NX',   'Freemax_2DT_Perf_NoAIF_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20231102_MI_PT',         'meas_MID00677_FID20400_G25_FB_de_tpat3_res256_Ave16',              'NX',   'Freemax_LGE_REP_STCNNT_offline.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20231102_MI_PT',         'meas_MID00667_FID20390_G33_SAX_FB_de_tpat3_res256_Ave16_BW610_PHASres84',              'NX',   'Freemax_LGE_REP_STCNNT_offline.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    %'/export/Lab-Xue/data/mri_raw_data/freemax/20231102_MI_PT',         'meas_MID00667_FID20390_G33_SAX_FB_de_tpat3_res256_Ave16_BW610_PHASres84',              'NX',   'Freemax_LGE_REP_STCNNT_offline.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    '/export/Lab-Xue/data/mri_raw_data/freemax/20231102_MI_PT',         'meas_MID00646_FID20365_G25_SAX_RTCINE_256_R3_tpat',              'NX',   'Freemax_RTCine_Binning_STCNNT_AI.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    % patients with Gd, R3
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00186_FID04084_REST_G33_perfusion_trufi_sr_Tpat_3_192',              'NX',   'Freemax_2DT_Perf_NoAIF_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',   'meas_MID00225_FID04597_REST_G33_perfusion_trufi_sr_Tpat_3_192',              'NX',   'Freemax_2DT_Perf_NoAIF_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    % LGE, R3
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00211_FID04109_G25_4CH_FB_de_snapshot_p3_BW500',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00212_FID04110_G25_2CH_FB_de_snapshot_p3_BW500',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00215_FID04113_G25_SAX_FB_de_snapshot_p3_BW500',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00206_FID04104_G25_4CH_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00216_FID04114_G25_4CH_FB_de_snapshot_p3_BW500_TI300_REF48',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00217_FID04115_G25_2CH_FB_de_snapshot_p3_BW500_TI300_REF48',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00231_FID04603_repeat_4CH_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00232_FID04604_repeat_2CH_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00233_FID04605_SAX3_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00239_FID04611_G25_4CH_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00241_FID04613_G25_2CH_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00242_FID04614_G25_SAX3_FB_de_snapshot_p2_BW900',              'NX',   'Freemax_LGE_STCNNT.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00211_FID04109_G25_4CH_FB_de_snapshot_p3_BW500',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00212_FID04110_G25_2CH_FB_de_snapshot_p3_BW500',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00215_FID04113_G25_SAX_FB_de_snapshot_p3_BW500',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00206_FID04104_G25_4CH_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00216_FID04114_G25_4CH_FB_de_snapshot_p3_BW500_TI300_REF48',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230511_Pat_MI_Cardiac_Gd',         'meas_MID00217_FID04115_G25_2CH_FB_de_snapshot_p3_BW500_TI300_REF48',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00231_FID04603_repeat_4CH_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00232_FID04604_repeat_2CH_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00233_FID04605_SAX3_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00239_FID04611_G25_4CH_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00241_FID04613_G25_2CH_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230517_Pat_MI',         'meas_MID00242_FID04614_G25_SAX3_FB_de_snapshot_p2_BW900',              'NX',   'GTPrep_LGE.xml',             'res_grappa',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    % retro cine
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230720_NV',   'meas_MID00406_FID09064_G25_4CH_CINE_256_R3ipat_BW399',       'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230720_NV',   'meas_MID00407_FID09065_G25_2CH_CINE_256_R3ipat_BW399',       'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230720_NV',   'meas_MID00411_FID09069_G25_SAX_CINE_256_R3ipat_BW399',       'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       

    '/export/Lab-Xue/data/mri_raw_data/freemax/20230720_NV',   'meas_MID00412_FID09070_G25_4CH_CINE_256_R4ipat_BW399',       'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230720_NV',   'meas_MID00414_FID09072_G25_2CH_CINE_256_R4ipat_BW399',       'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...          
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230720_NV',   'meas_MID00416_FID09074_G25_SAX_CINE_256_R4ipat_BW399',       'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       

    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV2_AI',         'meas_MID00175_FID08447_G25_4CH_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV2_AI',         'meas_MID00176_FID08448_G25_2CH_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV2_AI',         'meas_MID00177_FID08449_G25_SAX_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV2_AI',         'meas_MID00178_FID08450_G25_2CH_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV2_AI',         'meas_MID00179_FID08451_G25_4CH_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       

    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00076_FID08346_G25_4CH_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00081_FID08351_REPEAT_G25_2CH_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00078_FID08348_G25_SAX_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00079_FID08349_G25_4CH_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00080_FID08350_G25_2CH_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00082_FID08352_G25_SAX_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       

    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00687_FID08077_REPEAT_G25_4CH_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00688_FID08078_REPEAT_G25_2CH_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00689_FID08079_G25_SAX_CINE_256_R4ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00720_FID08107_G25_4CH_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       
    '/export/Lab-Xue/data/mri_raw_data/freemax/20230712_NV_AI',         'meas_MID00723_FID08110_G25_SAX_CINE_256_R3ipat',              'NX',   'Freemax_2DT_RetroCine_STCNNT_SCC.xml',             'res',              'ref',   'wip_070_fire_IsmrmrdParameterMap_Siemens.xsl'   ; ...       

    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
