function UTCases = set_up_UT_cases_ExternalSites;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {    
    'ExternalSites\UCL',  'meas_MID31_t1_nw_mtflash3d_v3e_xpc_FID268',  'VB',   'GT_3DT_Cartesian.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'ExternalSites\UCL',  'meas_MID30_t1_nw_mtflash3d_v3e_xpc_R4_FID267',  'VB',   'GT_3DT_Cartesian.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'ExternalSites\UCL\IceGadgetronMPM_280515',  'meas_MID15_t1_nw_mtflash3d_v3i_FID15572',  'VB',   'GT_3DT_Cartesian.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'ExternalSites\UCL\IceGadgetronMPM_280515',  'meas_MID27_t1_nw_mtflash3d_v3i_FID15584',  'VB',   'GT_3DT_Cartesian.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'ExternalSites\RBH',  'meas_MID00406_FID03502_gre',  'VD',   'GT_2DT_Cartesian.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'ExternalSites\others',  'meas_MID51_IR_gre_gadgetronJS_R3P30S2_interleaved_FID28946',  'VB',   'GT_2DT_Cartesian.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'ExternalSites\Siemens',  'meas_MID00097_FID01263_BEAT_IRTTT_1030',  'VD',   'grappa.xml', 'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
