function UTCases = set_up_UT_cases_Flow;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'RealTimeFlow',               'meas_MID02853_FID26835_realtime_flow',                         'VD',   'GTPrep_2DT_RealTimeFlow.xml',         'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroFlow',                  '20160818_09h36m56s_28440',                                     'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'RetroFlow',                  'meas_MID00238_FID26502_BEAT_FQ_Gadgetron_NIH',                 'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    'RetroFlow',                  'meas_MID00248_FID26512_BEAT_FQ_Gadgetron_NIH',                 'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    'RetroFlow',                  'meas_MID00248_FID26512_BEAT_FQ_Gadgetron_NIH',                 'VD',   'GTPrep_2DT_RetroGated_Flow_L1SPIRIT_SLEP.xml',      'grappa_res',              'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    
    'RetroFlow',                  'meas_MID00938_FID27436_pre_CS_flow_80_rest',                   'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    'RetroFlow',                  'meas_MID00938_FID27436_pre_CS_flow_80_rest',                   'VD',   'GTPrep_2DT_RetroGated_Flow_L1SPIRIT_SLEP.xml',      'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    

    'RetroFlow',                  'meas_MID00940_FID27438_pre_CS_flow_80_rest_test1',             'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    'RetroFlow',                  'meas_MID00940_FID27438_pre_CS_flow_80_rest_test1',             'VD',   'GTPrep_2DT_RetroGated_Flow_L1SPIRIT_SLEP.xml',      'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    
    'ut\NewData\KAROLINSKA\QUARK', 'Retro_NLin_Flow_41672_9583212_9583217_669_20160829-172538',             'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    'ut\NewData\KAROLINSKA\QUARK', 'Retro_NLin_Flow_41672_9583212_9583217_669_20160829-172538',             'VD',   'GTPrep_2DT_RetroGated_Flow_L1SPIRIT_SLEP.xml',      'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    
    'ut\NewData\KAROLINSKA\QUARK', 'Retro_NLin_Flow_41672_9583212_9583217_670_20160829-172655',             'VD',   'GTPrep_2DT_RetroGated_Flow.xml',      'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    'ut\NewData\KAROLINSKA\QUARK', 'Retro_NLin_Flow_41672_9583212_9583217_670_20160829-172655',             'VD',   'GTPrep_2DT_RetroGated_Flow_L1SPIRIT_SLEP.xml',      'slep_res',              'slep_ref',   'IsmrmrdParameterMap_Siemens_Flow.xsl'   ; ...    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
