function UTCases = set_up_UT_cases_SNR_Recon_Test;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    % R=1
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00393_FID114595_R1_PEFOV100_PERes100',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00394_FID114596_R1_PEFOV75_PERes75',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00395_FID114597_R1_PEFOV75_PERes75_PF6_8',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00396_FID114598_R1_PEFOV75_PERes75_PF6_8_AsymStrong',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00397_FID114599_R1_PEFOV75_PERes75_PF6_8_AsymStrong_InterpON',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    % R=2
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00398_FID114600_R2_spat_PEFOV100_PERes100',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00399_FID114601_R2_spat_PEFOV75_PERes75',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00400_FID114602_R2_spat_PEFOV75_PERes75_PF6_8',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00401_FID114603_R2_spat_PEFOV75_PERes75_PF6_8_AsymStrong',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00402_FID114604_R2_spat_PEFOV75_PERes75_PF6_8_AsymStrong_InterpON',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   

    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00403_FID114605_R2_tpat_PEFOV100_PERes100',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00404_FID114606_R2_tpat_PEFOV75_PERes75',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00405_FID114607_R2_tpat_PEFOV75_PERes75_PF6_8',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00406_FID114608_R2_tpat_PEFOV75_PERes75_PF6_8_AsymStrong',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00407_FID114609_R2_tpat_PEFOV75_PERes75_PF6_8_AsymStrong_InterpON',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   

    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00408_FID114610_R2_ipat_PEFOV100_PERes100',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00409_FID114611_R2_ipat_PEFOV75_PERes75',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00410_FID114612_R2_ipat_PEFOV75_PERes75_PF6_8',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00411_FID114613_R2_ipat_PEFOV75_PERes75_PF6_8_AsymStrong',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00412_FID114614_R2_ipat_PEFOV75_PERes75_PF6_8_AsymStrong_InterpON',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    
    % R=3
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00413_FID114615_R3_spat_PEFOV100_PERes100',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00414_FID114616_R3_spat_PEFOV100_PERes75',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00415_FID114617_R3_spat_PEFOV100_PERes75_PF6_8',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00416_FID114618_R3_spat_PEFOV100_PERes75_PF6_8_AsymStrong',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00417_FID114619_R3_spat_PEFOV100_PERes75_PF6_8_AsymStrong_InterpON',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   

    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00418_FID114620_R3_tpat_PEFOV100_PERes100',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00419_FID114621_R3_tpat_PEFOV100_PERes75',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00420_FID114622_R3_tpat_PEFOV100_PERes75_PF6_8',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00421_FID114623_R3_tpat_PEFOV100_PERes75_PF6_8_AsymStrong',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00422_FID114624_R3_tpat_PEFOV100_PERes75_PF6_8_AsymStrong_InterpON',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    
    % phase oversampling
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00423_FID114625_R1_PEFOV100_PERes120',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00424_FID114626_R2_spat__PEFOV100_PERes120',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00425_FID114627_R3_spat__PEFOV100_PERes120',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...      
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00426_FID114628_R2_tpat__PEFOV100_PERes120',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00427_FID114629_R3_tpat__PEFOV100_PERes120',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'SNR_Unit_Recon\SNRUnitTest', 'meas_MID00077_FID115844_R2_ipat_PEFOV75_PERes75_PEOverSampling120',                       'VD',   'GTPrep_2DT_Cartesian_GFactor_Offline.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end

