function UTCases = set_up_UT_cases_SNRDenoising;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {

    % SNR phantom, with different FAs
    'PhantomDatfileSNR/20211217',         'meas_MID01502_FID55179_FLASH_PAT1_n=256_FA15',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/20211217',         'meas_MID01503_FID55180_FLASH_PAT1_n=256_FA10',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/20211217',         'meas_MID01504_FID55181_FLASH_PAT1_n=256_FA5',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/20211217',         'meas_MID01505_FID55182_FLASH_PAT1_n=256_FA3',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/20211217',         'meas_MID01506_FID55183_FLASH_PAT1_n=256_FA2',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/20211217',         'meas_MID01507_FID55184_FLASH_PAT1_n=256_FA1',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % SNR phantom
    'PhantomDatfileSNR/21211208',         'meas_MID03480_FID51667_FLASH_PAT1_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/21211208',         'meas_MID03481_FID51668_FLASH_PAT2_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/21211208',         'meas_MID03482_FID51669_FLASH_PAT3_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR/21211208',         'meas_MID03483_FID51670_FLASH_PAT4_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'PhantomDatfileSNR',         'meas_MID02056_FID47760_FLASH_PAT1_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR',         'meas_MID02055_FID47759_FLASH_PAT2_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR',         'meas_MID02054_FID47758_FLASH_PAT3_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR',         'meas_MID02053_FID47757_FLASH_PAT4_n=256',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'PhantomDatfileSNR',         'meas_MID02051_FID47755_FLASH_PAT5_n=32',         'VD',   'Generic_Cartesian_Grappa_SNR.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'hxue',         'meas_MID00183_FID04448_R3_Retro_NLin_Cine_8ms_Lighthouse',         'VD',   'GTPrep_2DT_RetroCine.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'hxue',         'meas_MID00181_FID04446_R3_RT_Cine_NL_Res192_Lighthouse',         'VD',   'Generic_RTCine.xml',                          'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui/cardiacH5/imagedata',               '20190125_111354_meas_MID01053_FID10359_SAX_BinningCine_R3_192res_cloud',              'VD',   'Generic_RTCine.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui/abdomenH5/imagedata',               '20181206_212807_meas_MID00187_FID00682_t1_vibe_dixon_cor_p4_bh_wip963',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/abdomenH5/imagedata',                  '20181207_154011_meas_MID00065_FID00948_t2_tse_sfs_tra_trig_SkewedSpair',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/abdomenH5/imagedata',               '20190225_224306_meas_MID00094_FID00919_t1_vibe_dixon_tra_p4_bh',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui/brainH5/imagedata',               '20181207_170024_meas_MID00086_FID00969_t1_tse_dark-fluid_sag',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/brainH5/imagedata',               '20181207_170457_meas_MID00088_FID00971_t2_tse_dark-fluid_tra',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/brainH5/imagedata',               '20190225_210928_meas_MID00025_FID00850_t1_mprage_sag_iso_manual_denoising',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/brainH5/imagedata',               '20190225_211519_meas_MID00026_FID00851_t2_dark_fluid_sag_manual_denoising',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui/kneeH5/imagedata',               '20190104_200259_meas_MID00033_FID06439_pd_tse_sag_384',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/kneeH5/imagedata',               '20190104_200942_meas_MID00034_FID06440_t2_tse_tra',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui/spineH5/imagedata',               '20181205_214951_meas_MID00155_FID00270_t2_tse_stir_sag_384_t-spine',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'DataForHui/spineH5/imagedata',               '20181207_181828_meas_MID00150_FID01036_t2_tse_sag_p2',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'DataForHui/cardiacH5/imagedata',               '20190124_140027_meas_MID00846_FID10145_SAX_BinningCine_R3_192res_cloud',              'VD',   'Generic_RTCine_PInterp_N3Fil_ECG_dstore.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'neuro',               'meas_MID00083_FID14721_t1_mprage_1mm_p4_pos50_ACPC_check',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',               'meas_MID00070_FID19833_t2_qtse_tra_PAT4',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',               'meas_MID00069_FID19832_t2_qtse_tra_PAT3',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',               'meas_MID00094_FID14732_t2_spc_sag_1mm_p2X2',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro',               'meas_MID00095_FID14733_t2_spc_sag_1mm_p4X2',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % fruit
    '3D',               'meas_MID00018_FID21689_3D_T1_1mm3',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '3D',               'meas_MID00151_FID15826_t1_mprage_tra_p2_iso_1_0',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % neuro, Barts
    'neuro/Barts',               'meas_MID01518_FID64495_t1_se_ax_5mm',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro/Barts',               'meas_MID01516_FID64493_t1_mprage_tra_p2_iso_pre',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro/Barts',               'meas_MID01512_FID64489_t2_tse_cor_5mm',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro/Barts',               'meas_MID01501_FID64478_t2_tirm_tra_dark_fluid_5mm',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'neuro/Barts',               'meas_MID01522_FID64499_t1_se_cor_5mm_post',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % new LF
    'LowField/NewData',               '20190710_214113_meas_MID00023_FID26062_t1_se_ax_manual_denoising',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField/NewData',               '20190806_174202_meas_MID00032_FID31925_t1_se_tra_manual_denoising',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LowField/NewData',               '20200305_221434_meas_MID00064_FID67033_t2_tse_tra_msma_l-spine',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',             'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
