function UTCases = set_up_UT_cases_GT_IntegrationTest;
% run the gt recon

set_UT_Dir('D')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    
    'GT_UT/data/rtgrappa',                  'acc_data_with_device_2',                                                           'VB',   'grappa_float_cpu.xml',                                 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/data/epi',                       'meas_MID517_nih_ep2d_bold_fa60_FID82077',                                          'VD',   'epi.xml',                                              'res',       'ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'   ; ... 
    'GT_UT/data/epi_ave',                   'meas_MID01349_FID12150_amri_ep2d_bold_96x72x5_R2_16avg_gadgetron',                 'VD',   'Generic_Cartesian_Grappa_EPI_AVE.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens_EPI_FLASHREF.xsl'   ; ... 
    'GT_UT/AdjData',                        'meas_MID00086_FID21493_R1_CoilQA',                                                 'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/AdjData',                        'meas_MID00216_FID119445_Coil_QA',                                                  'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/AdjData/VE11A',                  'meas_MID00060_FID24208_NoiseQA',                                                   'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    
    'GT_UT/data/generic',                   'meas_MID00394_FID114596_R1_PEFOV75_PERes75',                                       'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/data/generic',                   'meas_MID00395_FID114597_R1_PEFOV75_PERes75_PF6_8',                                 'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/data/generic',                   'meas_MID00396_FID114598_R1_PEFOV75_PERes75_PF6_8_AsymStrong',                      'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/data/generic',                   'meas_MID00397_FID114599_R1_PEFOV75_PERes75_PF6_8_AsymStrong_InterpON',             'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ... 
    'GT_UT/data/generic',                   'meas_MID00393_FID114595_R1_PEFOV100_PERes100',                                     'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...     
    'GT_UT/data/generic',                   'meas_MID00423_FID114625_R1_PEFOV100_PERes120',                                     'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...     
    'GT_UT/data/generic',                   'meas_MID00077_FID115844_R2_ipat_PEFOV75_PERes75_PEOverSampling120',                'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...     
    'GT_UT/data/generic',                   'meas_MID00411_FID114613_R2_ipat_PEFOV75_PERes75_PF6_8_AsymStrong',                 'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...         
    'GT_UT/data/generic',                   'meas_MID00424_FID114626_R2_spat__PEFOV100_PERes120',                               'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...             
    'GT_UT/data/generic',                   'meas_MID00399_FID114601_R2_spat_PEFOV75_PERes75',                                  'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...             
    'GT_UT/data/generic',                   'meas_MID00400_FID114602_R2_spat_PEFOV75_PERes75_PF6_8',                            'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                 
    'GT_UT/data/generic',                   'meas_MID00401_FID114603_R2_spat_PEFOV75_PERes75_PF6_8_AsymStrong',                 'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                     
    'GT_UT/data/generic',                   'meas_MID00402_FID114604_R2_spat_PEFOV75_PERes75_PF6_8_AsymStrong_InterpON',        'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00398_FID114600_R2_spat_PEFOV100_PERes100',                                'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00404_FID114606_R2_tpat_PEFOV75_PERes75',                                  'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00405_FID114607_R2_tpat_PEFOV75_PERes75_PF6_8',                            'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00406_FID114608_R2_tpat_PEFOV75_PERes75_PF6_8_AsymStrong',                 'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00403_FID114605_R2_tpat_PEFOV100_PERes100',                                'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00416_FID114618_R3_spat_PEFOV100_PERes75_PF6_8_AsymStrong',                'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00427_FID114629_R3_tpat__PEFOV100_PERes120',                               'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00421_FID114623_R3_tpat_PEFOV100_PERes75_PF6_8_AsymStrong',                'VD',   'Generic_Cartesian_Grappa_SNR.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/T2W',                       'meas_MID00057_T2w',                                                                'VD',   'Generic_Cartesian_Grappa_T2W.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/tse',                       'meas_MID00450_FID76726_SAX_TE62_DIR_TSE',                                          'VD',   'Generic_Cartesian_Grappa.xml',                         'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                         
    'GT_UT/data/generic',                   'meas_MID00062_FID114726_SAX_SASHA',                                                'VB',   'Generic_Cartesian_Spirit_SASHA.xml',                   'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                             
    'GT_UT/data/simple_gre',                'meas_MiniGadgetron_GRE',                                                           'VB',   'default.xml',                                          'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/data/gre_3d',                    'meas_MID248_gre_FID30644',                                                         'VB',   'default_optimized.xml',                                'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 

    'GT_UT/data/generic',                   'meas_MID836_1slice_FID22517',                                                      'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml',  'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                             
    'GT_UT/data/generic',                   'meas_MID01095_FID40115',                                                           'VD',   'Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine.xml',  'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                             
    'GT_UT/data/cmr/CineBinning',           'meas_MID838_PK_rt_test_2slice_FID22519',                                           'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/data/cmr/CineBinning',           'meas_MID00247_FID39104_PK_realtime_gt_TPAT4_6_8',                                  'VD',   'CMR_2DT_RTCine_KspaceBinning.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    
    'GT_UT/gtprep_data/gtprep/B1Mapping',   'meas_MID00272_FID112569_B1MAP_BH_a90_rep30_PAT2',                                  'VD',   'B1mapping.xml',                                        'res',       'ref',   'IsmrmrdParameterMap_Siemens_EPI.xsl'   ; ...                             
    'GT_UT/gtprep_data/gtprep/CineBinning', 'meas_MID836_PK_rt_test_1slice_FID22517',                                           'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                  'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/CineBinning', 'meas_MID838_PK_rt_test_2slice_FID22519',                                           'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                  'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/Nonlinear',   '20140703_11h09m11s_12297',                                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/RetroGating', 'meas_MID00031_FID107666_4CH_fisp_retro_iPAT_256',                                  'VD',   'GTPrep_2DT_RetroGated_Cine.xml',                       'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/RetroGating', 'meas_MID00208_FID115039_SAX_fisp_retro_iPAT_256',                                  'VD',   'GTPrep_2DT_RetroGated_Cine.xml',                       'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/RealTimeFlow','meas_MID00089_FID19207_real_time_flow_R5_30s',                                     'VD',   'GTPrep_2DT_RTFlow_KspaceBinning.xml',                  'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/LGE',         'meas_MID120_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343803',                             'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                          'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/LGE',         'meas_MID01986_FID19364_Sax_RadCV_gtPlus_PSIR_12sl_4ave_MOCO',                      'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/7T',          'meas_MID709_CV_me_Gadgetron_rep20_bw1002_xRes160_nopat_FID50648',                  'VB',   'GTPrep_2DT_Cartesian_GFactor.xml',                     'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/t2star',      'meas_MID00372_FID108007_SAX_gt_T2Star_MOCO_DB_8e',                                 'VD',   'GTPrep_2DT_T2Star_Mapping.xml',                        'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/T2W',         'meas_MID00371_FID108006_SAX_gt_T2w_9sl_8ave_MOCO',                                 'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/T2W',         'meas_MID00123_FID43785_gt_CV_T2w_segmented',                                       'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/perfusion',   'meas_MID00178',                                                                    'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/perfusion',   'meas_MID00126_FID00452_SSFP_Perf_TPAT3_PF34_192x111',                              'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...                                 
    'GT_UT/gtprep_data/gtprep/perfusion',   'Perfusion_AIF_TwoEchoes_Interleaved_R2_66097_1457656_1457661_147_20160705-142053', 'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',                 'res',       'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...                                 
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end


