function UTCases = set_up_UT_cases_SNR_Denoising;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR/21211208',           'meas_MID03480_FID51667_FLASH_PAT1_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR/21211208',           'meas_MID03481_FID51668_FLASH_PAT2_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR/21211208',           'meas_MID03482_FID51669_FLASH_PAT3_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR/21211208',           'meas_MID03483_FID51670_FLASH_PAT4_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02056_FID47760_FLASH_PAT1_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02055_FID47759_FLASH_PAT2_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02054_FID47758_FLASH_PAT3_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02053_FID47757_FLASH_PAT4_n=256',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02046_FID47750_FLASH_PAT1_n=32',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02048_FID47752_FLASH_PAT2_n=32',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02049_FID47753_FLASH_PAT3_n=32',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02050_FID47754_FLASH_PAT4_n=32',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02051_FID47755_FLASH_PAT5_n=32',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    '/export/Lab-Kellman/Share/data/PhantomDatfileSNR',           'meas_MID02052_FID47756_FLASH_PAT6_n=32',        'VD',   'Generic_Cartesian_Grappa_SNR_STCNNT.xml',                              'res',          'res',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

disp('set_up_UT_cases_GtPrep_4px_UT')

if(nargout<=0)
    UTCases = [];
end
