function UTCases = set_up_UT_cases_ImageReviewing;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    % Retro-cine
    'RetroCine',                  'meas_MID00031_FID107666_4CH_fisp_retro_iPAT_256',              'VD',   'GTPrep_2DT_RetroGated_Cine.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroCine',                  'meas_MID00032_FID107667_3CH_fisp_retro_iPAT_256',              'VD',   'GTPrep_2DT_RetroGated_Cine.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroCine',                  'meas_MID00033_FID107668_2CH_fisp_retro_iPAT_256',              'VD',   'GTPrep_2DT_RetroGated_Cine.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroCine',                  'meas_MID00035_FID107670_SAX_fisp_retro_iPAT_256',              'VD',   'GTPrep_2DT_RetroGated_Cine.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'RetroCine',                  'meas_MID00036_FID107671_SAX_fisp_retro_iPAT_256',              'VD',   'GTPrep_2DT_RetroGated_Cine.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

    % RealTimeCine, linear
    'cine',                  'meas_MID00033_FID110002_4ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'meas_MID00035_FID110004_3ch_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'meas_MID00037_FID110006_2ch_realtime_gt_TPAT4_LT',           'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'meas_MID00041_FID110010_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine',                  'meas_MID00043_FID110012_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'cine\RTCine',           'meas_MID00273_FID115649_4CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00275_FID115651_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00277_FID115653_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00280_FID115656_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00282_FID115658_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00284_FID115660_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00286_FID115662_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00288_FID115664_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00290_FID115666_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00292_FID115668_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00294_FID115670_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00296_FID115672_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00298_FID115674_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00300_FID115676_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00302_FID115678_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00304_FID115680_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    'cine\RTCine',           'meas_MID00380_FID114109_4CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00382_FID114111_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00384_FID114113_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00386_FID114115_3CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00388_FID114117_2CH_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00390_FID114119_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00392_FID114121_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00394_FID114123_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00396_FID114125_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00398_FID114127_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00400_FID114129_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00402_FID114131_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00404_FID114133_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00406_FID114135_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00408_FID114137_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00410_FID114139_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00412_FID114141_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    'cine\RTCine',           'meas_MID00414_FID114143_SAX_realtime_gt_TPAT4',              'VD',   'GTPrep_2DT_RealTimeCine_PF_Handling_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
    
    % RealTimeCine, nl
    'cine',                  'meas_MID00157_FID109194_RTCine_NL_Amazon_Cloud_4SLC_Groups',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud',        'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141020_16h11m10s_25740',                                                'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141205_15h37m58s_31798',                                                'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'cine',                  '20141017_10h09m21s_25173',                                                'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp.xml',         'res',              'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'CV_Sparse',             'meas_MID01095_FID40115_PK_CVsparse_rt_net12_0',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'res',            'ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    'CV_Sparse',             'meas_MID01402_FID40422_PK_CVsparse_rt_net12_0',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_IrregularCartesianSampling.xml',  'res',            'ref',   'IsmrmrdParameterMap_Siemens_CV_Sparse.xsl'   ; ...
    
    % Binning Cine
    'binning',                  'meas_MID00322_FID06960_RealTimeCineBinning',                               'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'binning',                  '20160201_10h27m06s_78653',                                                 'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'res',              'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'binning\20150923_StudyLoid_12.0.123557963_CNMC2359-C0832',   '20150923_11h51m34s_62440',               'VD',   'GTPrep_2DT_RTCine_KspaceBinning.xml',                                  'res',            'binning_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    
    % Segmented LGE
    'LGE\AERA_FLASH_segmented_BH_normalization\E07505',         '20150820_09h49m09s_98415',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\AERA_FLASH_segmented_BH_normalization\E07505',         '20150820_09h51m56s_98420',         'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\SUB_Crash',         'meas_MID00129_FID103755_Sax_gt_PSIR_Segm_FLASH',                      'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % MOCO AVE LGE
    'LGE\VB17_20160226',         'meas_MID110_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343793',            'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID111_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343794',            'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID112_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343795',            'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID113_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343796',            'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\VB17_20160226',         'meas_MID114_PSIR_SSFP_MOCO_1sl_8_meas_584K_FID343797',            'VB',   'GTPrep_2DT_LGE_MOCO_AVE.xml',                                      'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\GoodCase_Cyst_A04050',         'meas_MID00354_FID81567_SAX_gt_PSIR_FLASH_9sl_8ave_MOCO',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...

    'LGE\Skyra',         'meas_MID00122_FID115498_gt_PSIR_FLASH_9sl_8ave_MOCO',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00212_FID115588_SAX_gt_PSIR_FLASH_9sl_8ave_MOCO',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00213_FID115589_4CH_gt_PSIR_FLASH_9sl_8ave_MOCO',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00215_FID115591_3CH_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00217_FID115593_2CH_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00218_FID115594_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00219_FID115595_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00220_FID115596_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00221_FID115597_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00222_FID115598_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00223_FID115599_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00225_FID115601_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00227_FID115603_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00228_FID115604_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00229_FID115605_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00230_FID115606_SAX_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\Skyra',         'meas_MID00231_FID115607_3CH_gt_PSIR_Segm_FLASH_PAT2',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'LGE\darkblood',     '20160321_12h41m49s_7112',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\darkblood',     '20160321_12h42m29s_7113',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\darkblood',     '20160321_12h43m28s_7114',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    'LGE\darkblood',     '20160321_12h44m12s_7115',   'VD',   'GTPrep_2DT_LGE_MOCO_AVE_OnTheFly.xml',                             'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % Segmented T2W
    'T2W',         'meas_MID00123_FID43785_gt_CV_T2w_segmented',         'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % MOCO AVE T2W
    'T2W',         'meas_MID00371_FID108006_SAX_gt_T2w_9sl_8ave_MOCO',         'VD',   'GTPrep_2DT_T2W_MOCO_AVE_OnTheFly.xml',                                         'res',            'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % Segmented T2* mapping
    't2star',          '20140530_15h06m05s_18546',                       'VD',   'GTPrep_2DT_T2Star_Mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',          '20150302_11h33m25s_66603',                       'VD',   'GTPrep_2DT_T2Star_Mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    % FB T2* mapping
    'gtprep_data\gtprep\t2star',          'meas_MID00372_FID108007_SAX_gt_T2Star_MOCO_DB_8e',                       'VD',   'GTPrep_2DT_T2Star_Mapping.xml',            'res',           'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
      
    % 3D recon
    '3D',         'meas_MID00828_FID39146_T1_3D_SAG___R2Y',              'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'res',         'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00173_FID08775_head_gre_ipat3x2',             'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'res',         'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00176_FID08778_head_gre_ipat3x3',             'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'res',         'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    '3D',         'meas_MID00351_FID27847_QQQ_Angio3D_Sag_pre',          'VD',   'Generic_Cartesian_Grappa_SNR.xml',                               'res',         'ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   

    % TSE
    'TSE', 'meas_MID00062_FID01994_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00064_FID01996_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00066_FID01998_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00091_FID06424_QQQ_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   

    % knee
    'knee', 'meas_MID00391_FID115767_t1_tirm_sag_320',                       'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'knee', 'meas_MID00393_FID115769_t1_tirm_cor_320',                       'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'knee', 'meas_MID00396_FID115772_t1_tirm_tra_320',                       'VD',   'Generic_Cartesian_Grappa.xml',  'res',  'ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    
    % Perfusion
    'DualBolus\SSFP\20160114_A04207_4ml\rest',  'meas_MID00165_FID102574_BIG__05_REST_SSFP_PERF_TPAT3_PF3_4_192x111',       'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'res',          'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',   'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'res',          'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\NewData\SUB_1p5T\20160208_E07814\stress',  'E07814_20160208_10h46m40s_7857',                                 'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'res',          'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...        

    'DualBolus\FFR\20160314_A04294_2ml\FFR3',  'meas_MID00100_FID114764_FFR3_BIG_BOLUS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'res',          'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end

