function UTCases = set_up_UT_cases_TSE;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    'TSE', 'meas_MID00052_FID01984_QQQ_SAX_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00054_FID01986_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00056_FID01988_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00058_FID01990_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00060_FID01992_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00062_FID01994_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00064_FID01996_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00066_FID01998_QQQ_SAX_TE60_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00091_FID06424_QQQ_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00093_FID06426_QQQ_4CH_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00208_FID108659_4CH_TE62_SPAIR_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00260_FID109465_AX_TE62_SPAIR_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00264_FID03478_QQQ_AOV_SPAIR_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00445_FID76721_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00446_FID76722_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00447_FID76723_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00448_FID76724_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00449_FID76725_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00450_FID76726_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00452_FID76728_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
    'TSE', 'meas_MID00454_FID76730_SAX_TE62_DIR_TSE',  'VD',   'Generic_Cartesian_Grappa.xml',  'grappa_res',  'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'  ; ...   
   };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
