function UTCases = set_up_UT_cases_Perfusion;
% run the gt recon

% set_UT_Dir('E')

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {   
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_ismrmrd_storage_SavedISMRMRD_localhost.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perf_AIF_2E_Linear_Mapping_FIL_MBF_MBV_Mask_ismrmrd_storage.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Offline.xml',          'grappa_flow_res_cx',          'grappa_flow_ref_cx',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...   
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...    
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00293_FID42018_SSFP_PERFUSION_GADGETRON_AIF2eTPAT_1slc_96res',      'VD',   'GTPrep_2DT_Perfusion_AIF_MocoProgressive.xml',          'progressive',          'progressive_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'PerfusionUT',  'meas_MID00023_FID62532_R4_2SLC_96Res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Offline.xml',          'grappa_flow_res_cx',          'grappa_flow_ref_cx',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'PerfusionUT',  'meas_MID00023_FID62532_R4_2SLC_96Res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...    
    'PerfusionUT',  'meas_MID00023_FID62532_R4_2SLC_96Res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'PerfusionUT',  'meas_MID00026_FID62535_R4_2SLC_96Res_60REP_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Offline.xml',          'grappa_flow_res_cx',          'grappa_flow_ref_cx',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'PerfusionUT',  'meas_MID00026_FID62535_R4_2SLC_96Res_60REP_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...    
    'PerfusionUT',  'meas_MID00026_FID62535_R4_2SLC_96Res_60REP_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'slep_flow_res',          'slep_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_cloud_flow_res',          'slep_cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\highTemporal',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_cloud_flow_res2',          'slep_cloud_flow_ref2',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\CardiacPhases',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\CardiacPhases',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'slep_flow_res',          'slep_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\CardiacPhases',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear_Gateway.xml',          'slep_cloud_flow_res',          'slep_cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...

    'SUB_Perf',  'meas_MID00329_FID59479_PK_256by144_high_spatial_res_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'FLASH_Perfusion_HighRes',  'meas_MID00116_FID36155_FULL_STRESS_FLASH_Perf_TPAT3_AIF_PF3_4',      'VD',   'GTPrep_2DT_Perfusion_AIF.xml',          'grappa_res',          'grappa_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'FLASH_Perfusion_HighRes',  'meas_MID00116_FID36155_FULL_STRESS_FLASH_Perf_TPAT3_AIF_PF3_4',      'VD',   'GTPrep_2DT_Perfusion_AIF_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'FLASH_Perfusion_HighRes',  'meas_MID00155_FID37490_1sl_128RO_12rep_FLASH_PERFUSION_GADGETRON',      'VD',   'GTPrep_2DT_Perfusion_AIF_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'MOCO_EVALUATION\SUB\SUB_SSFP',  '20150519_10h41m05s_81722',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\TwoConc',  'meas_MID00027_FID65792_40ms_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2.xml',          'grappa_res',          'grappa_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\TwoConc',  'meas_MID00027_FID65792_40ms_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\TwoConc',  'meas_MID00031_FID65796_40ms_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00021_FID68459_40ms_8_sl_2conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00022_FID68460_40ms_4_sl_1conc_RES_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00255_FID68693_1_conc_40ms_Trigger4_1_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00252_FID68690_1_conc_40ms_1_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00251_FID68689_1_conc_40ms_3_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID00250_FID68688_2_conc_40ms_6_sl_FLASH_PER_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00033_FID68886_CV_epi_DS_AIF_810_snv_pk',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'SUB_Perf\WIP_GT_COMPARISON',  '20150810_11h30m44s_95892',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'SUB_Perf\WIP_GT_COMPARISON',  '20150810_11h32m37s_95893',      'VD',   'GTPrep_2DT_Perfusion_AIF.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'SUB_Perf\WIP_GT_COMPARISON',  '20150810_11h35m30s_95895',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'SUB_Perf\WIP_GT_COMPARISON',  '20150810_11h35m45s_95896',      'VD',   'GTPrep_2DT_Perfusion_AIF.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'SUB_Perf\werid_aif',  'meas_MID00333_FID96062_Rest_Perf_SSFP_GT_TPAT3_PFon_FS_on',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'SUB_Perf\LOW_EF_CASE\20150812\stress',  '20150812_09h12m51s_96225',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'SUB_Perf\LOW_EF_CASE\20150812\rest',  '20150812_09h33m57s_96247',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\slowPerf',  'meas_MID00235_FID70703_4CH_SLOW_FLASH_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'Perf',  '20140408_13h17m13s_10066',      'VD',   'GTPrep_2DT_Perfusion_AIF_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\SSFP\20151013_A04076_4ml\stress',  'meas_MID00189_FID84454_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\SSFP\20151013_A04076_4ml\stress',  'meas_MID00189_FID84454_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Gateway.xml',  'grappa_cloud_flow_res',    'grappa_cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID00053_FID03397_CV_epi_DS_AIF_810',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\FLASH\20151217_A04169_4ml_s\stress',  'meas_MID00331_FID98161_BIG__075_STRESS_FLASH_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\FLASH\20151217_A04169_4ml_s\stress',  'meas_MID00331_FID98161_BIG__075_STRESS_FLASH_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_Gateway.xml',  'grappa_cloud_flow_res',    'grappa_cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion\mrxcat2ismrmrd_3dPerf',  'mrxcat2ismrmrd_3dPerf',      'VB',   'GTPrep_2DT_Perfusion.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\Test',  'meas_MID00053_FID103858_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\FFR\20160201_A04221_2ml\FFR3',  'meas_MID00265_FID104919_FFR3_BIG__05_REST_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\FFR\20160201_A04221_2ml\FFR4',  'meas_MID00298_FID104952_FFR4_BIG__05_REST_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\FFR\20160111_A04189_2ml\FFR2',  'meas_MID00076_FID101683_FFR2_BIG__05__SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'DualBolus\FFR\20160111_A04189_2ml\FFR2',  'meas_MID00076_FID101683_FFR2_BIG__05__SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_ismrmrd_storage.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'DualBolus\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_NonLinear.xml',          'nl_flow_res',          'nl_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'ut\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'ut\SSFP\20160114_A04207_4ml\rest',  'meas_MID00165_FID102574_BIG__05_REST_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping.xml',          'grappa_flow_res',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'ut\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Interleaved_R2_QuantitativeFlow_Mapping_ismrmrd_storage.xml',          'grappa_flow_res2',          'grappa_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'ut\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_FullFOV.xml',          'fov_flow_res2',          'fov_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'ut\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask_Gateway.xml',          'cloud_flow_res',          'cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'ut\SSFP\20160114_A04207_4ml\stress',  'meas_MID00125_FID102534_BIG__05_STRESS_SSFP_PERF_TPAT3_PF3_4_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_GdPhantom.xml',          'cloud_flow_res',          'cloud_flow_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'UVA',  'meas_MID00786_FID15265_TurboFLASH_Perfusion_STRESS_160mat_TPAT_BIR4512_TEST',      'VD',   'GTPrep_2DT_Perfusion_AIF.xml',          'grappa',          'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    'ut\GdPhantom_20161015\raw\FLASH_RR4',  'meas_MID00324_FID30940_flash_ti85_rr4',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_GdPhantom.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'ut\NewData\RoyalFree\Perfusion',  'meas_MID00126_FID00452_SSFP_Perf_TPAT3_PF34_192x111',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID02794_FID16475_stressSSFP_Perf_TPAT3_PF34_192x111_new',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion',  'meas_MID01377_FID10259_SSFP_Perf_Half_Dose_Stress',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion',  'meas_MID01381_FID10263_SSFP_Perf_Half_Dose_Rest',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion\FAILED',  'meas_MID00758_FID23598_STRESS_SSFP_Perf_TPAT3_PF34_192x111_new',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_MBF_MBV_Mask.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\FAILED',  'meas_MID00761_FID23601_REST_SSFP_Perf_TPAT3_PF34_192x111_new',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_ismrmrd_storage_SavedISMRMRD_localhost.xml',          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_MBF_MBV_Mask.xml',                          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_NonLinear_Mapping_Mask.xml',                               'nl_res',           'nl_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_MBF_MBV_Mask_ismrmrd_storage.xml',          'all_res2',         'all_ref2',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_NonLinear_Mapping_Mask_Gateway.xml',                       'cloud_res',        'cloud_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask_Gateway.xml',                       'cloud_res',        'cloud_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_Mask_Gateway.xml',                       'cloud_res2',        'cloud_ref2',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...

    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_ismrmrd_storage_SavedISMRMRD_localhost.xml',          'all_res3',         'all_ref3',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_383_20170328-161334',      'VD',   'GTPrep_2DT_Perf_AIF_2E_Linear_Mapping_FIL_MBF_MBV_Mask_ismrmrd_storage.xml',          'all_res3',         'all_ref3',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'perfusion\Barts',  'Perfusion_AIF_TwoEchoes_Interleaved_R2_42110_268079274_268079283_384_20170328-161843',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_MBF_MBV_Mask.xml',                          'all_res',          'all_ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    
    'ut\NewData\SUB_Others',  'meas_MID00386_FID58605_SLOW_PK_TEST_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VD',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_ismrmrd_storage_SavedISMRMRD_localhost.xml',          'res',          'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...
    'ut\NewData\SUB_Others',  'meas_MID00064_FID61725_dose_0_1_2ml_s_FLASH_PERFUSION_GT_AIF2eTPAT2',      'VB',   'GTPrep_2DT_Perfusion_AIF_TwoEchoes_Linear_Mapping_ismrmrd_storage_SavedISMRMRD_localhost.xml',          'res',          'ref',   'IsmrmrdParameterMap_Siemens_Perfusion.xsl'   ; ...

};

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end
