function UTCases = set_up_UT_cases_Cloud;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = { 'cloud',                  'meas_MID00832_FID37686_PK_realtime_tfi_9slice_tpat5_724',          'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...          
            % 160 * 120, R5
            'cloud',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cloud',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cloud',                  'meas_MID01151_FID12395_CV_GT_RealTimeCine_NonLinear_Amazon_Cloud', 'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
            % 192*144, R5, 9 slice cine
            'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_CoilMap_DualLayer_Gateway.xml',  'slep_coil_map_cloud_res', 'slep_coil_map_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  '20141211_14h40m45s_32438',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_amazon_cloud_res', 'slep_amazon_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cloud',                 '20141211_14h40m45s_32438',                                         'VD',   'Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml',  'nl_spirit_cloud_res', 'nl_spirit_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  'meas_MID00084_FID107719_gtRealTimeCineNonLinear',                  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID00084_FID107719_gtRealTimeCineNonLinear',                  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_amazon_cloud_res', 'slep_amazon_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % binning, 192*144, 16s data
            'cloud',                 'meas_MID01145_FID12389_RealTimeCine_KSpaceBinning_Amazon_cloud',      'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cloud',                 'meas_MID01145_FID12389_RealTimeCine_KSpaceBinning_Amazon_cloud',      'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway_Amazon_Cloud.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...            
            'cloud',                 'meas_MID01145_FID12389_RealTimeCine_KSpaceBinning_Amazon_cloud',      'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',             'binning_cloud_res', 'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...            

            % binning,
            'binning',                  '20140725_09h39m20s_15118',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  '20140808_10h43m11s_16687',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  '20140808_10h46m55s_16688',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140808_10h47m38s_16690',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning',                  '20140811_08h51m42s_16829',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140811_08h55m30s_16830',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20140929_11h31m06s_22550',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20141106_17h11m02s_28066',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20150515_12h47m26s_48845',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20150528_09h15m14s_49725',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  '20150702_10h47m29s_54199',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...               
            'binning',                  '20160608_14h42m27s_18305',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...               
            'binning',                  '20160307_11h13m09s_4537',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h09m53s_62222',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\20150921_StudyLoid_12.0.122624046_CNMC2359-C0830',                  '20150921_11h39m35s_62241',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\20150923_StudyLoid_12.0.123557963_CNMC2359-C0832',                  '20150923_11h51m34s_62440',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  'meas_MID00324_FID06962_RTCineBinning_Res256',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            'binning\Segmented_binning','20140801_13h20m17s_16046',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140804_10h49m30s_16197',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140805_09h41m08s_16314',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140806_15h11m46s_16546',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140811_08h51m42s_16829',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140813_08h44m36s_17059',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140815_09h08m39s_17649',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140815_11h43m47s_17744',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140819_09h59m51s_18072',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140820_11h27m29s_18236',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140822_10h39m46s_18655',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140822_11h57m58s_18706',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140828_09h31m25s_19205',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning\Segmented_binning','20140828_11h16m18s_19268',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  'meas_MID00186_FID12170_PK792_binning_192_128_SAX',     'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    

            
            % real time, 
            'cine',                  'meas_MID00070_FID36924_PK_realtime_tfi_9slice_tpat6_724',           'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',         'slep_cloud_res',              'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID00138_FID106371_gtRealTimeCineNonLinear_9slc',              'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',         'slep_cloud_res',              'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'cine',                  '20151230_16h17m26s_75567',                                         'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',  'slep_cloud_res', 'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            % Pig FFR data, 20160222_A04259_2ml, good quality 
            'cine',                  'meas_MID00157_FID109194_RTCine_NL_Amazon_Cloud_4SLC_Groups',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway.xml',         'slep_cloud_res',              'slep_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            'cine',                  'meas_MID00157_FID109194_RTCine_NL_Amazon_Cloud_4SLC_Groups',  'VD',   'GTPrep_2DT_RTCine_L1SPIRIT_SLEP_PhysioInterp_DualLayer_Gateway_Amazon_Cloud.xml',  'slep_amazon_cloud_res', 'slep_amazon_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
            
            'binning',               '20160201_10h27m06s_78653',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',               '20160201_10h27m06s_78653',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'generic_cloud_res',              'generic_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            % test
            'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            'binning',                  'meas_MID836_PK_rt_test_1slice_FID22517',              'VD',   'GTPrep_2DT_RTCine_KspaceBinning_SingleLayer_Gateway.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            'binning',                  'meas_MID838_PK_rt_test_2slice_FID22519',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            % debug, 20160622
            'binning',                  'meas_MID00094_FID20352_SAX_RT_Binning_8sec_Lighthouse_(Baseline)', 'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',         'binning_cloud_res',              'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...    
            
            % debug, 20160715
            'binning\CNMC_20160715',   'meas_MID00062_FID23728_SAX_R3_RT_Binning_256_CLOUD_9sl',              'VD',   'CMR_2DT_RTCine_KspaceBinning_Cloud.xml',                                  'binning_cloud_res',            'binning_cloud_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...   
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];
end
