function UTCases = set_up_UT_cases_T2StarMapping;
% run the gt recon

% sub folder, data name, VB or VD, config xml file, result_folder, ground-truth folder
UTCases = {
    't2star',                '20140530_15h08m15s_18550',                                'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star\VB17',           'meas_MID42_CV_me_584_T2Star_FID2535',                     'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',           'meas_MID45_CV_me_584K_DB_FB_160_FID123521',               'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',           'meas_MID198_CV_me_584Z_DB_BH_256_FID140066',              'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star\VB17',           'meas_MID285_CV_me_584Z_DB_BH_256_FS_FID140153',           'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',           'meas_MID286_CV_me_584Z_DB_BH_128_FS_FID140154',           'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',           'meas_MID287_CV_me_584Z_DB_FB_160_FS_FID140155',           'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star\VB17',           'meas_MID288_CV_me_584Z_DB_FB_128_FS_FID140156',           'VB',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star\VE11A',          'meas_MID00277_FID64942_BH_gt_T2star_DB_8e_256',           'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    
    't2star',                '20140609_10h40m42s_20069',                                'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                'meas_MID02074_FID72649_Gadgetron_T2Star_BH_DB_8e',        'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                '20140530_15h06m05s_18546',                                'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    't2star',                'meas_MID00594_FID41000_Gadgetron_T2Star_MOCO_DB_8e',      'VD',               'GTPrep_2DT_T2Star_Mapping.xml',                                                  'grappa_res',            'grappa_ref',   'IsmrmrdParameterMap_Siemens.xsl'   ; ...
    };

N = size(UTCases, 1);

for i=1:N
    disp([num2str(i) '  -  ' UTCases{i, 1} '         -          ' UTCases{i, 2} ' - ' UTCases{i, 3} ' - ' UTCases{i, 4}]);
end

if(nargout<=0)
    UTCases = [];

end
