function varargout = imuithreshold(varargin)

if nargin == 0
	p1 = struct( ...
		'Name',					'Threshold', ...
		'Style',				'integer', ...
		'DefaultValue',			127, ...
		'Max',					255, ...
		'Min',					0, ...
		'LargeStep',			10, ...
		'SmallStep',			1);
	p2 = struct( ...
		'Name',					'Convert to binary image', ...
		'Style',				'check', ...
		'DefaultValue',			0);
	P = struct( ...
		'FilterName',			'Threshold', ...
		'AvailableImageType',	[0 0 0 1 1], ...
		'Class',				'', ...
		'ParameterNumber',		2, ...
		'Parameters', 			{ {p1, p2} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	LTB = [zeros(1, FUNPARA{1}), ones(1, 255 - FUNPARA{1})];
	if isrgb(CX)
		CX = grayxform(rgb2gray(CX), LTB);
		CX = cat(3, CX, CX, CX);
	else
		CX = grayxform(CX, LTB);
	end
	if FUNPARA{2}
		varargout{1} = im2bw(CX);
	else
		varargout{1} = CX;
	end
end