
function cine_sax_seg_report_barts_apply_NN_on_images(dataDir, endo_model, epi_model, lax_model, aiDir, use_1mm)
% cine_sax_seg_report_barts_apply_NN_on_images(dataDir, endo_model, epi_model, lax_model, aiDir)

if(nargin<5)
    aiDir = dataDir;
end
if(nargin<6)
    use_1mm = 1;
end    

if(use_1mm==0)    
    command = ['gadgetron_cine_seg_reporting_barts ' ... 
        ' --endo_model_file ' endo_model ... 
        ' --epi_model_file ' epi_model ... 
        ' --lax_model_file ' lax_model ... 
        ...
        ' --sax_image ' fullfile(dataDir, 'I_sax') ... 
        ' --ch2_image ' fullfile(dataDir, 'I_2ch') ... 
        ' --ch4_image ' fullfile(dataDir, 'I_4ch') ... 
        ...
        ' --ch2_image_position ' fullfile(dataDir, 'ch2_ImagePosition') ... 
        ' --ch2_image_orientation ' fullfile(dataDir, 'ch2_ImageOrientation') ... 
        ' --ch2_pixel_spacing ' fullfile(dataDir, 'ch2_pixel_spacing') ... 
        ...
        ' --ch4_image_position ' fullfile(dataDir, 'ch4_ImagePosition') ... 
        ' --ch4_image_orientation ' fullfile(dataDir, 'ch4_ImageOrientation') ... 
        ' --ch4_pixel_spacing ' fullfile(dataDir, 'ch4_pixel_spacing') ... 
        ...
        ' --sax_image_position ' fullfile(dataDir, 'sax_ImagePosition') ... 
        ' --sax_image_orientation ' fullfile(dataDir, 'sax_ImageOrientation') ... 
        ' --sax_pixel_spacing ' fullfile(dataDir, 'sax_pixel_spacing') ... 
        ...
        ' --sax_endo_mask ' fullfile(aiDir, 'sax_endo_mask') ...
        ' --sax_epi_mask ' fullfile(aiDir, 'sax_epi_mask') ...
        ' --sax_endo_contour ' fullfile(aiDir, 'sax_endo_contour') ...
        ' --sax_epi_contour ' fullfile(aiDir, 'sax_epi_contour') ...
        ' --ch2_pts ' fullfile(aiDir, 'ch2_pts') ...
        ' --ch4_pts ' fullfile(aiDir, 'ch4_pts') ...
        ' --metrics ' fullfile(aiDir, 'metrics') ...
        ];
    command
    dos(command);
elseif (use_1mm==1)
    command = ['gadgetron_cine_seg_reporting_barts ' ... 
        ' --endo_model_file ' endo_model ... 
        ' --epi_model_file ' epi_model ... 
        ' --lax_model_file ' lax_model ... 
        ...
        ' --sax_image ' fullfile(dataDir, 'I_sax_1mm') ... 
        ' --ch2_image ' fullfile(dataDir, 'I_2ch_1mm') ... 
        ' --ch4_image ' fullfile(dataDir, 'I_4ch_1mm') ... 
        ...
        ' --ch2_image_position ' fullfile(dataDir, 'ch2_ImagePosition') ... 
        ' --ch2_image_orientation ' fullfile(dataDir, 'ch2_ImageOrientation') ... 
        ' --ch2_pixel_spacing ' fullfile(dataDir, 'ch2_1mm_pixel_spacing') ... 
        ...
        ' --ch4_image_position ' fullfile(dataDir, 'ch4_ImagePosition') ... 
        ' --ch4_image_orientation ' fullfile(dataDir, 'ch4_ImageOrientation') ... 
        ' --ch4_pixel_spacing ' fullfile(dataDir, 'ch4_1mm_pixel_spacing') ... 
        ...
        ' --sax_image_position ' fullfile(dataDir, 'sax_ImagePosition') ... 
        ' --sax_image_orientation ' fullfile(dataDir, 'sax_ImageOrientation') ... 
        ' --sax_pixel_spacing ' fullfile(dataDir, 'sax_1mm_pixel_spacing') ... 
        ...
        ' --sax_endo_mask ' fullfile(aiDir, 'sax_endo_mask_1mm') ...
        ' --sax_epi_mask ' fullfile(aiDir, 'sax_epi_mask_1mm') ...
        ' --sax_endo_contour ' fullfile(aiDir, 'sax_endo_contour_1mm') ...
        ' --sax_epi_contour ' fullfile(aiDir, 'sax_epi_contour_1mm') ...
        ' --ch2_pts ' fullfile(aiDir, 'ch2_pts_1mm') ...
        ' --ch4_pts ' fullfile(aiDir, 'ch4_pts_1mm') ...
        ' --metrics ' fullfile(aiDir, 'metrics_1mm') ...
        ];
    command
    dos(command);
elseif (use_1mm==2)
    command = ['gadgetron_cine_seg_reporting_barts ' ... 
        ' --endo_model_file ' endo_model ... 
        ' --epi_model_file ' epi_model ... 
        ' --lax_model_file ' lax_model ... 
        ...
        ' --sax_image ' fullfile(dataDir, 'I_sax_1mm') ... 
        ' --ch2_image ' fullfile(dataDir, 'I_2ch_1mm') ... 
        ' --ch4_image ' fullfile(dataDir, 'I_4ch_1mm') ... 
        ...
        ' --ch2_image_position ' fullfile(dataDir, 'ch2_ImagePosition') ... 
        ' --ch2_image_orientation ' fullfile(dataDir, 'ch2_ImageOrientation') ... 
        ' --ch2_pixel_spacing ' fullfile(dataDir, 'ch2_pixel_spacing_highres') ... 
        ...
        ' --ch4_image_position ' fullfile(dataDir, 'ch4_ImagePosition') ... 
        ' --ch4_image_orientation ' fullfile(dataDir, 'ch4_ImageOrientation') ... 
        ' --ch4_pixel_spacing ' fullfile(dataDir, 'ch4_pixel_spacing_highres') ... 
        ...
        ' --sax_image_position ' fullfile(dataDir, 'sax_ImagePosition') ... 
        ' --sax_image_orientation ' fullfile(dataDir, 'sax_ImageOrientation') ... 
        ' --sax_pixel_spacing ' fullfile(dataDir, 'sax_pixel_spacing_highres') ... 
        ...
        ' --sax_endo_mask ' fullfile(aiDir, 'sax_endo_mask_1mm') ...
        ' --sax_epi_mask ' fullfile(aiDir, 'sax_epi_mask_1mm') ...
        ' --sax_endo_contour ' fullfile(aiDir, 'sax_endo_contour_1mm') ...
        ' --sax_epi_contour ' fullfile(aiDir, 'sax_epi_contour_1mm') ...
        ' --ch2_pts ' fullfile(aiDir, 'ch2_pts_1mm') ...
        ' --ch4_pts ' fullfile(aiDir, 'ch4_pts_1mm') ...
        ' --metrics ' fullfile(aiDir, 'metrics_1mm') ...
        ];
    command
    dos(command);
end
