
function GeneratePerfusionPhantom(dxcat2Dir, ParFile, FreeBreathingFlag, LV_BloodPool, RV_BloodPool, LV_Myocardium, RV_Myocardium, Artery, Lung, ... 
    out_period, time_per_frame, out_frames, outputPrefix, breathingPhase, resp_period, max_diaphragm_motion, plotFlag, bathFile, numOfBatches)

if ( plotFlag )
    figure
    hold on
    plot(LV_BloodPool, 'r');
    plot(RV_BloodPool, 'b');
    plot(LV_Myocardium, 'k');
    plot(RV_Myocardium, 'k');
    plot(Artery, 'k');
    plot(Lung, 'k');
    hold off
end

N = numel(LV_BloodPool);

if ( isempty(bathFile) )

    cd(dxcat2Dir)

    for n=1:N
        n
        
        if ( FreeBreathingFlag )
            command = ['dxcat2 ' ParFile '  --out_period ' num2str(out_period) ' --time_per_frame ' num2str(time_per_frame) ' --out_frames ' num2str(out_frames) ...
                ' --myoLV_act ' num2str(LV_Myocardium(n)) ...
                ' --myoRV_act ' num2str(RV_Myocardium(n)) ' ' ...
                ' --myoLA_act ' num2str(LV_Myocardium(n)) ' ' ...
                ' --myoRA_act ' num2str(RV_Myocardium(n)) ' ' ...
                ' --bldplLV_act ' num2str(LV_BloodPool(n)) ' ' ...
                ' --bldplRV_act ' num2str(RV_BloodPool(n)) ' ' ...
                ' --bldplLA_act ' num2str(LV_BloodPool(n)) ' ' ...
                ' --bldplRA_act ' num2str(RV_BloodPool(n)) ' ' ...
                ' --r_lung_activity ' num2str(Lung(n)) ' ' ...
                ' --l_lung_activity ' num2str(Lung(n)) ' ' ...
                ' --art_activity ' num2str(Artery(n)) ' ' ...
                ' --vein_activity ' num2str(RV_BloodPool(n)) ' ' ...
                ' --resp_period ' num2str(resp_period) ' ' ...
                ' --max_diaphragm_motion ' num2str(max_diaphragm_motion) ' ' ...
                ' --resp_start_ph_index ' num2str(breathingPhase(n)) ' ' ...
                ' --motion_option 1 ' ...
                outputPrefix num2str(n)]            
        else
            command = ['dxcat2 ' ParFile '  --out_period ' num2str(out_period) ' --time_per_frame ' num2str(time_per_frame) ' --out_frames ' num2str(out_frames) ...
                ' --myoLV_act ' num2str(LV_Myocardium(n)) ...
                ' --myoRV_act ' num2str(RV_Myocardium(n)) ' ' ...
                ' --myoLA_act ' num2str(LV_Myocardium(n)) ' ' ...
                ' --myoRA_act ' num2str(RV_Myocardium(n)) ' ' ...
                ' --bldplLV_act ' num2str(LV_BloodPool(n)) ' ' ...
                ' --bldplRV_act ' num2str(RV_BloodPool(n)) ' ' ...
                ' --bldplLA_act ' num2str(LV_BloodPool(n)) ' ' ...
                ' --bldplRA_act ' num2str(RV_BloodPool(n)) ' ' ...
                ' --r_lung_activity ' num2str(Lung(n)) ' ' ...
                ' --l_lung_activity ' num2str(Lung(n)) ' ' ...
                ' --art_activity ' num2str(Artery(n)) ' ' ...
                ' --vein_activity ' num2str(RV_BloodPool(n)) ' ' ...
                ' --motion_option 0 ' ...
                outputPrefix num2str(n)]
        end
        
        dos(command, '-echo');    
    end

else
    
    numOfCommand = floor(N/numOfBatches);
    [path, name, ext] = fileparts(bathFile);
    
    for i=1:numOfBatches
        
        startInd = (i-1)*numOfCommand + 1;
        endInd = i*numOfCommand;        
        if ( i == numOfBatches )
            endInd = N;
        end
        
        BatchName = fullfile(path, [name '_' num2str(i) ext]);
        fid = fopen(BatchName, 'w');
        
        command = ['cd ' dxcat2Dir];
        fprintf(fid, '%s\n\n', command);
        
        for n=startInd:endInd
            
            if ( FreeBreathingFlag )
                command = ['dxcat2 ' ParFile '  --out_period ' num2str(out_period) ' --time_per_frame ' num2str(time_per_frame) ' --out_frames ' num2str(out_frames) ...
                    ' --myoLV_act ' num2str(LV_Myocardium(n)) ...
                    ' --myoRV_act ' num2str(RV_Myocardium(n)) ' ' ...
                    ' --myoLA_act ' num2str(LV_Myocardium(n)) ' ' ...
                    ' --myoRA_act ' num2str(RV_Myocardium(n)) ' ' ...
                    ' --bldplLV_act ' num2str(LV_BloodPool(n)) ' ' ...
                    ' --bldplRV_act ' num2str(RV_BloodPool(n)) ' ' ...
                    ' --bldplLA_act ' num2str(LV_BloodPool(n)) ' ' ...
                    ' --bldplRA_act ' num2str(RV_BloodPool(n)) ' ' ...
                    ' --r_lung_activity ' num2str(Lung(n)) ' ' ...
                    ' --l_lung_activity ' num2str(Lung(n)) ' ' ...
                    ' --art_activity ' num2str(Artery(n)) ' ' ...
                    ' --vein_activity ' num2str(RV_BloodPool(n)) ' ' ...
                    ' --resp_period ' num2str(resp_period) ' ' ...
                    ' --max_diaphragm_motion ' num2str(max_diaphragm_motion) ' ' ...
                    ' --resp_start_ph_index ' num2str(breathingPhase(n)) ' ' ...
                    ' --motion_option 1 ' ...
                    outputPrefix num2str(n)]            
            else
                command = ['dxcat2 ' ParFile '  --out_period ' num2str(out_period) ' --time_per_frame ' num2str(time_per_frame) ' --out_frames ' num2str(out_frames) ...
                    ' --myoLV_act ' num2str(LV_Myocardium(n)) ...
                    ' --myoRV_act ' num2str(RV_Myocardium(n)) ' ' ...
                    ' --myoLA_act ' num2str(LV_Myocardium(n)) ' ' ...
                    ' --myoRA_act ' num2str(RV_Myocardium(n)) ' ' ...
                    ' --bldplLV_act ' num2str(LV_BloodPool(n)) ' ' ...
                    ' --bldplRV_act ' num2str(RV_BloodPool(n)) ' ' ...
                    ' --bldplLA_act ' num2str(LV_BloodPool(n)) ' ' ...
                    ' --bldplRA_act ' num2str(RV_BloodPool(n)) ' ' ...
                    ' --r_lung_activity ' num2str(Lung(n)) ' ' ...
                    ' --l_lung_activity ' num2str(Lung(n)) ' ' ...
                    ' --art_activity ' num2str(Artery(n)) ' ' ...
                    ' --vein_activity ' num2str(RV_BloodPool(n)) ' ' ...
                    ' --motion_option 0 ' ...
                    outputPrefix num2str(n)]
            end
            
            fprintf(fid, '%s\n\n', command);
        end
        fclose(fid);
        
        dos([BatchName, ' &']);
    end
end
