function varargout = filter_median(varargin)

if nargin == 0
	p1 = struct( ...
		'Name',					'Radius (in pixel)', ...
		'Style',				'integer', ...
		'DefaultValue',			3, ...
		'Max',					64, ...
		'Min',					2, ...
		'LargeStep',			8, ...
		'SmallStep',			1);
	P = struct( ...
		'FilterName',			'Median', ...
		'Class',				'noise', ...
		'AvailableImageType',	[0 0 0 1 1], ...
		'ParameterNumber',		1, ...
		'Parameters', 			{ {p1} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	if isrgb(CX)
		varargout{1} = cat(3, ...
			medfilt2(CX(:, :, 1), [FUNPARA{1}, FUNPARA{1}]), ...
			medfilt2(CX(:, :, 2), [FUNPARA{1}, FUNPARA{1}]), ...
			medfilt2(CX(:, :, 3), [FUNPARA{1}, FUNPARA{1}]) );
	else
		varargout{1} = medfilt2(CX, [FUNPARA{1}, FUNPARA{1}]);
	end
end