function varargout = filter_bwareaopen(varargin)


if nargin == 0
	p1 = struct( ...
		'Name',					'Object size (in pixel)', ...
		'Style',				'integer', ...
		'DefaultValue',			8, ...
		'Max',					128, ...
		'Min',					1, ...
		'LargeStep',			10, ...
		'SmallStep',			1);
	p2 = struct( ...
		'Name',					'Connectivity', ...
		'Style',				'popup', ...
		'DefaultValue',			2, ...
		'Items',				{ {'4 connected neighborhood', '8 connected neighborhood'} } );
	P = struct( ...
		'FilterName',			'Binary area open', ...
		'AvailableImageType',	[0 1 0 0 0], ...
		'Class',				'morphological', ...
		'ParameterNumber',		2, ...
		'Parameters', 			{ { p1, p2} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	varargout{1} = bwareaopen(CX, FUNPARA{1}, FUNPARA{2} * 4);
end