function varargout = filter_gaussianblur(varargin)

if nargin == 0
	p1 = struct( ...
		'Name',					'Blur radius (in pixel)', ...
		'Style',				'integer', ...
		'DefaultValue',			3, ...
		'Max',					64, ...
		'Min',					1, ...
		'LargeStep',			8, ...
		'SmallStep',			1);
	p2 = struct( ...
		'Name',					'Sigma', ...
		'Style',				'single', ...
		'DefaultValue',			0.5, ...
		'Max',					1, ...
		'Min',					0, ...
		'LargeStep',			1 / 10, ...
		'SmallStep',			1 / 100);

	P = struct( ...
		'FilterName',			'Gaussian blur', ...
		'AvailableImageType',	[0 0 0 1 1], ...
		'Class',				'blur&sharpen', ...
		'ParameterNumber',		2, ...
		'Parameters', 			{ {p1, p2} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	varargout{1} = imfilter(CX, ...
			fspecial('gaussian', FUNPARA{1}, FUNPARA{2}), 'replicate');
end