function varargout = filter_motionblur(varargin)

if nargin == 0
	p1 = struct( ...
		'Name',					'Blur length (in pixel)', ...
		'Style',				'integer', ...
		'DefaultValue',			10, ...
		'Max',					100, ...
		'Min',					1, ...
		'LargeStep',			5, ...
		'SmallStep',			1);
	p2 = struct( ...
		'Name',					'Angle', ...
		'Style',				'integer', ...
		'DefaultValue',			0, ...
		'Max',					180, ...
		'Min',					0, ...
		'LargeStep',			10, ...
		'SmallStep',			1);

	P = struct( ...
		'FilterName',			'Motion blur', ...
		'AvailableImageType',	[0 0 0 1 1], ...
		'Class',				'blur&sharpen', ...
		'ParameterNumber',		2, ...
		'Parameters', 			{ {p1, p2} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	varargout{1} = imfilter(CX, ...
			fspecial('motion', FUNPARA{1}, FUNPARA{2}), 'replicate');
end