function varargout = filter_unsharp(varargin)

if nargin == 0
	p1 = struct( ...
		'Name',					'Alpha', ...
		'Style',				'single', ...
		'DefaultValue',			0.2, ...
		'Max',					1, ...
		'Min',					0.01, ...
		'LargeStep',			1 / 10, ...
		'SmallStep',			1 / 100);
	p2 = struct( ...
		'Name',					'Transparency', ...
		'Style',				'single', ...
		'DefaultValue',			1, ...
		'Max',					1, ...
		'Min',					0, ...
		'LargeStep',			1 / 10, ...
		'SmallStep',			1 / 100);

	P = struct( ...
		'FilterName',			'Unsharp', ...
		'AvailableImageType',	[0 0 0 1 1], ...
		'Class',				'blur&sharpen', ...
		'ParameterNumber',		2, ...
		'Parameters', 			{ {p1, p2} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	varargout{1} = imlincomb(1 - FUNPARA{2}, CX, ...
			FUNPARA{2}, imfilter(CX, ...
			fspecial('unsharp', FUNPARA{1}), 'replicate' ) );
end