function varargout = filter_bwdist(varargin)

if nargin == 0
	p1 = struct( ...
		'Name',					'Method', ...
		'Style',				'popup', ...
		'DefaultValue',			1, ...
		'Items',				{ {'Euclidean', 'Cityblock', 'Chessboard', 'Quasi-euclidean'} } );
	P = struct( ...
		'FilterName',			'Distance transform', ...
		'AvailableImageType',	[0 1 0 0 0], ...
		'Class',				'morphological', ...
		'ParameterNumber',		1, ...
		'Parameters', 			{ {p1} });
	varargout{1} = P;
else
	CX = varargin{1};
	FUNPARA = varargin{2};
	method = {'euclidean', 'cityblock', 'chessboard', 'quasi-euclidean'};
	CX = bwdist(CX, method{FUNPARA{1}});
	CX = CX / max(max(CX));
	varargout{1} = CX;
end